Repository openshift/library-go, pull requests merged in 2018-12, with the labels that each got.

#122 Add function to apply CRDs
  pkg/operator/resource/resourceapply/apiextensions.go
  pkg/operator/resource/resourcemerge/apiextensions.go
Labels: approved, lgtm, size/M

#127 Add proc reaper for PID 1 containerized processes
  pkg/proc/reaper.go
  pkg/proc/reaper_unsupported.go
Labels: approved, lgtm, size/M

#128 fileobserve: handle panic when multiple files are changed
  pkg/controller/controllercmd/builder.go
Labels: approved, lgtm, size/XS

#121 events: add events to operator status controller
  pkg/operator/status/controller.go
  pkg/operator/status/controller_test.go
Labels: approved, lgtm, size/S

#129 fix the clusteroperator status update
  pkg/operator/status/status_controller.go
  pkg/operator/status/status_controller_test.go
Labels: approved, lgtm, size/M

#130 controllercmd: pass the right stop channel to run
  pkg/controller/controllercmd/cmd.go
Labels: approved, lgtm, size/XS

#132 Revert "config obverser: do not write invalid configs"
  pkg/operator/configobserver/config_observer_controller.go
  pkg/operator/configobserver/config_observer_controller_test.go
Labels: approved, lgtm, size/S

#135 configobserver: move install-config CIDR readers here
  pkg/operator/configobserver/network/observe_network.go
  pkg/operator/configobserver/network/observe_networking_test.go
Labels: approved, lgtm, size/L

#134 manage available and progressing status for static pods
  pkg/operator/staticpod/controller/installer/installer_controller.go
Labels: approved, lgtm, size/M

#136 unit test setConditions()
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
Labels: approved, lgtm, size/M

#137 add functions for finding resource hashes
  pkg/operator/resource/resourcehash/as_configmap.go
Labels: approved, lgtm, size/L

#138 configobserver: add owners to network helpers
  pkg/operator/configobserver/network/OWNERS
Labels: approved, lgtm, size/S

#140 staticpod: fix AllNodesAtLatestRevision wording
  pkg/operator/staticpod/controller/installer/installer_controller.go
Labels: approved, lgtm, size/XS

#141 Static pod revision history prune command
  glide.lock
  pkg/operator/staticpod/prune/cmd.go
  pkg/operator/staticpod/prune/cmd_test.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_swagger_doc_generated.go
  vendor/vbom.ml/util/.gitignore
  vendor/vbom.ml/util/LICENSE
  vendor/vbom.ml/util/README.md
  vendor/vbom.ml/util/cmd/short-regexp/main.go
  vendor/vbom.ml/util/doc.go
  vendor/vbom.ml/util/regexp.go
  vendor/vbom.ml/util/regexp_test.go
  vendor/vbom.ml/util/rope/README.md
  vendor/vbom.ml/util/rope/concat.go
  vendor/vbom.ml/util/rope/concat_test.go
  vendor/vbom.ml/util/rope/debug.go
  vendor/vbom.ml/util/rope/leaf.go
  vendor/vbom.ml/util/rope/leaf_test.go
  vendor/vbom.ml/util/rope/node.go
  vendor/vbom.ml/util/rope/node_test.go
  vendor/vbom.ml/util/rope/reader.go
  vendor/vbom.ml/util/rope/reader_test.go
  vendor/vbom.ml/util/rope/rebalance.go
  vendor/vbom.ml/util/rope/rebalance_test.go
  vendor/vbom.ml/util/rope/rope.go
  vendor/vbom.ml/util/rope/rope_test.go
  vendor/vbom.ml/util/sortorder/README.md
  vendor/vbom.ml/util/sortorder/doc.go
  vendor/vbom.ml/util/sortorder/natsort.go
  vendor/vbom.ml/util/sortorder/natsort_test.go
Labels: approved, lgtm, size/XXL

#147 add back available and progressing
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
Labels: approved, lgtm, size/S

#142 add functionality required to rotate certificates
  pkg/crypto/crypto.go
  pkg/crypto/crypto_test.go
  pkg/crypto/rotation.go
  pkg/crypto/rotation_test.go
  pkg/crypto/testfiles/tls-expired.crt
  pkg/crypto/testfiles/tls-multiple.crt
  pkg/crypto/testfiles/tls.crt
  pkg/crypto/testfiles/tls.key
Labels: approved, lgtm, size/L

#149 add simple ca and cert rotation
  pkg/operator/certrotation/cabundle.go
  pkg/operator/certrotation/cabundle_test.go
  pkg/operator/certrotation/client_cert_rotation_controller.go
  pkg/operator/certrotation/signer.go
  pkg/operator/certrotation/signer_test.go
  pkg/operator/certrotation/target.go
  pkg/operator/certrotation/target_test.go
  pkg/operator/certrotation/testfiles/tls-expired.crt
  pkg/operator/certrotation/testfiles/tls-multiple.crt
  pkg/operator/certrotation/testfiles/tls.crt
  pkg/operator/certrotation/testfiles/tls.key
Labels: approved, lgtm, size/XXL

#146 Pruning controller for static pod installer revisions
  Makefile
  pkg/operator/staticpod/controller/prune/bindata/bindata.go
  pkg/operator/staticpod/controller/prune/manifests/pruner-pod.yaml
  pkg/operator/staticpod/controller/prune/prune_controller.go
  pkg/operator/staticpod/controller/prune/prune_controller_test.go
Labels: approved, lgtm, size/XL
