Repository openshift/library-go, pull requests merged in 2018-09, with the labels that each got.

#24 add config file ref helpers
  glide.lock
  pkg/config/helpers/config_refs.go
  pkg/config/helpers/serving_info.go
  vendor/github.com/certifi/gocertifi/certifi.go
  vendor/github.com/certifi/gocertifi/gen.go
  vendor/github.com/certifi/gocertifi/tasks.py
  vendor/github.com/openshift/api/OWNERS
  vendor/github.com/openshift/api/apps/v1/consts.go
  vendor/github.com/openshift/api/apps/v1/deprecated_consts.go
  vendor/github.com/openshift/api/build/v1/generated.pb.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/build/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/generated.pb.go
  vendor/github.com/openshift/api/config/v1/generated.proto
  vendor/github.com/openshift/api/config/v1/stringsource.go
  vendor/github.com/openshift/api/config/v1/stringsource_test.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/hack/lib/init.sh
  vendor/github.com/openshift/api/hack/update-deepcopy.sh
  vendor/github.com/openshift/api/image/v1/generated.pb.go
  vendor/github.com/openshift/api/image/v1/generated.proto
  vendor/github.com/openshift/api/image/v1/types.go
  vendor/github.com/openshift/api/image/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/image/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/install.go
  vendor/github.com/openshift/api/kubecontrolplane/install.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/doc.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/generated.pb.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/generated.proto
  vendor/github.com/openshift/api/kubecontrolplane/v1/register.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/types.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/legacyconfig/v1/doc.go
  vendor/github.com/openshift/api/legacyconfig/v1/register.go
  vendor/github.com/openshift/api/legacyconfig/v1/serialization.go
  vendor/github.com/openshift/api/legacyconfig/v1/stringsource.go
  vendor/github.com/openshift/api/legacyconfig/v1/stringsource_test.go
  vendor/github.com/openshift/api/legacyconfig/v1/types.go
  vendor/github.com/openshift/api/legacyconfig/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/network/v1/generated.pb.go
  vendor/github.com/openshift/api/network/v1/generated.proto
  vendor/github.com/openshift/api/osin/install.go
  vendor/github.com/openshift/api/osin/v1/doc.go
  vendor/github.com/openshift/api/osin/v1/generated.pb.go
  vendor/github.com/openshift/api/osin/v1/generated.proto
  vendor/github.com/openshift/api/osin/v1/register.go
  vendor/github.com/openshift/api/osin/v1/types.go
  vendor/github.com/openshift/api/osin/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/osin/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/template/v1/consts.go
  vendor/github.com/pkg/profile/.travis.yml
Labels: size/XXL

#25 add image ref parsing utilities
  pkg/image/internal/digest/digest.go
  pkg/image/internal/digest/digester.go
  pkg/image/internal/digest/doc.go
  pkg/image/internal/reference/doc.go
  pkg/image/internal/reference/reference.go
  pkg/image/internal/reference/regexp.go
  pkg/image/reference/reference.go
  pkg/image/reference/reference_test.go
Labels: lgtm, size/XXL

#26 add recommended defaults and client helpers
  glide.lock
  glide.yaml
  pkg/config/configdefaults/config_default.go
  pkg/config/helpers/client.go
  vendor/github.com/openshift/api/config/v1/generated.pb.go
  vendor/github.com/openshift/api/config/v1/generated.proto
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/hack/update-deepcopy.sh
  vendor/github.com/openshift/api/install.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/generated.pb.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/generated.proto
  vendor/github.com/openshift/api/kubecontrolplane/v1/types.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/openshiftcontrolplane/install.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/doc.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/register.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/zz_generated.deepcopy.go
Labels: lgtm, size/XXL

#27 add helper for processing and writing assets using go templates
  pkg/assets/assets.go
  pkg/assets/assets_test.go
Labels: lgtm, size/L

#28 add missing file ref
  pkg/config/helpers/config_refs.go
Labels: lgtm, size/S

#30 align client helpers to types
  pkg/config/helpers/client.go
  pkg/config/helpers/config_refs.go
Labels: size/S

#31 assets: add helpers for recursive directory walk
  pkg/assets/assets.go
  pkg/assets/template.go
Labels: lgtm, size/L

#32 add ability to copy configmap/secret from another namespace
  pkg/operator/resource/resourceapply/core.go
Labels: lgtm, size/M

#33 add generic resource handling for resources that require no modification
  glide.lock
  pkg/operator/resource/resourceapply/generic.go
  pkg/operator/resource/resourceapply/generic_test.go
  vendor/github.com/openshift/api/install.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/register.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/zz_generated.deepcopy.go
Labels: size/L

#34 hard fail on failure
  pkg/operator/resource/resourceapply/generic.go
  pkg/operator/resource/resourceapply/generic_test.go
Labels: size/S

#35 Rename resourcecread to resourceread
  pkg/operator/resource/resourceread/apiextensions.go
  pkg/operator/resource/resourceread/apps.go
  pkg/operator/resource/resourceread/core.go
  pkg/operator/resource/resourceread/rbac.go
Labels: size/XS

#36 Remove liggit from approvers & reviewers
  OWNERS
Labels: size/XS
