Repository openshift/library-go, pull requests merged in 2018-05, with the labels that each got.

#7 Add linter
  .travis.yml
  Makefile
  hack/verify-golint.sh
Labels: lgtm, size/S

#8 add profiler
  glide.lock
  pkg/serviceability/profiler.go
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/authorization/v1/codec.go
  vendor/github.com/openshift/api/authorization/v1/generated.pb.go
  vendor/github.com/openshift/api/authorization/v1/generated.proto
  vendor/github.com/openshift/api/authorization/v1/register.go
  vendor/github.com/openshift/api/authorization/v1/types.go
  vendor/github.com/openshift/api/authorization/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/authorization/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/generated.pb.go
  vendor/github.com/openshift/api/config/v1/generated.proto
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/hack/lib/init.sh
  vendor/github.com/openshift/api/hack/update-deepcopy.sh
  vendor/github.com/openshift/api/operator/v1alpha1/doc.go
  vendor/github.com/openshift/api/operator/v1alpha1/generated.pb.go
  vendor/github.com/openshift/api/operator/v1alpha1/generated.proto
  vendor/github.com/openshift/api/operator/v1alpha1/register.go
  vendor/github.com/openshift/api/operator/v1alpha1/types.go
  vendor/github.com/openshift/api/operator/v1alpha1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/api/servicecertsigner/v1alpha1/doc.go
  vendor/github.com/openshift/api/servicecertsigner/v1alpha1/generated.pb.go
  vendor/github.com/openshift/api/servicecertsigner/v1alpha1/generated.proto
  vendor/github.com/openshift/api/servicecertsigner/v1alpha1/register.go
  vendor/github.com/openshift/api/servicecertsigner/v1alpha1/types.go
  vendor/github.com/openshift/api/servicecertsigner/v1alpha1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/servicecertsigner/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, size/XXL

#12 error handling fixes for controllers
  pkg/controller/controllercmd/builder.go
  pkg/controller/controllercmd/cmd.go
Labels: size/S
