Repository openshift/library-go, pull requests merged in 2018-11, with the labels that each got.

#69 Cleanup static pod controllers and add staticpod.NewControllers
  pkg/operator/staticpod/controller/common/interfaces.go
  pkg/operator/staticpod/controller/common/test_utils.go
  pkg/operator/staticpod/controller/deployment/deployment_controller.go
  pkg/operator/staticpod/controller/deployment/deployment_controller_test.go
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
  pkg/operator/staticpod/controller/node/node_controller.go
  pkg/operator/staticpod/controller/node/node_controller_test.go
  pkg/operator/staticpod/controllers.go
Labels: approved, lgtm, size/L

#70 Add installer-sa and cluster role binding controller to static pod operator
  Makefile
  glide.lock
  glide.yaml
  pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
  pkg/operator/staticpod/controller/backingresource/backing_resource_controller_test.go
  pkg/operator/staticpod/controller/backingresource/bindata/bindata.go
  pkg/operator/staticpod/controller/backingresource/manifests/installer-cluster-rolebinding.yaml
  pkg/operator/staticpod/controller/backingresource/manifests/installer-sa.yaml
  pkg/operator/staticpod/controllers.go
  vendor/github.com/jteeuwen/go-bindata/CONTRIBUTING.md
  vendor/github.com/jteeuwen/go-bindata/LICENSE
  vendor/github.com/jteeuwen/go-bindata/Makefile
  vendor/github.com/jteeuwen/go-bindata/README.md
  vendor/github.com/jteeuwen/go-bindata/asset.go
  vendor/github.com/jteeuwen/go-bindata/bytewriter.go
  vendor/github.com/jteeuwen/go-bindata/config.go
  vendor/github.com/jteeuwen/go-bindata/convert.go
  vendor/github.com/jteeuwen/go-bindata/convert_test.go
  vendor/github.com/jteeuwen/go-bindata/debug.go
  vendor/github.com/jteeuwen/go-bindata/doc.go
  vendor/github.com/jteeuwen/go-bindata/go-bindata/AppendSliceValue.go
  vendor/github.com/jteeuwen/go-bindata/go-bindata/main.go
  vendor/github.com/jteeuwen/go-bindata/go-bindata/version.go
  vendor/github.com/jteeuwen/go-bindata/release.go
  vendor/github.com/jteeuwen/go-bindata/restore.go
  vendor/github.com/jteeuwen/go-bindata/stringwriter.go
  vendor/github.com/jteeuwen/go-bindata/testdata/Makefile
  vendor/github.com/jteeuwen/go-bindata/testdata/dupname/foo/bar
  vendor/github.com/jteeuwen/go-bindata/testdata/dupname/foo_bar
  vendor/github.com/jteeuwen/go-bindata/testdata/in/a/test.asset
  vendor/github.com/jteeuwen/go-bindata/testdata/in/b/test.asset
  vendor/github.com/jteeuwen/go-bindata/testdata/in/c/test.asset
  vendor/github.com/jteeuwen/go-bindata/testdata/in/test.asset
  vendor/github.com/jteeuwen/go-bindata/testdata/out/compress-memcopy.go
  vendor/github.com/jteeuwen/go-bindata/testdata/out/compress-nomemcopy.go
  vendor/github.com/jteeuwen/go-bindata/testdata/out/debug.go
  vendor/github.com/jteeuwen/go-bindata/testdata/out/debug.go-bindata
  vendor/github.com/jteeuwen/go-bindata/testdata/out/nocompress-memcopy.go
  vendor/github.com/jteeuwen/go-bindata/testdata/out/nocompress-nomemcopy.go
  vendor/github.com/jteeuwen/go-bindata/testdata/symlinkFile/file1
  vendor/github.com/jteeuwen/go-bindata/testdata/symlinkParent/symlinkTarget
  vendor/github.com/jteeuwen/go-bindata/testdata/symlinkRecursiveParent/file1
  vendor/github.com/jteeuwen/go-bindata/testdata/symlinkRecursiveParent/symlinkTarget
  vendor/github.com/jteeuwen/go-bindata/testdata/symlinkSrc/file1
  vendor/github.com/jteeuwen/go-bindata/testdata/symlinkSrc/file2
  vendor/github.com/jteeuwen/go-bindata/testdata/symlinkSrc/file3
  vendor/github.com/jteeuwen/go-bindata/testdata/symlinkSrc/file4
  vendor/github.com/jteeuwen/go-bindata/toc.go
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XXL

#74 retry copying content in installer command
  pkg/operator/staticpod/installerpod/cmd.go
Labels: approved, lgtm, size/S

#76 refactor staticpod unit tests
  pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
  pkg/operator/staticpod/controller/backingresource/backing_resource_controller_test.go
  pkg/operator/staticpod/controller/deployment/deployment_controller_test.go
Labels: approved, lgtm, size/XL

#80 build: make verify-deps work on osx
  alpha-build-machinery/make/targets/openshift/deps.mk
Labels: size/XS

#79 build: fix GO_BUILD_PACKAGES to build binaries
  alpha-build-machinery/make/lib/golang.mk
Labels: approved, lgtm, size/XS

#81 alpha-build-machinery: fix verify-deps
  .gitignore
  alpha-build-machinery/make/targets/openshift/deps.mk
  vendor/bitbucket.org/ww/goautoneg/.hg_archival.txt
Labels: approved, lgtm, size/S

#83 add generic way to observe changes in files and react to them
  glide.lock
  glide.yaml
  pkg/controller/controllercmd/builder.go
  pkg/controller/controllercmd/cmd.go
  pkg/controller/fileobserver/observer.go
  pkg/controller/fileobserver/observer_default.go
  pkg/controller/fileobserver/observer_linux.go
  pkg/controller/fileobserver/observer_test.go
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_console.go
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_idp.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/types_project.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/zz_generated.deepcopy.go
  vendor/github.com/sigma/go-inotify/LICENSE
  vendor/github.com/sigma/go-inotify/PATENTS
  vendor/github.com/sigma/go-inotify/README.md
  vendor/github.com/sigma/go-inotify/inotify_linux.go
  vendor/github.com/sigma/go-inotify/inotify_linux_test.go
Labels: approved, lgtm, size/XXL

#85 update for v1 operator api
  pkg/operator/v1helpers/helper_test.go
  pkg/operator/v1helpers/helpers.go
  pkg/operator/v1staticpod/controller/backingresource/backing_resource_controller.go
  pkg/operator/v1staticpod/controller/backingresource/backing_resource_controller_test.go
  pkg/operator/v1staticpod/controller/backingresource/bindata/bindata.go
  pkg/operator/v1staticpod/controller/backingresource/manifests/installer-cluster-rolebinding.yaml
  pkg/operator/v1staticpod/controller/backingresource/manifests/installer-sa.yaml
  pkg/operator/v1staticpod/controller/common/interfaces.go
  pkg/operator/v1staticpod/controller/common/test_utils.go
  pkg/operator/v1staticpod/controller/deployment/deployment_controller.go
  pkg/operator/v1staticpod/controller/deployment/deployment_controller_test.go
  pkg/operator/v1staticpod/controller/installer/installer_controller.go
  pkg/operator/v1staticpod/controller/installer/installer_controller_test.go
  pkg/operator/v1staticpod/controller/node/node_controller.go
  pkg/operator/v1staticpod/controller/node/node_controller_test.go
  pkg/operator/v1staticpod/controllers.go
  pkg/operator/v1staticpod/installerpod/cmd.go
  pkg/operator/v1staticpod/installerpod/cmd_test.go
  pkg/operator/v1status/controller.go
Labels: approved, lgtm, size/XXL

#87 serving: register metav1 types to api server
  pkg/config/serving/server.go
Labels: approved, lgtm, size/XS

#86 staticpod: wait for PodReady condition
  pkg/operator/staticpod/controller/common/test_utils.go
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
  pkg/operator/staticpod/controllers.go
Labels: approved, lgtm, size/XL

#89 staticpod: sync installer with v1alpha1 changes
  pkg/operator/v1staticpod/controller/common/test_utils.go
  pkg/operator/v1staticpod/controller/installer/installer_controller.go
  pkg/operator/v1staticpod/controller/installer/installer_controller_test.go
  pkg/operator/v1staticpod/controllers.go
Labels: approved, lgtm, size/XL

#90 staticpod: sync installer with v1alpha1 changes
  pkg/operator/v1staticpod/controller/installer/installer_controller.go
Labels: approved, lgtm, size/M

#91 alpha-build-machinery: fail 'make test JUNITFILE=...' on test failure
  alpha-build-machinery/make/targets/golang/test-unit.mk
Labels: approved, lgtm, size/XS

#93 fileobserver: use polling to observe file changes
  pkg/controller/controllercmd/builder.go
  pkg/controller/fileobserver/observer.go
  pkg/controller/fileobserver/observer_default.go
  pkg/controller/fileobserver/observer_linux.go
  pkg/controller/fileobserver/observer_polling.go
  pkg/controller/fileobserver/observer_polling_test.go
  pkg/controller/fileobserver/observer_test.go
Labels: approved, lgtm, size/L

#95 add skeleton for operator config observation
  pkg/operator/configobserver/config_observer_controller.go
  pkg/operator/configobserver/config_observer_controller_test.go
Labels: approved, lgtm, size/L

#96 fix serving cert path
  pkg/controller/controllercmd/cmd.go
Labels: approved, lgtm, size/XS

#98 update generation handling for operator v1
  pkg/operator/resource/resourcemerge/apps.go
Labels: approved, lgtm, size/M

#101 use protobuf when possible
  pkg/config/client/client_config.go
Labels: approved, lgtm, size/XS

#104 Add simple event recorder
  pkg/operator/events/recorder.go
  pkg/operator/events/recorder_deployment.go
  pkg/operator/events/recorder_deployment_test.go
  pkg/operator/events/recorder_test.go
Labels: approved, lgtm, size/L

#99 observer: fail when requesting empty filename for observing
  pkg/controller/fileobserver/observer_polling.go
Labels: approved, lgtm, size/XS

#103 expose the configuration file content for a controller
  pkg/controller/controllercmd/builder.go
  pkg/controller/controllercmd/cmd.go
  pkg/controller/controllercmd/flags.go
Labels: approved, lgtm, size/M

#105 Wire event recorder
  pkg/controller/controllercmd/builder.go
  pkg/controller/controllercmd/cmd.go
  pkg/controller/fileobserver/observer.go
  pkg/operator/configobserver/config_observer_controller.go
  pkg/operator/configobserver/config_observer_controller_test.go
  pkg/operator/events/OWNERS
  pkg/operator/events/recorder.go
  pkg/operator/events/recorder_deployment.go
  pkg/operator/events/recorder_deployment_test.go
  pkg/operator/events/recorder_in_memory.go
  pkg/operator/events/recorder_logging.go
  pkg/operator/events/recorder_test.go
  pkg/operator/resource/resourceapply/generic.go
  pkg/operator/resource/resourceapply/generic_test.go
  pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
  pkg/operator/staticpod/controller/backingresource/backing_resource_controller_test.go
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
  pkg/operator/staticpod/controller/node/node_controller.go
  pkg/operator/staticpod/controller/node/node_controller_test.go
  pkg/operator/staticpod/controller/revision/deployment_controller.go
  pkg/operator/staticpod/controller/revision/deployment_controller_test.go
  pkg/operator/staticpod/controllers.go
  pkg/operator/v1alpha1staticpod/controller/backingresource/backing_resource_controller.go
  pkg/operator/v1alpha1staticpod/controller/backingresource/backing_resource_controller_test.go
  pkg/operator/v1alpha1staticpod/controllers.go
Labels: approved, lgtm, size/XL

#108 union and set operator failing condition
  pkg/operator/status/controller.go
  pkg/operator/status/controller_test.go
Labels: approved, lgtm, size/L

#110 Pass controller context struct to StartFunc
  pkg/controller/controllercmd/builder.go
  pkg/controller/controllercmd/cmd.go
  pkg/controller/controllercmd/flags.go
Labels: approved, lgtm, size/M

#111 installer: fix revision update events
  pkg/operator/staticpod/controller/installer/installer_controller.go
Labels: approved, lgtm, size/S

#112 tolerate imperfect pod specs
  pkg/operator/events/recorder.go
Labels: approved, lgtm, size/S

#113 use upstream event recorder
  pkg/controller/controllercmd/builder.go
  pkg/operator/events/recorder_upstream.go
Labels: approved, lgtm, size/M

#115 fix diff calculations for roleref and services
  pkg/operator/resource/resourceapply/core.go
  pkg/operator/resource/resourceapply/rbac.go
Labels: approved, lgtm, size/M

#114 events: wire events directly to resourceapply
  pkg/operator/resource/resourceapply/apps.go
  pkg/operator/resource/resourceapply/core.go
  pkg/operator/resource/resourceapply/core_test.go
  pkg/operator/resource/resourceapply/event_helpers.go
  pkg/operator/resource/resourceapply/generic.go
  pkg/operator/resource/resourceapply/generic_test.go
  pkg/operator/resource/resourceapply/rbac.go
  pkg/operator/resource/resourceapply/storage.go
  pkg/operator/staticpod/controller/revision/deployment_controller.go
  pkg/operator/v1alpha1staticpod/controller/deployment/deployment_controller.go
  pkg/operator/v1alpha1staticpod/controller/deployment/deployment_controller_test.go
  pkg/operator/v1alpha1staticpod/controllers.go
Labels: approved, lgtm, size/L

#117 wire events to config observer functions
  pkg/operator/configobserver/config_observer_controller.go
  pkg/operator/configobserver/config_observer_controller_test.go
Labels: approved, lgtm, size/S

#118 events: fix reporting kind from resource apply
  pkg/operator/resource/resourceapply/event_helpers.go
Labels: approved, lgtm, size/M

#119 events: use deployment as ownerRef involved object
  pkg/controller/controllercmd/builder.go
  pkg/operator/events/recorder.go
  pkg/operator/events/recorder_test.go
Labels: approved, lgtm, size/L

#124 staticpod: document controllers
  pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/node/node_controller.go
  pkg/operator/staticpod/controller/revision/deployment_controller.go
Labels: approved, lgtm, size/S

#106 add mfojtik to owners for fileobserver
  pkg/controller/fileobserver/OWNERS
Labels: approved, lgtm, size/XS

#125 resourceapply: fix event helpers messages
  pkg/operator/resource/resourceapply/event_helpers.go
Labels: approved, lgtm, size/S

#126 resourceapply: add event helpers unit tests
  pkg/operator/resource/resourceapply/event_helpers.go
  pkg/operator/resource/resourceapply/event_helpers_test.go
Labels: approved, lgtm, size/L
