Repository openshift/library-go, pull requests merged in 2019-12, with the labels that each got.

#621 switches the remaining controllers to use context instead of stopCh
  pkg/operator/certrotation/client_cert_rotation_controller.go
  pkg/operator/configobserver/config_observer_controller.go
  pkg/operator/management/management_state_controller.go
  pkg/operator/resourcesynccontroller/resourcesync_controller.go
  pkg/operator/resourcesynccontroller/resourcesync_controller_test.go
  pkg/operator/status/status_controller.go
Labels: approved, lgtm, size/M

#624 Bug 1779263: encryption: cope with missing revisions on upgrade
  pkg/operator/encryption/deployer/revisionedpod.go
  pkg/operator/encryption/deployer/revisionedpod_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#609 Verify outbound manifests now that schema1 support is dropped
  pkg/image/registryclient/client.go
  pkg/image/registryclient/client_test.go
Labels: approved, lgtm, size/M

#548 Add MapToEnvVars helper function
  pkg/operator/v1helpers/helpers.go
Labels: approved, lgtm, size/S

#594 Added api to check if bootstrap user is enabled
  pkg/authentication/bootstrapauthenticator/bootstrap.go
  pkg/authentication/bootstrapauthenticator/bootstrap_test.go
Labels: approved, lgtm, size/L

#636 Bug 1779796: controllercmd: set TCP timeout on leader election client
  pkg/controller/controllercmd/builder.go
Labels: approved, lgtm, size/XS

#632 pkg/operator/status: Add configurable inertia
  pkg/operator/status/condition.go
  pkg/operator/status/inertia.go
  pkg/operator/status/status_controller.go
  pkg/operator/status/status_controller_test.go
Labels: approved, lgtm, size/L

#639 show the individual reasons for status conditions on union
  pkg/operator/status/condition.go
  pkg/operator/status/status_controller_test.go
Labels: approved, lgtm, size/M

#638 bug 1781804: fix revision pending message
  pkg/operator/staticpod/controller/installer/installer_controller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#642 installerpodstate: fix reporting InstallerPodNetworkingDegraded
  pkg/operator/staticpod/controller/installerstate/installer_state_controller.go
Labels: approved, lgtm, size/XS

#644 controllercmd: Only observe config file if provided
  pkg/controller/controllercmd/cmd.go
Labels: approved, lgtm, size/XS

#630 Bug 1780809: kube-apiserver stuck in Progressing/Degraded if target revision is deleted
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#645 ApplySecret: Don't erase injected Data for ServiceAccounts
  pkg/operator/resource/resourceapply/core.go
  pkg/operator/resource/resourceapply/core_test.go
Labels: approved, lgtm, size/L

#647 controllercmd: pass context via func argument
  pkg/controller/controllercmd/builder.go
  pkg/controller/controllercmd/cmd.go
Labels: approved, lgtm, size/S

#649 bug 1784052: delete secrets if immutable fields don't match
  pkg/operator/resource/resourceapply/core.go
  pkg/operator/resource/resourceapply/event_helpers.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#650 Add verify-deps for go mod
  alpha-build-machinery/make/default.example.mk.help.log
  alpha-build-machinery/make/operator.example.mk.help.log
  alpha-build-machinery/make/targets/openshift/deps-glide.mk
  alpha-build-machinery/make/targets/openshift/deps-gomod.mk
  alpha-build-machinery/make/targets/openshift/deps.mk
  glide.lock
  glide.yaml
Labels: approved, lgtm, size/XXL

#651 rename typo to dependencymagnet
  pkg/dependencymagnet/doc.go
Labels: approved, lgtm, size/XS
