Repository openshift/library-go, pull requests merged in 2019-11, with the labels that each got.

#560 Add SubjectKeyId and AuthorityKeyId to server certs
  pkg/crypto/crypto.go
  pkg/crypto/crypto_test.go
Labels: approved, lgtm, size/M

#577 encryption: add events to controllers
  pkg/operator/encryption/controllers/key_controller.go
  pkg/operator/encryption/controllers/key_controller_test.go
  pkg/operator/encryption/controllers/prune_controller.go
  pkg/operator/encryption/controllers/prune_controller_test.go
  pkg/operator/encryption/controllers/state_controller.go
  pkg/operator/encryption/controllers/state_controller_test.go
  pkg/operator/encryption/testing/helpers.go
  pkg/operator/events/eventstesting/recorder_wrapper.go
Labels: approved, lgtm, size/L

#578 cert-syncer: add --tls-server-name-override flag
  pkg/operator/staticpod/certsyncpod/certsync_cmd.go
Labels: approved, lgtm, size/XS

#580 adds e2e encryption test cases to library-go
  test/library/encryption/assertion.go
  test/library/encryption/helpers.go
  test/library/encryption/scenarios.go
Labels: approved, lgtm, size/L

#581 verify resources in the encryption config
  test/library/encryption/assertion.go
  test/library/encryption/scenarios.go
Labels: approved, lgtm, size/M

#582 prints events from the operator ns on failure
  test/library/encryption/e_log.go
  test/library/encryption/helpers.go
  test/library/encryption/scenarios.go
Labels: approved, lgtm, size/M

#583 allows for setting a namespace for operator's events
  test/library/encryption/e_log.go
  test/library/encryption/helpers.go
  test/library/encryption/scenarios.go
Labels: approved, lgtm, size/S

#579 Allow rotation "only when certs are expired"
  pkg/operator/certrotation/signer.go
  pkg/operator/certrotation/target.go
  pkg/operator/certrotation/target_test.go
Labels: approved, lgtm, size/M

#585 encryption: forgiving error handling for migration for retryable errors
  pkg/operator/encryption/controllers/migrators/errors.go
  pkg/operator/encryption/controllers/migrators/inprocess.go
Labels: approved, lgtm, size/L

#584 fix workqueue and client metrics registration
  pkg/controller/metrics/client_metrics.go
  pkg/controller/metrics/workqueue_metrics.go
Labels: approved, lgtm, size/L

#588 Fix stack overflow with controller metrics
  pkg/controller/metrics/client_metrics.go
  pkg/controller/metrics/client_metrics_test.go
Labels: approved, lgtm, size/S

#586 File observer fixes
  pkg/controller/fileobserver/observer.go
  pkg/controller/fileobserver/observer_polling.go
  pkg/controller/fileobserver/observer_polling_test.go
Labels: approved, lgtm, size/L

#592 encryption: fix error logic take 2, add logs and retry migrations
  pkg/operator/encryption/controllers/migration_controller.go
  pkg/operator/encryption/controllers/migration_controller_test.go
  pkg/operator/encryption/controllers/migrators/errors.go
  pkg/operator/encryption/controllers/migrators/inprocess.go
  pkg/operator/encryption/controllers/migrators/inprocess_test.go
  pkg/operator/encryption/controllers/migrators/kubestorageversionmigrator.go
  pkg/operator/encryption/controllers/migrators/types.go
  test/e2e-encryption/encryption_test.go
Labels: approved, lgtm, size/L

#587 image/reference: A ref with tag and ID should prefer ID
  pkg/image/reference/reference.go
Labels: approved, lgtm, size/XS

#591 verifies input params of JSONPatchSecret function to prevent npe
  pkg/operator/resource/resourceapply/apiextensions.go
  pkg/operator/resource/resourceapply/apiregistration.go
  pkg/operator/resource/resourceapply/apps.go
  pkg/operator/resource/resourceapply/core.go
  pkg/operator/resource/resourceapply/core_test.go
  pkg/operator/resource/resourceapply/json_patch_helpers.go
  pkg/operator/resource/resourceapply/json_patch_helpers_test.go
  pkg/operator/resource/resourceapply/monitoring.go
  pkg/operator/resource/resourceapply/rbac.go
  pkg/operator/resource/resourceapply/storage.go
  pkg/operator/revisioncontroller/revision_controller.go
  pkg/operator/status/status_controller.go
Labels: approved, lgtm, size/M

#593 fileobserver: fix logging
  pkg/controller/fileobserver/observer_polling.go
Labels: approved, lgtm, size/XS

#598 Bug 1772190: certsyncpod: reduce amount of events produced by removing files
  pkg/operator/staticpod/certsyncpod/certsync_controller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#604 Pin dependencies for release-4.3
  glide.lock
  glide.yaml
  pkg/operator/configobserver/featuregates/observe_featuregates_test.go
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_tlssecurityprofile.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/console/v1/0000_10_consoleyamlsample.crd.yaml
  vendor/github.com/openshift/api/console/v1/types_console_yaml_sample.go
  vendor/github.com/openshift/api/console/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/glide.lock
  vendor/github.com/openshift/api/glide.yaml
  vendor/github.com/openshift/api/hack/lib/init.sh
  vendor/github.com/openshift/api/hack/update-deepcopy.sh
  vendor/github.com/openshift/api/imageregistry/install.go
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/doc.go
  vendor/github.com/openshift/api/imageregistry/v1/register.go
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/install.go
  vendor/github.com/openshift/api/operator/v1/0000_30_openshift-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_dns-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/operator/v1/types_dns.go
  vendor/github.com/openshift/api/operator/v1/types_openshiftapiserver.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/samples/install.go
  vendor/github.com/openshift/api/samples/v1/0000_10_samplesconfig.crd.yaml
  vendor/github.com/openshift/api/samples/v1/doc.go
  vendor/github.com/openshift/api/samples/v1/generated.pb.go
  vendor/github.com/openshift/api/samples/v1/generated.proto
  vendor/github.com/openshift/api/samples/v1/register.go
  vendor/github.com/openshift/api/samples/v1/types_config.go
  vendor/github.com/openshift/api/samples/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/samples/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/servicecertsigner/v1alpha1/types.go
  vendor/github.com/openshift/api/servicecertsigner/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/glide.lock
  vendor/github.com/openshift/client-go/glide.yaml
Labels: approved, lgtm, size/XXL

#599 adds an e2e load test scenario for encryption/migration
  test/library/encryption/perf_helpers.go
  test/library/encryption/perf_scenarios.go
Labels: approved, lgtm, size/L

#595 adds a list processor for migrating resources in parallel
  pkg/operator/encryption/controllers/migrators/inprocess.go
  pkg/operator/encryption/controllers/migrators/inprocess_processor.go
  pkg/operator/encryption/controllers/migrators/inprocess_processor_test.go
Labels: approved, lgtm, size/XL

#603 Bug 1775057: encryption: keep last read key after migration for easier backup/restore
  pkg/operator/encryption/controllers/state_controller_test.go
  pkg/operator/encryption/statemachine/transition.go
  pkg/operator/encryption/statemachine/transition_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#610 encryption: adapt log output verbosity to default of 2
  pkg/operator/encryption/controllers/migrators/inprocess.go
  pkg/operator/encryption/controllers/migrators/inprocess_processor.go
  pkg/operator/encryption/controllers/prune_controller.go
Labels: approved, lgtm, size/S

#611 encryption: improve EncryptionWriteKeyTriggeredInternal reasons
  pkg/operator/encryption/controllers/key_controller.go
  pkg/operator/encryption/controllers/key_controller_test.go
Labels: approved, lgtm, size/M

#613 prevents WaitGroup from being copied after the first use
  test/library/encryption/perf_helpers.go
Labels: approved, lgtm, size/XS

#612 encryption: enrich current state with secret info to avoid spurious events
  pkg/operator/encryption/controllers.go
  pkg/operator/encryption/controllers/key_controller.go
  pkg/operator/encryption/controllers/key_controller_test.go
  pkg/operator/encryption/controllers/migration_controller.go
  pkg/operator/encryption/controllers/migration_controller_test.go
  pkg/operator/encryption/controllers/state_controller.go
  pkg/operator/encryption/controllers/state_controller_test.go
  pkg/operator/encryption/encryptionconfig/config.go
  pkg/operator/encryption/encryptionconfig/config_test.go
  pkg/operator/encryption/secrets/secrets.go
  pkg/operator/encryption/statemachine/transition.go
Labels: approved, lgtm, size/L

#614 staticpod: deprecate service monitor controller
  pkg/operator/staticpod/controllers.go
Labels: approved, lgtm, size/S

#615 encryption: fix freezing key controller
  pkg/operator/encryption/controllers/key_controller.go
  pkg/operator/encryption/controllers/key_controller_test.go
  pkg/operator/encryption/controllers/prune_controller_test.go
  pkg/operator/encryption/state/helpers.go
  pkg/operator/encryption/statemachine/transition.go
  pkg/operator/encryption/statemachine/transition_test.go
  test/e2e-encryption/encryption_test.go
Labels: approved, lgtm, size/L

#597 Bug 1771665: Backport file observer fixes
  pkg/controller/fileobserver/observer.go
  pkg/controller/fileobserver/observer_polling.go
  pkg/controller/fileobserver/observer_polling_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#605 encryption: add Encrypted condition
  pkg/operator/encryption/controllers.go
  pkg/operator/encryption/controllers/condition_controller.go
  test/e2e-encryption/encryption_test.go
Labels: approved, lgtm, size/L

#617 encryption: fix repeated state change events
  pkg/operator/encryption/controllers/state_controller.go
Labels: approved, lgtm, size/S

#616 staticpod: switch controllers to use context instead of stopCh
  pkg/operator/loglevel/logging_controller.go
  pkg/operator/revisioncontroller/revision_controller.go
  pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/installerstate/installer_state_controller.go
  pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
  pkg/operator/staticpod/controller/node/node_controller.go
  pkg/operator/staticpod/controller/prune/prune_controller.go
  pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  pkg/operator/staticpod/controllers.go
  pkg/operator/unsupportedconfigoverridescontroller/unsupportedconfigoverrides_controller.go
Labels: approved, lgtm, size/L

#618 inprocess migrator metrics
  pkg/operator/encryption/controllers/migrators/inprocess.go
  pkg/operator/encryption/controllers/migrators/inprocess_processor.go
  pkg/operator/encryption/controllers/migrators/inprocess_processor_test.go
  pkg/operator/encryption/controllers/migrators/metrics.go
Labels: approved, lgtm, size/L

#619 encryption: retry requests during e2e when kube-apiserver restarts
  test/library/encryption/errors.go
  test/library/encryption/helpers.go
Labels: approved, lgtm, size/M

#620 adds context to ControllerContext for signal and cancellation propagation
  pkg/controller/controllercmd/builder.go
Labels: approved, lgtm, size/S

#622 Bug 1776797: encryption: speed-up, Encrypted condition, allow backup/restore
  pkg/operator/encryption/controllers.go
  pkg/operator/encryption/controllers/condition_controller.go
  pkg/operator/encryption/controllers/key_controller.go
  pkg/operator/encryption/controllers/key_controller_test.go
  pkg/operator/encryption/controllers/migration_controller.go
  pkg/operator/encryption/controllers/migration_controller_test.go
  pkg/operator/encryption/controllers/migrators/inprocess.go
  pkg/operator/encryption/controllers/migrators/inprocess_processor.go
  pkg/operator/encryption/controllers/migrators/inprocess_processor_test.go
  pkg/operator/encryption/controllers/migrators/metrics.go
  pkg/operator/encryption/controllers/prune_controller.go
  pkg/operator/encryption/controllers/prune_controller_test.go
  pkg/operator/encryption/controllers/state_controller.go
  pkg/operator/encryption/controllers/state_controller_test.go
  pkg/operator/encryption/encryptionconfig/config.go
  pkg/operator/encryption/encryptionconfig/config_test.go
  pkg/operator/encryption/secrets/secrets.go
  pkg/operator/encryption/state/helpers.go
  pkg/operator/encryption/statemachine/transition.go
  pkg/operator/encryption/statemachine/transition_test.go
  test/e2e-encryption/encryption_test.go
  test/library/encryption/errors.go
  test/library/encryption/helpers.go
  test/library/encryption/perf_helpers.go
  test/library/encryption/perf_scenarios.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL
