Repository openshift/library-go, pull requests merged in 2019-05, with the labels that each got.

#380 fix updatestatus return value
  pkg/operator/v1helpers/helpers.go
Labels: approved, lgtm, size/XS

#382 installer: add revision suffix to required resources
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
Labels: approved, lgtm, size/M

#383 installer: refactor code style for checking required resources
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
Labels: approved, lgtm, size/M

#390 only acccept cloud config files for certain providers
  pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
Labels: approved, lgtm, size/XS

#385 certsyncpod: default namespace to POD_NAMESPACE env var
  pkg/operator/staticpod/certsyncpod/certsync_cmd.go
Labels: approved, lgtm, size/XS

#387 controllercmd: handle TERM signals gracefully in operator
  pkg/controller/controllercmd/cmd.go
Labels: approved, lgtm, size/S

#386 Specify no cloud provider for the baremetal platform.
  pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
  pkg/operator/configobserver/cloudprovider/observe_cloudprovider_test.go
Labels: approved, lgtm, size/XS

#391 installerpod: save secrets 0600
  pkg/operator/staticpod/installerpod/cmd.go
Labels: approved, lgtm, size/XS

#393 expose run-once and wait-for-ready options on cert rotation
  pkg/operator/certrotation/client_cert_rotation_controller.go
Labels: approved, lgtm, size/S

#394 Fix copies
  pkg/operator/resource/resourceapply/rbac.go
Labels: approved, lgtm, size/XS

#396 operator/condition: add initial list of condition names
  pkg/operator/certrotation/client_cert_rotation_controller.go
  pkg/operator/condition/condition.go
  pkg/operator/configobserver/config_observer_controller.go
  pkg/operator/configobserver/config_observer_controller_test.go
  pkg/operator/management/management_state_controller.go
  pkg/operator/resourcesynccontroller/resourcesync_controller.go
  pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
  pkg/operator/staticpod/controller/backingresource/backing_resource_controller_test.go
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
  pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
  pkg/operator/staticpod/controller/revision/revision_controller.go
  pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  pkg/operator/unsupportedconfigoverridescontroller/unsupportedconfigoverrides_controller.go
Labels: approved, lgtm, size/L

#392 file-watcher-watchdog: add command to kill the operand process on file changes
  pkg/operator/watchdog/cmd.go
  pkg/operator/watchdog/cmd_test.go
  pkg/operator/watchdog/proc.go
  pkg/operator/watchdog/proc_test.go
Labels: approved, lgtm, size/XL

#402 bump openshift/api and openshift/client-go for 1.14.0
  glide.lock
  glide.yaml
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/apps/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/apps/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/authorization/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/authorization/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/glide.lock
  vendor/github.com/openshift/client-go/glide.yaml
  vendor/github.com/openshift/client-go/image/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/oauth/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/oauth/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/project/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/project/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/quota/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/quota/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/servicecertsigner/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/servicecertsigner/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/template/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/template/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/user/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/user/clientset/versioned/fake/clientset_generated.go
  vendor/google.golang.org/appengine/README.md
  vendor/google.golang.org/appengine/datastore/internal/cloudkey/cloudkey.go
  vendor/google.golang.org/appengine/datastore/internal/cloudpb/entity.pb.go
  vendor/google.golang.org/appengine/datastore/key.go
  vendor/google.golang.org/appengine/datastore/keycompat.go
  vendor/google.golang.org/appengine/datastore/keycompat_test.go
  vendor/gopkg.in/yaml.v2/decode_test.go
  vendor/gopkg.in/yaml.v2/encode.go
  vendor/gopkg.in/yaml.v2/encode_test.go
Labels: approved, lgtm, size/XXL

#403 operator: fix named queue names to prevent prometheus errors
  pkg/operator/certrotation/client_cert_rotation_controller.go
  pkg/operator/management/management_state_controller.go
  pkg/operator/status/status_controller.go
Labels: approved, lgtm, size/XS

#401 pin dependencies for openshift/api to release-4.1
  glide.lock
  glide.yaml
  vendor/github.com/openshift/api/Dockerfile.build
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/OWNERS
  vendor/github.com/openshift/api/authorization/v1/generated.proto
  vendor/github.com/openshift/api/authorization/v1/types.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/hack/update-protobuf.sh
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_etcd.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/types_serviceca.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.pb.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/google.golang.org/appengine/README.md
  vendor/google.golang.org/appengine/datastore/internal/cloudkey/cloudkey.go
  vendor/google.golang.org/appengine/datastore/internal/cloudpb/entity.pb.go
  vendor/google.golang.org/appengine/datastore/key.go
  vendor/google.golang.org/appengine/datastore/keycompat.go
  vendor/google.golang.org/appengine/datastore/keycompat_test.go
  vendor/sigs.k8s.io/controller-tools/Gopkg.lock
  vendor/sigs.k8s.io/controller-tools/Gopkg.toml
  vendor/sigs.k8s.io/controller-tools/pkg/crd/generator/generator.go
Labels: approved, lgtm, size/XXL

#405 add authorization helper functions
  pkg/authorization/authorizationutil/subject.go
  pkg/authorization/authorizationutil/util.go
Labels: approved, lgtm, size/L

#406 add envresolve package
  pkg/build/envresolve/env.go
  pkg/build/envresolve/kube_copy.go
Labels: approved, lgtm, size/L

#410 add bootstrap authenticator which is used by oauth-server and kube-apiserver
  pkg/authentication/bootstrapauthenticator/bootstrap.go
Labels: approved, lgtm, size/L

#414 pkg/template: template generator
  pkg/template/OWNERS
  pkg/template/generator/doc.go
  pkg/template/generator/examples/doc.go
  pkg/template/generator/examples/remotevalue.go
  pkg/template/generator/examples/remotevalue_test.go
  pkg/template/generator/expressionvalue.go
  pkg/template/generator/expressionvalue_test.go
  pkg/template/generator/generator.go
Labels: approved, lgtm, size/L

#415 provide function to init logrus from klog
  pkg/serviceability/logrus.go
Labels: approved, lgtm, size/S

#417 add resource read function to consume bytes
  pkg/config/helpers/readresource.go
Labels: approved, lgtm, size/L

#416 Add pkg/oauth helpers
  pkg/oauth/oauthdiscovery/discovery.go
  pkg/oauth/oauthdiscovery/urls.go
Labels: approved, lgtm, size/M

#418 add name generation methods
  pkg/build/naming/namer.go
  pkg/build/naming/namer_test.go
  pkg/security/ldapquery/errors.go
  pkg/security/ldapquery/query.go
  pkg/security/ldapquery/query_test.go
  pkg/security/ldapquery/types.go
Labels: approved, lgtm, size/L

#419 Add image utils
  pkg/image/imageutil/helpers.go
  pkg/image/referencemutator/builds.go
  pkg/image/referencemutator/builds_test.go
  pkg/image/referencemutator/meta.go
  pkg/image/referencemutator/pods.go
  pkg/image/referencemutator/pods_test.go
  pkg/image/trigger/annotations.go
  pkg/image/trigger/annotations_test.go
  pkg/image/trigger/interfaces.go
  pkg/image/trigger/types.go
Labels: approved, lgtm, size/XXL

#422 Add networkutils package
  pkg/network/networkutils/networkutils.go
  pkg/network/networkutils/networkutils_test.go
Labels: approved, lgtm, size/L

#423 move clusterquotamapping to library-go
  pkg/quota/clusterquotamapping/clusterquotamapping.go
  pkg/quota/clusterquotamapping/clusterquotamapping_test.go
  pkg/quota/clusterquotamapping/helpers.go
  pkg/quota/clusterquotamapping/mapper.go
Labels: approved, lgtm, size/XXL

#427 move scopes and groupification out
  pkg/authorization/scopemetadata/clusterrole_describers.go
  pkg/authorization/scopemetadata/describers.go
  pkg/authorization/scopemetadata/user_describers.go
  pkg/authorization/scopemetadata/validation.go
  pkg/authorization/scopemetadata/validation_test.go
  pkg/legacyapi/legacygroupification/groupification.go
Labels: approved, lgtm, size/XL

#426 apps: move apps utils
  pkg/apps/OWNERS
  pkg/apps/appsserialization/scheme.go
  pkg/apps/appsserialization/scheme_test.go
  pkg/apps/appsserialization/serialize.go
  pkg/apps/appsutil/const.go
  pkg/apps/appsutil/rc_scale_client.go
  pkg/apps/appsutil/util.go
  pkg/apps/appsutil/util_test.go
Labels: approved, lgtm, size/XXL

#429 Add missing unit test for image utils
  pkg/image/imageutil/helpers_test.go
Labels: approved, lgtm, size/S

#428 add writeyaml function
  pkg/authorization/scopemetadata/clusterrole_describers.go
  pkg/authorization/scopemetadata/describers.go
  pkg/authorization/scopemetadata/user_describers.go
  pkg/authorization/scopemetadata/validation.go
  pkg/authorization/scopemetadata/validation_test.go
  pkg/config/helpers/readresource.go
Labels: approved, lgtm, size/M

#424 Bug 1714158: Prevent cert-syncer to act on stale data
  pkg/operator/staticpod/certsyncpod/certsync_cmd.go
  pkg/operator/staticpod/certsyncpod/certsync_controller.go
Labels: approved, lgtm, size/L
