Repository openshift/library-go, pull requests merged in 2019-10, with the labels that each got.

#523 pkg/assets/create: Fix "unstructed" -> "unstructured" typo
  pkg/assets/create/creater.go
Labels: approved, lgtm, size/XS

#535 Add -x (overwrite) flag to crd-schema-gen command
  alpha-build-machinery/make/examples/multiple-binaries/Makefile.test.log
  alpha-build-machinery/make/examples/multiple-binaries/manifests/operator.openshift.io_myotheroperatorresources.crd.yaml
  alpha-build-machinery/make/examples/multiple-binaries/manifests/operator.openshift.io_myotheroperatorresources.crd.yaml-merge-patch
  alpha-build-machinery/make/examples/multiple-binaries/pkg/apis/v1beta1/types.go
  alpha-build-machinery/make/examples/multiple-binaries/testing/manifests/initial/operator.openshift.io_myotheroperatorresources.crd.yaml
  alpha-build-machinery/make/examples/multiple-binaries/testing/manifests/initial/operator.openshift.io_myotheroperatorresources.crd.yaml-merge-patch
  alpha-build-machinery/make/examples/multiple-binaries/testing/manifests/updated/operator.openshift.io_myotheroperatorresources.crd.yaml
  alpha-build-machinery/make/examples/multiple-binaries/testing/manifests/updated/operator.openshift.io_myotheroperatorresources.crd.yaml-merge-patch
  alpha-build-machinery/make/targets/openshift/crd-schema-gen.mk
Labels: approved, lgtm, size/L

#534 Bug 1754042: Detect more retriable errors from general registry clients
  pkg/image/registryclient/client.go
  pkg/image/registryclient/client_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#542 Ignore nested vendor/ folders in gofmt
  alpha-build-machinery/make/lib/golang.mk
Labels: approved, lgtm, size/XS

#544 Fix tests
  alpha-build-machinery/Makefile
  alpha-build-machinery/make/examples/multiple-binaries/Makefile.test
  alpha-build-machinery/make/examples/multiple-binaries/Makefile.test.log
Labels: approved, lgtm, size/S

#537 Generic crdgen
  alpha-build-machinery/make/examples/multiple-binaries/Makefile
  alpha-build-machinery/make/examples/multiple-binaries/Makefile.test
  alpha-build-machinery/make/examples/multiple-binaries/Makefile.test.log
  alpha-build-machinery/make/targets/openshift/crd-schema-gen.mk
Labels: approved, lgtm, size/L

#547 Ignore _output folders for gofmt
  alpha-build-machinery/make/lib/golang.mk
Labels: approved, lgtm, size/XS

#546 Emit event when certificate gets updated
  pkg/operator/staticpod/certsyncpod/certsync_controller.go
Labels: approved, lgtm, size/S

#551 Add pkg/crypto:MakeSelfSignedCAConfigForSubject
  pkg/crypto/crypto.go
Labels: approved, lgtm, size/S

#539 s/user self_dir/use self_dir/
  alpha-build-machinery/make/default.mk
  alpha-build-machinery/make/targets/golang/build.mk
  alpha-build-machinery/make/targets/golang/test-unit.mk
  alpha-build-machinery/make/targets/golang/verify-update.mk
  alpha-build-machinery/make/targets/openshift/controller-gen.mk
  alpha-build-machinery/make/targets/openshift/crd-schema-gen.mk
  alpha-build-machinery/make/targets/openshift/rpm.mk
  alpha-build-machinery/make/targets/openshift/yq.mk
Labels: approved, lgtm, size/S

#552 Explicitly disable go.mod for bindata generation
  alpha-build-machinery/make/targets/openshift/bindata.mk
Labels: approved, lgtm, size/XS

#550 installer: add controller that watch pending installer pods
  pkg/operator/staticpod/controller/installerstate/installer_state_controller.go
  pkg/operator/staticpod/controller/installerstate/installer_state_controller_test.go
  pkg/operator/staticpod/controllers.go
Labels: approved, lgtm, size/L

#549 Bug 1761280: don't log secret data
  pkg/operator/resource/resourceapply/core.go
  pkg/operator/resource/resourceapply/json_patch_helpers.go
  pkg/operator/staticpod/controller/revision/revision_controller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#561 Use pre-built version of controller-gen
  alpha-build-machinery/make/examples/multiple-binaries/Makefile
  alpha-build-machinery/make/examples/multiple-binaries/Makefile.test.log
  alpha-build-machinery/make/targets/openshift/controller-gen.mk
Labels: approved, lgtm, size/L

#564 Add e2e-encryption tests
  Makefile
  glide.lock
  test/e2e-encryption/encryption_test.go
  test/library/client.go
  test/library/library.go
  vendor/github.com/pmezard/go-difflib/.travis.yml
  vendor/github.com/pmezard/go-difflib/LICENSE
  vendor/github.com/pmezard/go-difflib/README.md
  vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  vendor/github.com/pmezard/go-difflib/difflib/difflib_test.go
  vendor/github.com/stretchr/testify/.gitignore
  vendor/github.com/stretchr/testify/.travis.gofmt.sh
  vendor/github.com/stretchr/testify/.travis.gogenerate.sh
  vendor/github.com/stretchr/testify/.travis.govet.sh
  vendor/github.com/stretchr/testify/.travis.yml
  vendor/github.com/stretchr/testify/Gopkg.lock
  vendor/github.com/stretchr/testify/Gopkg.toml
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/README.md
  vendor/github.com/stretchr/testify/_codegen/main.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/assertions_test.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/errors.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/forward_assertions_test.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions_test.go
  vendor/github.com/stretchr/testify/doc.go
  vendor/github.com/stretchr/testify/go.mod
  vendor/github.com/stretchr/testify/go.sum
  vendor/github.com/stretchr/testify/http/doc.go
  vendor/github.com/stretchr/testify/http/test_response_writer.go
  vendor/github.com/stretchr/testify/http/test_round_tripper.go
  vendor/github.com/stretchr/testify/mock/doc.go
  vendor/github.com/stretchr/testify/mock/mock.go
  vendor/github.com/stretchr/testify/mock/mock_test.go
  vendor/github.com/stretchr/testify/package_test.go
  vendor/github.com/stretchr/testify/require/doc.go
  vendor/github.com/stretchr/testify/require/forward_requirements.go
  vendor/github.com/stretchr/testify/require/forward_requirements_test.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/github.com/stretchr/testify/require/requirements_test.go
  vendor/github.com/stretchr/testify/suite/doc.go
  vendor/github.com/stretchr/testify/suite/interfaces.go
  vendor/github.com/stretchr/testify/suite/suite.go
  vendor/github.com/stretchr/testify/suite/suite_test.go
Labels: approved, lgtm, size/XXL

#565 encryption: expect pods for all nodes in staticpod operator status
  pkg/operator/encryption/controllers/key_controller_test.go
  pkg/operator/encryption/controllers/migration_controller_test.go
  pkg/operator/encryption/controllers/prune_controller_test.go
  pkg/operator/encryption/controllers/state_controller_test.go
  pkg/operator/encryption/deployer/staticpod.go
  pkg/operator/encryption/testing/helpers.go
  pkg/operator/v1helpers/test_helpers.go
Labels: approved, lgtm, size/L

#553 add tls1.3 cipher suites
  pkg/crypto/crypto.go
  pkg/crypto/crypto_test.go
Labels: approved, lgtm, size/M

#566 encryption: cleanup and fix static pod deployer nodeName logic
  pkg/operator/encryption/controllers/key_controller_test.go
  pkg/operator/encryption/controllers/migration_controller_test.go
  pkg/operator/encryption/controllers/prune_controller_test.go
  pkg/operator/encryption/controllers/state_controller_test.go
  pkg/operator/encryption/deployer/staticpod.go
  pkg/operator/encryption/testing/helpers.go
Labels: approved, lgtm, size/L

#567 operator: generalize revision controller to be independent of static pods
  pkg/operator/revisioncontroller/revision_controller.go
  pkg/operator/revisioncontroller/revision_controller_test.go
  pkg/operator/revisioncontroller/staticpod.go
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
  pkg/operator/staticpod/controller/revision/compatibility.go
  pkg/operator/staticpod/controllers.go
Labels: approved, lgtm, size/L

#568 encryption: split into RevisionLabelPodDeployer and StaticPodNodeProvider
  pkg/operator/encryption/controllers/key_controller_test.go
  pkg/operator/encryption/controllers/migration_controller_test.go
  pkg/operator/encryption/controllers/prune_controller_test.go
  pkg/operator/encryption/controllers/state_controller_test.go
  pkg/operator/encryption/deployer/revisionedpod.go
  pkg/operator/encryption/deployer/staticpod.go
Labels: approved, lgtm, size/L

#563 pkg/operator/status/condition: Handle Unknown in internalUnionCondition
  pkg/operator/status/condition.go
  pkg/operator/status/status_controller_test.go
Labels: approved, lgtm, size/M

#570 encryption: missing node pods => progressing
  pkg/operator/encryption/deployer/revisionedpod.go
Labels: approved, lgtm, size/XS

#571 encryption: fix var scope bug in categorizePods and add tests
  pkg/operator/encryption/deployer/revisionedpod.go
  pkg/operator/encryption/deployer/revisionedpod_test.go
Labels: approved, lgtm, size/L

#572 encryption: fix logf format in e2e
  test/e2e-encryption/encryption_test.go
Labels: approved, lgtm, size/XS

#573 moves e2e encryption code to library-go
  test/library/encryption/assertion.go
  test/library/encryption/e_log.go
  test/library/encryption/etcd_client.go
  test/library/encryption/helpers.go
Labels: approved, lgtm, size/XL

#574 cleans e2e encryption code
  test/library/encryption/assertion.go
  test/library/encryption/helpers.go
Labels: approved, lgtm, size/M
