Repository openshift/library-go, pull requests merged in 2019-02, with the labels that each got.

#216 add signer target for rotation
  pkg/operator/certrotation/target.go
Labels: approved, lgtm, size/M

#217 installer: add test to exercise revision skew
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
Labels: approved, lgtm, size/M

#218 Fix diffing symlinks for `make verify-deps`
  alpha-build-machinery/make/targets/openshift/deps.mk
Labels: approved, lgtm, size/XS

#219 Fix updating deps for mercurial
  alpha-build-machinery/scripts/update-deps.sh
Labels: approved, lgtm, size/XS

#221 Fix updating deps for mercurial
  alpha-build-machinery/make/targets/openshift/deps.mk
Labels: approved, lgtm, size/XS

#223 status: print exact message to logs when status not found
  pkg/operator/status/status_controller.go
Labels: approved, lgtm, size/XS

#220 assets: add creater based on dynamic client
  pkg/assets/create/OWNERS
  pkg/assets/create/create_test.go
  pkg/assets/create/creater.go
  pkg/assets/create/testdata/0000_10_kube-apiserver-operator_01_config.crd.yaml
  pkg/assets/create/testdata/00_openshift-kube-apiserver-ns.yaml
  pkg/assets/create/testdata/configmap-aggregator-client-ca.yaml
  pkg/assets/create/testdata/operator-config.yaml
  pkg/assets/create/testdata/secret-aggregator-client.yaml
Labels: approved, lgtm, size/XL

#224 make it possible for an installer pod to have extra args
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controllers.go
  pkg/operator/staticpod/installerpod/cmd.go
Labels: approved, lgtm, size/M

#222 installer: handle installer failures better
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
Labels: approved, lgtm, size/L

#226 pkg/assets/create: Allow mid-create cancels
  pkg/assets/create/create_test.go
  pkg/assets/create/creater.go
Labels: approved, lgtm, size/S

#227 installerpod: fix retry handling and report events
  pkg/operator/staticpod/controller/installer/bindata/bindata.go
  pkg/operator/staticpod/controller/installer/manifests/installer-pod.yaml
  pkg/operator/staticpod/installerpod/cmd.go
  pkg/operator/staticpod/installerpod/cmd_test.go
Labels: approved, lgtm, size/L

#229 set failing when static pods are not all healthy
  pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  pkg/operator/staticpod/controllers.go
Labels: approved, lgtm, size/L

#231 installerpod: remove namespace from the installer event
  pkg/operator/staticpod/installerpod/cmd.go
  pkg/operator/staticpod/installerpod/cmd_test.go
Labels: approved, lgtm, size/M

#232 operator: stop logging not found as errors
  pkg/operator/staticpod/controller/prune/prune_controller.go
  pkg/operator/status/status_controller.go
Labels: approved, lgtm, size/XS

#233 Prepare to use protobuf client-go
  pkg/config/client/client_config.go
  pkg/controller/controllercmd/builder.go
  pkg/operator/resource/resourceapply/generic.go
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
  pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  pkg/operator/staticpod/controllers.go
Labels: approved, lgtm, size/L

#235 fix version reporting in status controller
  pkg/operator/status/status_controller.go
  pkg/operator/status/status_controller_test.go
Labels: approved, lgtm, size/S

#236 config: fix panic in client_config
  pkg/config/client/client_config.go
Labels: approved, lgtm, size/S

#237 set content type to protobuf on client
  pkg/config/client/client_config.go
  pkg/controller/controllercmd/builder.go
Labels: approved, lgtm, size/XS

#234 operator: fix resourcesync controller client scope
  pkg/operator/resourcesynccontroller/resourcesync_controller.go
  pkg/operator/resourcesynccontroller/resourcesync_controller_test.go
  pkg/operator/v1helpers/core_getters.go
Labels: approved, lgtm, size/S

#230 Fix package name of clusteroperator v1helpers
  pkg/config/clusteroperator/v1helpers/status.go
  pkg/config/clusteroperator/v1helpers/status_test.go
Labels: approved, lgtm, size/XS

#238 add events for why a revision happens
  pkg/operator/staticpod/controller/revision/revision_controller.go
  pkg/operator/status/status_controller.go
Labels: approved, lgtm, size/XS

#239 don't prune when there are no IDs
  pkg/operator/staticpod/controller/prune/prune_controller.go
Labels: approved, lgtm, size/XS

#240 add reasons about why a cert was rotated
  pkg/operator/certrotation/client_cert_rotation_controller.go
  pkg/operator/certrotation/signer.go
  pkg/operator/certrotation/target.go
  pkg/operator/certrotation/target_test.go
Labels: approved, size/M

#241 fix annoying group typo
  pkg/operator/resource/resourceapply/event_helpers.go
Labels: approved, lgtm, size/XS

#242 use the resourceapply methods in the cert rotation
  pkg/operator/certrotation/cabundle.go
  pkg/operator/certrotation/cabundle_test.go
  pkg/operator/certrotation/signer.go
  pkg/operator/certrotation/signer_test.go
  pkg/operator/certrotation/target.go
  pkg/operator/certrotation/target_test.go
Labels: approved, lgtm, size/M

#243 retry config updates without failing
  pkg/operator/configobserver/config_observer_controller.go
  pkg/operator/configobserver/config_observer_controller_test.go
  pkg/operator/v1helpers/helpers.go
Labels: approved, lgtm, size/M

#244 resourceapply: log changes when objects are modified
  pkg/operator/resource/resourceapply/apiextensions.go
  pkg/operator/resource/resourceapply/apiregistration.go
  pkg/operator/resource/resourceapply/apps.go
  pkg/operator/resource/resourceapply/core.go
  pkg/operator/resource/resourceapply/core_test.go
  pkg/operator/resource/resourceapply/event_helpers.go
  pkg/operator/resource/resourceapply/generic_test.go
  pkg/operator/resource/resourceapply/json_patch_helpers.go
  pkg/operator/resource/resourceapply/json_patch_helpers_test.go
  pkg/operator/resource/resourceapply/monitoring.go
  pkg/operator/resource/resourceapply/rbac.go
  pkg/operator/resource/resourceapply/storage.go
  pkg/operator/staticpod/controller/revision/revision_controller_test.go
  pkg/operator/status/status_controller.go
Labels: approved, lgtm, size/L

#245 staticpodstate: do not blip on unready containers and check the termination exit code
  pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
Labels: approved, lgtm, size/S

#246 installer: prevent panics when new operator status is nil
  pkg/operator/v1helpers/helpers.go
Labels: approved, lgtm, size/XS

#247 add version setting to static pod management
  pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  pkg/operator/staticpod/controllers.go
  pkg/operator/status/version.go
Labels: approved, lgtm, size/M

#250 refactor static pod controller building
  pkg/operator/staticpod/controllers.go
Labels: approved, lgtm, size/L

#249 retrieval failures count against static pod state
  pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
Labels: approved, lgtm, size/XS

#251 get network CIDRs from config api
  pkg/operator/configobserver/network/observe_network.go
  pkg/operator/configobserver/network/observe_networking_test.go
Labels: approved, lgtm, size/L

#253 pull the version-mapping from the correct namespace
  pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  pkg/operator/staticpod/controllers.go
Labels: approved, lgtm, size/S

#257 if an operator is unmanaged, it should change status to unknown
  pkg/operator/status/status_controller.go
  pkg/operator/status/status_controller_test.go
Labels: approved, lgtm, size/S

#252 render: add special merge cases arg to GenericConfig.ApplyTo
  pkg/operator/render/options/generic.go
Labels: approved, lgtm, size/S

#256 include daemonset image pullspec in annotations to force rollout when it changes
  pkg/operator/resource/resourceapply/apps.go
Labels: approved, lgtm, size/XS

#258 simplify the clusteroperator status logic
  pkg/operator/status/condition.go
  pkg/operator/status/status_controller.go
  pkg/operator/status/status_controller_test.go
Labels: approved, lgtm, size/L

#262 crd-schema-gen: split code from main.go to make glide happy
  cmd/crd-schema-gen/generator/generator.go
  cmd/crd-schema-gen/main.go
Labels: approved, lgtm, size/XL

#263 crd-schema-gen: fix working dir after generator
  cmd/crd-schema-gen/generator/generator.go
Labels: approved, lgtm, size/XS

#265 remove rate limiting from config observation
  pkg/operator/configobserver/config_observer_controller.go
Labels: approved, lgtm, size/S

#261 operator: stop managing on unknown management state
  pkg/operator/resourcesynccontroller/resourcesync_controller.go
  pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
  pkg/operator/staticpod/controller/revision/revision_controller.go
  pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
Labels: approved, lgtm, size/M

#267 eliminate the race to read the serving certs in operator filepath change detection
  pkg/controller/controllercmd/builder.go
  pkg/controller/controllercmd/cmd.go
  pkg/controller/controllercmd/flags.go
  pkg/controller/fileobserver/observer.go
  pkg/controller/fileobserver/observer_polling.go
  pkg/controller/fileobserver/observer_polling_test.go
  pkg/crypto/crypto.go
Labels: approved, do-not-merge/hold, lgtm, size/L

#268 assets: add more sense to creater verbose messages
  pkg/assets/create/create_test.go
  pkg/assets/create/creater.go
Labels: approved, lgtm, size/S

#269 fix pull policy for installer and pruner
  pkg/operator/render/options/manifest.go
  pkg/operator/staticpod/controller/installer/bindata/bindata.go
  pkg/operator/staticpod/controller/installer/manifests/installer-pod.yaml
  pkg/operator/staticpod/controller/prune/bindata/bindata.go
  pkg/operator/staticpod/controller/prune/manifests/pruner-pod.yaml
Labels: approved, lgtm, size/S

#259 get network CIDRs from config api
  pkg/operator/configobserver/network/observe_network.go
  pkg/operator/configobserver/network/observe_networking_test.go
Labels: approved, lgtm, size/L

#266 make functions for easy adoption of rendered certificates
  pkg/assets/template.go
  pkg/operator/certrotation/client_cert_rotation_controller.go
  pkg/operator/certrotation/signer.go
  pkg/operator/certrotation/signer_test.go
  pkg/operator/certrotation/target.go
  pkg/operator/certrotation/target_test.go
Labels: approved, lgtm, size/M

#271 tolerate empty certificates
  pkg/assets/template.go
Labels: approved, lgtm, size/XS

#272 resource: enforce apiGroup to role binding as well
  pkg/operator/resource/resourceapply/rbac.go
Labels: approved, lgtm, size/XS

#273 Installer pod fixes
  pkg/operator/staticpod/installerpod/cmd.go
Labels: approved, lgtm, size/S

#270 allow hostnames to be specified and changed after initial creation
  pkg/operator/certrotation/client_cert_rotation_controller.go
  pkg/operator/certrotation/target.go
  pkg/operator/certrotation/target_test.go
Labels: approved, lgtm, size/L

#274 express rotation times in terms of durations
  pkg/operator/certrotation/client_cert_rotation_controller.go
  pkg/operator/certrotation/client_cert_rotation_controller_test.go
  pkg/operator/certrotation/signer.go
  pkg/operator/certrotation/signer_test.go
  pkg/operator/certrotation/target.go
  pkg/operator/certrotation/target_test.go
Labels: approved, lgtm, size/L

#277 resource: fix apiGroup defaulting for rolebindings
  pkg/operator/resource/resourceapply/rbac.go
Labels: approved, lgtm, size/M

#278 Use quorum-read from server for revision controller
  pkg/operator/staticpod/controller/revision/revision_controller.go
  pkg/operator/v1helpers/interfaces.go
  pkg/operator/v1helpers/test_helpers.go
Labels: approved, lgtm, size/S

#279 add controller for setting upgradeable conditions to false if unsupprtedConfigOverrides is set
  pkg/operator/staticpod/controllers.go
  pkg/operator/unsupportedconfigoverridescontroller/unsupportedconfigoverrides_controller.go
  pkg/operator/unsupportedconfigoverridescontroller/unsupportedconfigoverrides_controller_test.go
Labels: approved, lgtm, size/L

#280 start upgradable controller for static pods
  pkg/operator/staticpod/controllers.go
Labels: approved, lgtm, size/XS

#282 resourceapply: enforce apiGroup for rolebinding subjects
  pkg/operator/resource/resourceapply/rbac.go
Labels: approved, lgtm, size/S

#281 installerpod: retry on apiserver shutdown error
  pkg/operator/staticpod/installerpod/cmd.go
Labels: approved, lgtm, size/XS

#284 make no matching conditions result in unknown, not success
  pkg/operator/status/condition.go
  pkg/operator/status/status_controller.go
  pkg/operator/status/status_controller_test.go
Labels: approved, lgtm, size/L

#286 staticpod: simplify retry mechanism
  pkg/operator/staticpod/installerpod/cmd.go
  pkg/operator/staticpod/installerpod/copy.go
  pkg/operator/staticpod/installerpod/copy_test.go
Labels: approved, lgtm, size/L

#287 staticpod: retry on connection errors for optional secrets
  pkg/operator/staticpod/installerpod/copy.go
  pkg/operator/staticpod/installerpod/copy_test.go
Labels: approved, lgtm, size/M

#290 wire updated retry on connection logic to installer pod
  pkg/operator/resource/retry/retry.go
  pkg/operator/resource/retry/retry_test.go
  pkg/operator/resource/retry/wait.go
  pkg/operator/staticpod/installerpod/cmd.go
  pkg/operator/staticpod/installerpod/copy.go
  pkg/operator/staticpod/installerpod/copy_test.go
Labels: approved, lgtm, size/L
