Repository openshift/library-go, pull requests merged in 2019-03, with the labels that each got.

#293 revision-controller: log possible LatestAvailableRevision race
  pkg/operator/staticpod/controller/revision/revision_controller.go
Labels: approved, lgtm, size/XS

#292 revision: log all changes for the latest revision
  pkg/operator/staticpod/controller/revision/revision_controller.go
Labels: approved, lgtm, size/S

#291 Compare LastFailed and Current revisions for pruner pod
  pkg/operator/staticpod/controller/prune/prune_controller.go
  pkg/operator/staticpod/controller/prune/prune_controller_test.go
  pkg/operator/staticpod/prune/cmd.go
  pkg/operator/staticpod/prune/cmd_test.go
Labels: approved, lgtm, size/L

#298 add ability to separately copy certs
  pkg/operator/staticpod/certsyncpod/certsync_cmd.go
  pkg/operator/staticpod/certsyncpod/certsync_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controllers.go
  pkg/operator/staticpod/installerpod/cmd.go
Labels: approved, lgtm, size/L

#297 operator: ignore Unmanaged state in control plane operators
  pkg/operator/management/management_state.go
  pkg/operator/management/management_state_controller.go
  pkg/operator/management/management_state_controller_test.go
  pkg/operator/resourcesynccontroller/resourcesync_controller.go
  pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
  pkg/operator/staticpod/controller/revision/revision_controller.go
  pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  pkg/operator/status/status_controller.go
  pkg/operator/status/status_controller_test.go
  pkg/operator/unsupportedconfigoverridescontroller/unsupportedconfigoverrides_controller.go
Labels: approved, lgtm, size/L

#299 crd-schema-gen: allow a *-yaml-merge-patch file to post-kubebuilder-gen patch validation schemata
  cmd/crd-schema-gen/generator/generator.go
Labels: approved, lgtm, size/M

#300 crd-schema-gen: some output fixes
  cmd/crd-schema-gen/generator/generator.go
Labels: approved, lgtm, size/S

#301 events: allow to set component per controller
  pkg/operator/events/eventstesting/recorder_testing.go
  pkg/operator/events/recorder.go
  pkg/operator/events/recorder_in_memory.go
  pkg/operator/events/recorder_logging.go
  pkg/operator/events/recorder_upstream.go
  pkg/operator/staticpod/controllers.go
Labels: approved, lgtm, size/M

#302 events: wire component name for each controller
  pkg/operator/configobserver/config_observer_controller.go
  pkg/operator/events/eventstesting/recorder_testing.go
  pkg/operator/events/recorder.go
  pkg/operator/events/recorder_in_memory.go
  pkg/operator/events/recorder_logging.go
  pkg/operator/events/recorder_upstream.go
  pkg/operator/resourcesynccontroller/resourcesync_controller.go
  pkg/operator/staticpod/certsyncpod/certsync_controller.go
  pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
  pkg/operator/staticpod/controller/node/node_controller.go
  pkg/operator/staticpod/controller/prune/prune_controller.go
  pkg/operator/staticpod/controller/revision/revision_controller.go
  pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  pkg/operator/status/status_controller.go
  pkg/operator/unsupportedconfigoverridescontroller/unsupportedconfigoverrides_controller.go
Labels: approved, lgtm, size/M

#304 react to clusteroperator updates
  pkg/operator/status/status_controller.go
  pkg/operator/status/status_controller_test.go
Labels: approved, lgtm, size/S

#303 don't create pruner pod with revision 0
  pkg/operator/staticpod/controller/prune/prune_controller.go
  pkg/operator/staticpod/controller/prune/prune_controller_test.go
Labels: approved, lgtm, size/S

#307 Use CRD kind and group as the key
  cmd/crd-schema-gen/generator/generator.go
Labels: approved, lgtm, size/S

#305 Leader election: increase LeaseDuration,RenewDeadline,RetryPeriod
  pkg/config/leaderelection/leaderelection.go
Labels: approved, lgtm, size/XS

#306 staticpodstate: do not report failing when containers are initializing
  pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
Labels: approved, lgtm, size/XS

#311 certsyncpod: add reloader and fix starting informers
  pkg/operator/staticpod/certsyncpod/certsync_cmd.go
Labels: approved, lgtm, size/M

#314 staticpodstate: fix wrong field name
  pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
Labels: approved, lgtm, size/XS

#315 certs: add helpers to unify cert format
  pkg/certs/util.go
  pkg/certs/util_test.go
  pkg/operator/certrotation/cabundle.go
  pkg/operator/certrotation/target.go
Labels: approved, lgtm, size/L

#316 configobserver: prevent escaping bomb in condition message
  pkg/operator/configobserver/config_observer_controller.go
  pkg/operator/status/condition.go
Labels: approved, lgtm, size/S

#317 Correctly run UnsupportedConfigOverridesController when Managed
  pkg/operator/unsupportedconfigoverridescontroller/unsupportedconfigoverrides_controller.go
Labels: approved, lgtm, size/XS

#320 Implicitly hook {verify,update}-generated into {verify,update}
  alpha-build-machinery/make/targets/openshift/bindata.mk
  alpha-build-machinery/make/targets/openshift/codegen.mk
Labels: approved, lgtm, size/S

#318 Concat condition reason to it's type on condition union
  pkg/operator/status/condition.go
Labels: approved, lgtm, size/XS

#309 web profiler should take implicit dependency on net/http/pprof
  pkg/serviceability/profiler.go
Labels: approved, lgtm, size/XS

#312 installer: do no report errors for nodes that are not failing
  pkg/operator/staticpod/controller/installer/installer_controller.go
Labels: approved, lgtm, size/XS

#321 Add ResourceSync controller debug endpoint
  pkg/controller/controllercmd/builder.go
  pkg/operator/resourcesynccontroller/interfaces.go
  pkg/operator/resourcesynccontroller/resourcesync_controller.go
  pkg/operator/resourcesynccontroller/resourcesync_controller_test.go
Labels: approved, lgtm, size/L

#322 Get unnsuported cert rotation config reading
  pkg/operator/certrotation/config.go
Labels: approved, lgtm, size/M
