Repository openshift/library-go, pull requests merged in 2019-08, with the labels that each got.

#496 Make image building to be more configurable and confirm to 4.x naming conventions
  alpha-build-machinery/make/default.example.mk
  alpha-build-machinery/make/default.example.mk.help.log
  alpha-build-machinery/make/operator.example.mk
  alpha-build-machinery/make/operator.example.mk.help.log
  alpha-build-machinery/make/targets/openshift/images.mk
Labels: approved, lgtm, size/M

#497 operator/staticpod: properly format error message
  pkg/operator/staticpod/controller/installer/installer_controller.go
Labels: approved, lgtm, size/XS

#499 observe proxy: don't change target in noconfig -> noconfig case
  pkg/operator/configobserver/proxy/observe_proxy.go
  pkg/operator/configobserver/proxy/observe_proxy_test.go
Labels: approved, lgtm, size/S

#500 Generate cloud config for openstack cloud provider
  pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
Labels: approved, lgtm, size/XS

#501 Update observe proxy to use Status NoProxy
  pkg/operator/configobserver/proxy/observe_proxy.go
  pkg/operator/configobserver/proxy/observe_proxy_test.go
Labels: approved, lgtm, size/S

#503 Actually watch Proxy status
  pkg/operator/configobserver/proxy/observe_proxy.go
  pkg/operator/configobserver/proxy/observe_proxy_test.go
Labels: approved, lgtm, size/XS

#504 pkg/operator/staticpod/prune: return proper flag in error
  pkg/operator/staticpod/prune/cmd.go
Labels: approved, lgtm, size/XS

#505 Bug 1738432: genericoperatorclient: only preserve fields outside of Operator{Spec,Status}
  pkg/operator/genericoperatorclient/dynamic_operator_client.go
  pkg/operator/genericoperatorclient/dynamic_operator_client_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#508 watchdog: add --ready-file support
  pkg/oauth/oauthserviceaccountclient/oauthclientregistry_test.go
  pkg/operator/watchdog/cmd.go
Labels: approved, lgtm, size/S

#511 add dependency magnet files for go mod and build-machinery
  alpha-build-machinery/doc.go
  alpha-build-machinery/make/doc.go
  alpha-build-machinery/make/lib/doc.go
  alpha-build-machinery/make/targets/doc.go
  alpha-build-machinery/make/targets/golang/doc.go
  alpha-build-machinery/make/targets/openshift/doc.go
  alpha-build-machinery/make/targets/openshift/operator/doc.go
  alpha-build-machinery/scripts/doc.go
Labels: approved, lgtm, size/M

#510 watchdog: add --pid-file
  pkg/operator/watchdog/cmd.go
  pkg/operator/watchdog/cmd_test.go
Labels: approved, lgtm, size/M

#514 build-machinery: Fix and simplify GO_PACKAGE detection
  alpha-build-machinery/make/lib/golang.mk
Labels: approved, lgtm, size/XS

#515 controllercmd: add --terminate-on-files file observer
  pkg/controller/controllercmd/cmd.go
  pkg/controller/controllercmd/flags.go
Labels: approved, lgtm, size/S

#516 fileobserver: deprecate ExitOnChangeReactor in favor of TerminateOnChangeReactor
  pkg/controller/fileobserver/observer.go
  pkg/controller/fileobserver/observer_polling.go
  pkg/operator/staticpod/certsyncpod/certsync_cmd.go
Labels: approved, lgtm, size/M

#518 installer: fix pending revision error message to include target revision
  pkg/operator/staticpod/controller/installer/installer_controller.go
Labels: approved, lgtm, size/XS
