Repository openshift/library-go, pull requests merged in 2019-04, with the labels that each got.

#324 resourcesynccontroller: use cached get to confirm resource exists before deleting target
  pkg/operator/resourcesynccontroller/resourcesync_controller.go
Labels: approved, lgtm, size/XS

#326 staticpod: set operand version using environment variable
  pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  pkg/operator/status/version.go
Labels: approved, lgtm, size/S

#319 ClusterOperatorStatusController: Wait for cache sync
  pkg/operator/status/status_controller.go
Labels: approved, lgtm, size/XS

#329 Revert "resourcesynccontroller: use cached get to confirm resource ex…
  pkg/operator/resourcesynccontroller/resourcesync_controller.go
Labels: approved, lgtm, size/XS

#330 ClusterOperatorStatusController: Add WaitForCacheSync
  pkg/operator/status/status_controller.go
Labels: approved, lgtm, size/S

#337 add generic feature gate observer
  pkg/operator/configobserver/featuregates/observe_featuregates.go
  pkg/operator/configobserver/featuregates/observe_featuregates_test.go
Labels: approved, lgtm, size/L

#331 Allow controllercmd to reuse default config and rotation logic
  pkg/controller/controllercmd/cmd.go
Labels: approved, lgtm, size/M

#335 events: fallback to use namespace as controller if we are not able to get pod
  pkg/controller/controllercmd/builder.go
  pkg/operator/events/recorder.go
  pkg/operator/events/recorder_test.go
  pkg/operator/staticpod/installerpod/cmd.go
Labels: approved, lgtm, size/M

#340 wrap the existing wrap transport to handle 1.13
  pkg/config/client/client_config.go
  pkg/config/helpers/client.go
Labels: approved, lgtm, size/M

#323 Add prometheus metrics for rotated certificates
  pkg/operator/certrotation/cabundle.go
  pkg/operator/certrotation/client_cert_rotation_controller.go
  pkg/operator/certrotation/metrics/monitor.go
  pkg/operator/certrotation/metrics/util.go
  pkg/operator/certrotation/signer.go
  pkg/operator/certrotation/target.go
Labels: approved, lgtm, size/L

#342 crd-schema-gen: create PROJECT file to cope with latest controller-tools
  cmd/crd-schema-gen/generator/generator.go
Labels: approved, lgtm, size/XS

#343 crd-schema-gen: add --domain and (optional) --repo
  cmd/crd-schema-gen/generator/generator.go
Labels: approved, lgtm, size/M

#344 certrotation: fix metrics collector
  pkg/operator/certrotation/client_cert_rotation_controller.go
  pkg/operator/certrotation/metrics/monitor.go
Labels: approved, lgtm, size/S

#346 Revert metrics
  pkg/operator/certrotation/cabundle.go
  pkg/operator/certrotation/client_cert_rotation_controller.go
  pkg/operator/certrotation/metrics/monitor.go
  pkg/operator/certrotation/metrics/util.go
  pkg/operator/certrotation/signer.go
  pkg/operator/certrotation/target.go
Labels: approved, lgtm

#338 don't report bad transition unless over 1 minute ago
  pkg/operator/status/condition.go
  pkg/operator/status/status_controller.go
  pkg/operator/status/status_controller_test.go
Labels: approved, lgtm, size/L

#341 Add a common cloudprovider observer
  pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
  pkg/operator/configobserver/cloudprovider/observe_cloudprovider_test.go
Labels: approved, lgtm

#339 Switch openshift/library-go to go1.11
  pkg/crypto/crypto.go
  pkg/crypto/rotation_test.go
  pkg/operator/certrotation/cabundle_test.go
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
Labels: approved, lgtm, size/M

#351 certrotation: label managed certificates
  pkg/operator/certrotation/cabundle.go
  pkg/operator/certrotation/cabundle_test.go
  pkg/operator/certrotation/label.go
  pkg/operator/certrotation/signer.go
  pkg/operator/certrotation/signer_test.go
  pkg/operator/certrotation/target.go
  pkg/operator/certrotation/target_test.go
Labels: approved, lgtm, size/M

#356 Set an arbitrary event namespace when not running inside a cluster
  pkg/controller/controllercmd/builder.go
Labels: approved, lgtm, size/S

#354 Change ClusterOperatorStatus Failed to Degraded
  glide.lock
  glide.yaml
  pkg/operator/status/status_controller.go
  pkg/operator/status/status_controller_test.go
  vendor/github.com/gobuffalo/envy/SHOULDERS.md
  vendor/github.com/gobuffalo/envy/envy.go
  vendor/github.com/gobuffalo/envy/envy_test.go
  vendor/github.com/gobuffalo/envy/version.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/gopkg.in/yaml.v2/decode_test.go
  vendor/gopkg.in/yaml.v2/encode.go
  vendor/gopkg.in/yaml.v2/encode_test.go
  vendor/k8s.io/apiextensions-apiserver/Godeps/Godeps.json
  vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/validation/validation.go
  vendor/k8s.io/apiextensions-apiserver/pkg/controller/openapi/aggregator.go
  vendor/k8s.io/apiextensions-apiserver/pkg/controller/openapi/builder.go
  vendor/k8s.io/apiextensions-apiserver/pkg/controller/openapi/builder_test.go
  vendor/k8s.io/apiextensions-apiserver/pkg/controller/openapi/controller.go
  vendor/k8s.io/apiextensions-apiserver/pkg/controller/openapi/conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/controller/openapi/conversion_test.go
  vendor/k8s.io/apiextensions-apiserver/pkg/features/kube_features.go
  vendor/k8s.io/apiextensions-apiserver/pkg/generated/openapi/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/generated/openapi/zz_generated.openapi.go
Labels: approved, kind/api-change, lgtm, size/XXL

#357 resourcesynccontroller: use cached get to confirm resource exists before deleting target
  pkg/operator/resource/resourceapply/core.go
  pkg/operator/resourcesynccontroller/resourcesync_controller.go
  pkg/operator/resourcesynccontroller/resourcesync_controller_test.go
Labels: approved, lgtm, size/L

#358 update all control loops for degraded
  pkg/operator/certrotation/client_cert_rotation_controller.go
  pkg/operator/configobserver/config_observer_controller.go
  pkg/operator/configobserver/config_observer_controller_test.go
  pkg/operator/management/management_state_controller.go
  pkg/operator/management/management_state_controller_test.go
  pkg/operator/resourcesynccontroller/resourcesync_controller.go
  pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
  pkg/operator/staticpod/controller/backingresource/backing_resource_controller_test.go
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
  pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
  pkg/operator/staticpod/controller/revision/revision_controller.go
  pkg/operator/staticpod/controller/revision/revision_controller_test.go
  pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
Labels: approved, lgtm, size/M

#359 loglevel: fix reporting via events
  pkg/operator/loglevel/logging_controller.go
Labels: approved, lgtm, size/S

#360 wait for caches to synchronize before working
  pkg/operator/certrotation/client_cert_rotation_controller.go
  pkg/operator/configobserver/config_observer_controller.go
  pkg/operator/configobserver/config_observer_controller_test.go
  pkg/operator/loglevel/logging_controller.go
  pkg/operator/management/management_state_controller.go
  pkg/operator/resourcesynccontroller/resourcesync_controller.go
  pkg/operator/resourcesynccontroller/resourcesync_controller_test.go
  pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
  pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
  pkg/operator/staticpod/controller/node/node_controller.go
  pkg/operator/staticpod/controller/prune/prune_controller.go
  pkg/operator/staticpod/controller/prune/prune_controller_test.go
  pkg/operator/staticpod/controller/revision/revision_controller.go
  pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  pkg/operator/status/status_controller.go
  pkg/operator/unsupportedconfigoverridescontroller/unsupportedconfigoverrides_controller.go
Labels: approved, lgtm, size/L

#361 tighten leader election defaults
  pkg/config/leaderelection/leaderelection.go
Labels: approved, lgtm, size/XS

#362 add path, type, name, and namespace information to creation message
  pkg/assets/create/create_test.go
  pkg/assets/create/creater.go
Labels: approved, lgtm, size/S

#355 Add UpdateStaticPodOperatorSpec function
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
  pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller_test.go
  pkg/operator/staticpod/controller/node/node_controller_test.go
  pkg/operator/staticpod/controller/prune/prune_controller_test.go
  pkg/operator/staticpod/controller/revision/revision_controller_test.go
  pkg/operator/v1helpers/interfaces.go
  pkg/operator/v1helpers/test_helpers.go
Labels: approved, lgtm, size/M

#364 controller: retry connection errors when getting extension-apiserver-authentication
  pkg/config/serving/server.go
  pkg/controller/controllercmd/builder.go
Labels: approved, lgtm, size/M

#365 wait for certs to be present before installing
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
  pkg/operator/staticpod/controllers.go
Labels: approved, lgtm, size/L

#353 domain is not optional, repo is optional
  cmd/crd-schema-gen/generator/generator.go
Labels: approved, lgtm, size/XS

#366 stop flapping status on revision updates
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/installer/int32.go
Labels: approved, lgtm, size/L

#367 emit specific events for version changes
  pkg/operator/status/status_controller.go
  pkg/operator/v1helpers/helpers.go
Labels: approved, lgtm, size/S

#363 Remove EnsureOperatorConfigExists helper
  pkg/operator/v1helpers/helpers.go
Labels: approved, lgtm, size/M

#369 fix the failing revision counts
  pkg/operator/staticpod/controller/installer/installer_controller.go
Labels: approved, lgtm, size/S

#370 loglevel: rework setting the log level using flags
  pkg/operator/events/recorder_in_memory.go
  pkg/operator/loglevel/logging_controller.go
  pkg/operator/loglevel/logging_controller_test.go
  pkg/operator/loglevel/util.go
Labels: approved, lgtm, size/L

#371 installer: fire event on missing required certs
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
Labels: approved, lgtm, size/S

#368 Revision recovery from operator object deletion
  pkg/operator/staticpod/controller/revision/revision_controller.go
  pkg/operator/staticpod/controller/revision/revision_controller_test.go
Labels: approved, lgtm, size/M

#372 always retry failed installer pods
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
Labels: approved, lgtm, size/M

#373 set operator version to match other operators
  pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  pkg/operator/status/version.go
Labels: approved, lgtm, size/S

#375 logging: fix case when logging is set to empty string
  pkg/operator/loglevel/logging_controller.go
  pkg/operator/loglevel/logging_controller_test.go
Labels: approved, lgtm, size/S

#374 monitoring: make service monitor CRD unavailability produce less noise
  pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
Labels: approved, lgtm, size/S

#376 installer: ensure the etcd-client secret is available
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
Labels: approved, lgtm, size/L

#378 send events for apiservice
  pkg/operator/resource/resourceapply/apiregistration.go
Labels: approved, lgtm, size/XS
