Repository openshift/library-go, pull requests merged in 2019-09, with the labels that each got.

#512 Bug 1714158: Prevent cert-syncer to act on stale data
  pkg/operator/staticpod/certsyncpod/certsync_cmd.go
  pkg/operator/staticpod/certsyncpod/certsync_controller.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#520 Bug 1748280: resourceapply: sync ConfigMap binaryData as well
  pkg/operator/resource/resourceapply/core.go
  pkg/operator/resource/resourceapply/core_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#524 cmd: run terminate-on-files observer
  pkg/controller/controllercmd/cmd.go
Labels: approved, lgtm, size/M

#525 fileobserver: do not hash empty string
  pkg/controller/controllercmd/cmd.go
  pkg/controller/fileobserver/observer_polling.go
  pkg/controller/fileobserver/observer_polling_test.go
Labels: approved, lgtm, size/S

#526 Add codegen-crds targets
  alpha-build-machinery/Makefile
  alpha-build-machinery/make/examples/multiple-binaries/Makefile
  alpha-build-machinery/make/examples/multiple-binaries/Makefile.test
  alpha-build-machinery/make/examples/multiple-binaries/Makefile.test.log
  alpha-build-machinery/make/examples/multiple-binaries/manifests/operator.openshift.io_myoperatorresources.crd.yaml
  alpha-build-machinery/make/examples/multiple-binaries/manifests/operator.openshift.io_myoperatorresources.crd.yaml-merge-patch
  alpha-build-machinery/make/examples/multiple-binaries/manifests/operator.openshift.io_myotheroperatorresources.crd.yaml
  alpha-build-machinery/make/examples/multiple-binaries/pkg/apis/v1/doc.go
  alpha-build-machinery/make/examples/multiple-binaries/pkg/apis/v1/register.go
  alpha-build-machinery/make/examples/multiple-binaries/pkg/apis/v1/types.go
  alpha-build-machinery/make/examples/multiple-binaries/pkg/apis/v1beta1/doc.go
  alpha-build-machinery/make/examples/multiple-binaries/pkg/apis/v1beta1/register.go
  alpha-build-machinery/make/examples/multiple-binaries/pkg/apis/v1beta1/types.go
  alpha-build-machinery/make/examples/multiple-binaries/testing/manifests/initial/operator.openshift.io_myoperatorresources.crd.yaml
  alpha-build-machinery/make/examples/multiple-binaries/testing/manifests/initial/operator.openshift.io_myoperatorresources.crd.yaml-merge-patch
  alpha-build-machinery/make/examples/multiple-binaries/testing/manifests/initial/operator.openshift.io_myotheroperatorresources.crd.yaml
  alpha-build-machinery/make/examples/multiple-binaries/testing/manifests/updated/operator.openshift.io_myoperatorresources.crd.yaml
  alpha-build-machinery/make/examples/multiple-binaries/testing/manifests/updated/operator.openshift.io_myoperatorresources.crd.yaml-merge-patch
  alpha-build-machinery/make/examples/multiple-binaries/testing/manifests/updated/operator.openshift.io_myotheroperatorresources.crd.yaml
  alpha-build-machinery/make/lib/tmp.mk
  alpha-build-machinery/make/targets/golang/build.mk
  alpha-build-machinery/make/targets/openshift/controller-gen.mk
  alpha-build-machinery/make/targets/openshift/crd-schema-gen.mk
  alpha-build-machinery/make/targets/openshift/yq.mk
Labels: approved, do-not-merge/hold, lgtm, size/XL

#527 Fix up crd-schema-gen verify
  alpha-build-machinery/make/examples/multiple-binaries/Makefile.test.log
  alpha-build-machinery/make/targets/openshift/crd-schema-gen.mk
Labels: approved, lgtm, size/S

#531 update dependencies
  glide.lock
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/S

#533 Update dependencies
  glide.lock
  vendor/github.com/opencontainers/runc/libcontainer/configs/config.go
  vendor/github.com/opencontainers/runc/libcontainer/container_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/rootfs_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/rootfs_linux_test.go
  vendor/github.com/opencontainers/runc/libcontainer/seccomp/config.go
  vendor/github.com/opencontainers/runc/libcontainer/seccomp/seccomp_linux.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/M

#532 Fix small bug in crd-schema-gen target that would fail on nil value
  alpha-build-machinery/make/targets/openshift/crd-schema-gen.mk
Labels: approved, lgtm, size/XS
