Repository openshift/library-go, pull requests merged in 2019-01, with the labels that each got.

#154 check for incompatible version of mergo
  glide.yaml
  pkg/operator/configobserver/config_observer_controller_test.go
Labels: approved, lgtm, size/S

#150 staticpod: add monitoring resources controller
  Makefile
  pkg/operator/resource/resourceapply/monitoring.go
  pkg/operator/resource/resourceapply/monitoring_test.go
  pkg/operator/staticpod/controller/monitoring/bindata/bindata.go
  pkg/operator/staticpod/controller/monitoring/manifests/prometheus-role-binding.yaml
  pkg/operator/staticpod/controller/monitoring/manifests/prometheus-role.yaml
  pkg/operator/staticpod/controller/monitoring/manifests/service-monitor.yaml
  pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
  pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller_test.go
  pkg/operator/staticpod/controllers.go
Labels: approved, lgtm, size/XL

#156 fix secret types for certs
  pkg/operator/certrotation/signer.go
  pkg/operator/certrotation/target.go
Labels: approved, lgtm, size/XS

#158 segregate and simplify the cert rotation config
  pkg/operator/certrotation/cabundle.go
  pkg/operator/certrotation/cabundle_test.go
  pkg/operator/certrotation/client_cert_rotation_controller.go
  pkg/operator/certrotation/signer.go
  pkg/operator/certrotation/signer_test.go
  pkg/operator/certrotation/target.go
  pkg/operator/certrotation/target_test.go
Labels: approved, lgtm, size/L

#160 events: provide more details when operator status change
  pkg/config/clusteroperator/v1helpers/status.go
  pkg/config/clusteroperator/v1helpers/status_test.go
  pkg/operator/status/status_controller.go
Labels: approved, lgtm, size/L

#161 create a generic resource sync control loop
  pkg/operator/resourcesynccontroller/interfaces.go
  pkg/operator/resourcesynccontroller/resourcesync_controller.go
  pkg/operator/resourcesynccontroller/resourcesync_controller_test.go
Labels: approved, lgtm, size/L

#164 config-helper: /foo/- relative to /foo is ./-
  pkg/config/helpers/general.go
  pkg/config/helpers/general_test.go
Labels: approved, lgtm, size/XS

#165 installer: QoS class guaranteed with 100MB
  pkg/operator/staticpod/controller/installer/bindata/bindata.go
  pkg/operator/staticpod/controller/installer/manifests/installer-pod.yaml
  pkg/operator/v1alpha1staticpod/controller/backingresource/backing_resource_controller.go
  pkg/operator/v1alpha1staticpod/controller/backingresource/backing_resource_controller_test.go
  pkg/operator/v1alpha1staticpod/controller/backingresource/bindata/bindata.go
  pkg/operator/v1alpha1staticpod/controller/backingresource/manifests/installer-cluster-rolebinding.yaml
  pkg/operator/v1alpha1staticpod/controller/backingresource/manifests/installer-sa.yaml
  pkg/operator/v1alpha1staticpod/controller/common/interfaces.go
  pkg/operator/v1alpha1staticpod/controller/common/test_utils.go
  pkg/operator/v1alpha1staticpod/controller/deployment/deployment_controller.go
  pkg/operator/v1alpha1staticpod/controller/deployment/deployment_controller_test.go
  pkg/operator/v1alpha1staticpod/controller/installer/installer_controller.go
  pkg/operator/v1alpha1staticpod/controller/installer/installer_controller_test.go
  pkg/operator/v1alpha1staticpod/controller/node/node_controller.go
  pkg/operator/v1alpha1staticpod/controller/node/node_controller_test.go
  pkg/operator/v1alpha1staticpod/controllers.go
  pkg/operator/v1alpha1staticpod/installerpod/cmd.go
  pkg/operator/v1alpha1staticpod/installerpod/cmd_test.go
Labels: approved, lgtm, size/XXL

#167 protect unknown status revisions
  pkg/operator/staticpod/controller/prune/prune_controller.go
  pkg/operator/staticpod/controller/prune/prune_controller_test.go
Labels: approved, lgtm, size/L

#157 Set revision status ownerrefs when creating new revision
  pkg/operator/resource/resourceapply/core.go
  pkg/operator/resourcesynccontroller/resourcesync_controller.go
  pkg/operator/staticpod/controller/revision/deployment_controller.go
  pkg/operator/staticpod/controller/revision/deployment_controller_test.go
Labels: approved, lgtm, size/M

#169 detect non-deterministic config observation
  pkg/operator/configobserver/config_observer_controller.go
  pkg/operator/configobserver/config_observer_controller_test.go
Labels: approved, lgtm, size/M

#168 fix panic in service monitor sync
  pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
Labels: approved, lgtm, size/S

#171 cert-rotation: add go doc
  pkg/operator/certrotation/cabundle.go
  pkg/operator/certrotation/client_cert_rotation_controller.go
  pkg/operator/certrotation/signer.go
  pkg/operator/certrotation/target.go
Labels: approved, lgtm, size/S

#173 add better event information and glog info on diff
  pkg/config/clusteroperator/v1helpers/status.go
  pkg/config/clusteroperator/v1helpers/status_test.go
  pkg/operator/status/status_controller.go
Labels: approved, lgtm, size/M

#170 API resource pruning in pruner control loop
  pkg/operator/staticpod/controller/prune/prune_controller.go
  pkg/operator/staticpod/controller/prune/prune_controller_test.go
  pkg/operator/staticpod/controller/revision/deployment_controller_test.go
Labels: approved, lgtm, size/L

#180 Return current service in ApplyService
  pkg/operator/resource/resourceapply/core.go
Labels: approved, lgtm, size/XS

#181 collapse into consistent operator client interfaces
  pkg/operator/configobserver/config_observer_controller.go
  pkg/operator/configobserver/config_observer_controller_test.go
  pkg/operator/resource/resourcemerge/apps.go
  pkg/operator/resourcesynccontroller/resourcesync_controller.go
  pkg/operator/resourcesynccontroller/resourcesync_controller_test.go
  pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
  pkg/operator/staticpod/controller/backingresource/backing_resource_controller_test.go
  pkg/operator/staticpod/controller/common/helpers.go
  pkg/operator/staticpod/controller/common/interfaces.go
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
  pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
  pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller_test.go
  pkg/operator/staticpod/controller/node/node_controller.go
  pkg/operator/staticpod/controller/node/node_controller_test.go
  pkg/operator/staticpod/controller/prune/prune_controller.go
  pkg/operator/staticpod/controller/prune/prune_controller_test.go
  pkg/operator/staticpod/controller/revision/deployment_controller.go
  pkg/operator/staticpod/controller/revision/deployment_controller_test.go
  pkg/operator/staticpod/controllers.go
  pkg/operator/status/status_controller.go
  pkg/operator/status/status_controller_test.go
  pkg/operator/v1alpha1helpers/helper_test.go
  pkg/operator/v1alpha1helpers/helpers.go
  pkg/operator/v1alpha1status/controller.go
  pkg/operator/v1helpers/helpers.go
  pkg/operator/v1helpers/interfaces.go
  pkg/operator/v1helpers/test_helpers.go.go
Labels: approved, lgtm, size/XXL

#182 don't clear status conditions or we get update churn
  pkg/operator/status/status_controller.go
Labels: approved, lgtm, size/XS

#183 fix ownerref to have values, not empty
  pkg/operator/staticpod/controller/revision/revision_controller.go
  pkg/operator/staticpod/controller/revision/revision_controller_test.go
Labels: approved, lgtm, size/XS

#184 don't fail on servicemonitor update failure
  pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
Labels: approved, lgtm, size/XS

#186 streamline objectref hash
  pkg/operator/resource/resourcehash/as_configmap.go
Labels: approved, lgtm, size/S

#188 add resource syncing to configobservation
  pkg/operator/configobserver/config_observer_controller.go
  pkg/operator/configobserver/config_observer_controller_test.go
Labels: approved, lgtm, size/XS

#187 Reduce qps
  pkg/operator/resource/resourcehash/as_configmap.go
Labels: approved, lgtm, size/M

#189 create a cached version of getters to reduce qps
  pkg/operator/resourcesynccontroller/resourcesync_controller.go
  pkg/operator/resourcesynccontroller/resourcesync_controller_test.go
  pkg/operator/staticpod/controller/prune/prune_controller.go
  pkg/operator/staticpod/controller/prune/prune_controller_test.go
  pkg/operator/staticpod/controller/revision/revision_controller.go
  pkg/operator/staticpod/controller/revision/revision_controller_test.go
  pkg/operator/staticpod/controllers.go
  pkg/operator/v1helpers/core_getters.go
  pkg/operator/v1helpers/fake_informers.go
  pkg/operator/v1helpers/informers.go
Labels: approved, lgtm, size/L

#190 make the hash tolerant of missing items
  pkg/operator/resource/resourcehash/as_configmap.go
Labels: approved, lgtm, size/S

#192 rotate only after the signer has had some time to propogate
  pkg/operator/certrotation/client_cert_rotation_controller.go
  pkg/operator/certrotation/client_cert_rotation_controller_test.go
  pkg/operator/certrotation/target.go
  pkg/operator/certrotation/target_test.go
Labels: approved, lgtm, size/L

#194 Revert "status: report cluster operator version"
  pkg/operator/status/status_controller.go
Labels: approved, lgtm, size/XS

#196 add conditions for cert rotators
  pkg/operator/certrotation/cabundle.go
  pkg/operator/certrotation/client_cert_rotation_controller.go
Labels: approved, lgtm, size/S

#198 fix cached getters to return fresh objects to avoid cache mutation
  pkg/operator/v1helpers/core_getters.go
Labels: approved, lgtm, size/S

#177 Add optional configMaps to revision controller
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
  pkg/operator/staticpod/controller/revision/revision_controller.go
  pkg/operator/staticpod/controller/revision/revision_controller_test.go
  pkg/operator/staticpod/controllers.go
  pkg/operator/staticpod/installerpod/cmd.go
  pkg/operator/staticpod/installerpod/cmd_test.go
Labels: approved, lgtm, size/XL

#185 Remove unneeded GO_PACKAGES_EXPANDED
  Makefile
  alpha-build-machinery/make/lib/golang.mk
  alpha-build-machinery/make/targets/golang/verify-update.mk
Labels: approved, lgtm, size/XS

#199 prevent panic on missing mutex
  pkg/operator/status/version.go
  pkg/operator/status/version_test.go
Labels: approved, lgtm, size/M

#202 operator: set the last transition time properly
  pkg/config/clusteroperator/v1helpers/status.go
Labels: approved, lgtm, size/XS

#201 set transition time on conditions properly
  pkg/operator/v1helpers/helpers.go
Labels: approved, lgtm, size/XS

#200 Fix building multiple binaries
  Makefile
  alpha-build-machinery/Makefile
  alpha-build-machinery/make/default.example.mk
  alpha-build-machinery/make/default.example.mk.help.log
  alpha-build-machinery/make/examples/multiple-binaries/Makefile
  alpha-build-machinery/make/examples/multiple-binaries/Makefile.test
  alpha-build-machinery/make/examples/multiple-binaries/Makefile.test.log
  alpha-build-machinery/make/examples/multiple-binaries/cmd/oc/main.go
  alpha-build-machinery/make/examples/multiple-binaries/cmd/openshift/main.go
  alpha-build-machinery/make/golang.example.mk
  alpha-build-machinery/make/golang.example.mk.help.log
  alpha-build-machinery/make/golang.mk
  alpha-build-machinery/make/lib/golang.mk
  alpha-build-machinery/make/operator.example.mk
  alpha-build-machinery/make/operator.example.mk.help.log
  alpha-build-machinery/make/targets/golang/build.mk
Labels: approved, lgtm, size/L

#203 static pods are available even if they aren't at the latest revision
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
Labels: approved, lgtm, size/M

#206 add installer cmd debugging
  pkg/operator/staticpod/installerpod/cmd.go
Labels: approved, lgtm, size/S

#175 Wire prune controller to run and sync limits from operator config
  pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
  pkg/operator/staticpod/controller/backingresource/backing_resource_controller_test.go
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
  pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller_test.go
  pkg/operator/staticpod/controller/node/node_controller_test.go
  pkg/operator/staticpod/controller/prune/prune_controller.go
  pkg/operator/staticpod/controller/prune/prune_controller_test.go
  pkg/operator/staticpod/controller/revision/revision_controller.go
  pkg/operator/staticpod/controller/revision/revision_controller_test.go
  pkg/operator/staticpod/controllers.go
  pkg/operator/v1helpers/interfaces.go
  pkg/operator/v1helpers/test_helpers.go
Labels: approved, lgtm, size/L

#205 Add mutex and trace profiles to serviceability, handle unique
  pkg/serviceability/serviceability.go
Labels: approved, lgtm, size/S

#207 set failing status for failing installer pod
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
Labels: approved, lgtm, size/M

#209 staticpod: set priority class and tolerations for installer pod
  pkg/operator/staticpod/controller/installer/bindata/bindata.go
  pkg/operator/staticpod/controller/installer/manifests/installer-pod.yaml
Labels: approved, lgtm, size/XS

#211 Prune old installer pods
  pkg/operator/staticpod/controller/installer/installer_controller.go
Labels: approved, lgtm, size/S

#212 Fix possible nil deref on isLatestRevisionCurrent reason
  pkg/operator/staticpod/controller/revision/revision_controller.go
Labels: approved, lgtm, size/XS

#214 add pruner pod priorityclass and toleration
  pkg/operator/staticpod/controller/installer/bindata/bindata.go
  pkg/operator/staticpod/controller/installer/manifests/installer-pod.yaml
  pkg/operator/staticpod/controller/prune/bindata/bindata.go
  pkg/operator/staticpod/controller/prune/manifests/pruner-pod.yaml
Labels: approved, lgtm, size/S

#215 add pruner pod ownerrefs for revision
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
  pkg/operator/staticpod/controller/prune/prune_controller.go
  pkg/operator/staticpod/controller/prune/prune_controller_test.go
Labels: approved, lgtm, size/M
