Repository openshift/library-go, pull requests merged in 2019-06, with the labels that each got.

#431 add serviceaccount oauth client determination
  pkg/authorization/scopemetadata/user_describers.go
  pkg/oauth/oauthserviceaccountclient/oauthclientregistry.go
  pkg/oauth/oauthserviceaccountclient/oauthclientregistry_test.go
Labels: approved, lgtm, size/XXL

#432 add template processing to library-go
  pkg/template/templateprocessing/object.go
  pkg/template/templateprocessing/object_test.go
  pkg/template/templateprocessing/template.go
  pkg/template/templateprocessing/template_test.go
  pkg/template/templateprocessing/testdata/guestbook.json
  pkg/template/templateprocessing/testdata/guestbook_list.json
Labels: approved, lgtm, size/XXL

#433 move security uid package for scc
  pkg/security/uid/uid.go
  pkg/security/uid/uid_test.go
Labels: approved, lgtm, size/L

#434 move quota type util used by ocm and oas
  pkg/quota/quotautil/helpers.go
  pkg/template/templateprocessingclient/dynamic_process.go
Labels: approved, lgtm, size/L

#430 start informers after the listers have been requested
  pkg/operator/staticpod/certsyncpod/certsync_cmd.go
  pkg/operator/staticpod/certsyncpod/certsync_controller.go
Labels: approved, lgtm, size/S

#440 add network plugin constants
  pkg/network/networkutils/networkutils.go
Labels: approved, lgtm, size/XS

#441 Add image util used by cli and apiserver
  pkg/image/imageutil/helpers.go
  pkg/image/imageutil/helpers_test.go
Labels: approved, lgtm, size/M

#442 image: add missing docker types
  pkg/image/dockerv1client/conversion.go
  pkg/image/dockerv1client/types.go
Labels: lgtm, size/M

#443 Add more imageutils shared between oc and importer
  pkg/image/imageutil/helpers.go
  pkg/image/imageutil/helpers_test.go
Labels: lgtm, size/L

#446 pem block parsing used in several binaries
  pkg/certs/pem.go
Labels: approved, lgtm, size/M

#447 image: expose ParseDigest
  pkg/image/imageutil/helpers.go
Labels: approved, lgtm, size/XS

#444 staticpod-controller: introduce reason strings why nodes were chosen
  glide.lock
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
  vendor/github.com/docker/distribution/contrib/docker-integration/malevolent-certs/ca.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/nginx/ssl/registry-ca+ca.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/nginx/ssl/registry-ca+client-cert.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/nginx/ssl/registry-ca+client-key.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/nginx/ssl/registry-ca+localhost-cert.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/nginx/ssl/registry-ca+localhost-key.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/nginx/ssl/registry-ca+localregistry-cert.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/nginx/ssl/registry-ca+localregistry-key.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/nginx/ssl/registry-noca+client-cert.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/nginx/ssl/registry-noca+client-key.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/nginx/ssl/registry-noca+localhost-cert.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/nginx/ssl/registry-noca+localhost-key.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/nginx/ssl/registry-noca+localregistry-cert.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/nginx/ssl/registry-noca+localregistry-key.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/tokenserver-oauth/certs/ca.pem
  vendor/github.com/docker/distribution/contrib/docker-integration/tokenserver/certs/ca.pem
  vendor/github.com/openshift/api/build/v1/consts.go
  vendor/github.com/openshift/api/project/v1/types.go
  vendor/gopkg.in/yaml.v2/decode_test.go
  vendor/gopkg.in/yaml.v2/encode.go
  vendor/gopkg.in/yaml.v2/encode_test.go
Labels: approved, lgtm, size/XL

#448 snip links between build controller and build apiserver
  glide.lock
  pkg/build/buildutil/buildutil.go
  pkg/build/buildutil/buildutil_test.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/utils.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/utils_test.go
  vendor/github.com/openshift/api/build/v1/consts.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/console/OWNERS
  vendor/github.com/openshift/api/console/install.go
  vendor/github.com/openshift/api/console/v1/doc.go
  vendor/github.com/openshift/api/console/v1/register.go
  vendor/github.com/openshift/api/console/v1/types.go
  vendor/github.com/openshift/api/console/v1/types_console_cli_download.go
  vendor/github.com/openshift/api/console/v1/types_console_link.go
  vendor/github.com/openshift/api/console/v1/types_console_notification.go
  vendor/github.com/openshift/api/console/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/console/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/hack/lib/init.sh
  vendor/github.com/openshift/api/hack/update-deepcopy.sh
  vendor/github.com/openshift/api/network/v1/generated.pb.go
  vendor/github.com/openshift/api/network/v1/generated.proto
  vendor/github.com/openshift/api/network/v1/types.go
  vendor/github.com/openshift/api/network/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/network/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types_dns.go
  vendor/google.golang.org/appengine/go.mod
  vendor/google.golang.org/appengine/go.sum
  vendor/gopkg.in/yaml.v2/decode_test.go
  vendor/gopkg.in/yaml.v2/encode.go
  vendor/gopkg.in/yaml.v2/encode_test.go
Labels: approved, lgtm, size/XXL

#449 Add missing image utils
  pkg/image/imageutil/helpers.go
  pkg/image/imageutil/helpers_test.go
Labels: approved, lgtm, size/M

#450 add helpers shared with e2e tests
  pkg/apps/appsutil/util.go
  pkg/image/imageutil/helpers.go
Labels: approved, lgtm, size/L

#451 add shared apiserver/controller helpers for builds
  pkg/image/imageutil/helpers.go
Labels: approved, lgtm, size/XS

#452 move more shared image helpers
  pkg/image/imageutil/helpers.go
Labels: approved, lgtm, size/S

#453 reports `NotReady` status of master nodes
  pkg/crypto/crypto.go
  pkg/operator/condition/condition.go
  pkg/operator/staticpod/controller/node/node_controller.go
  pkg/operator/staticpod/controller/node/node_controller_test.go
Labels: approved, lgtm, size/L

#456 quota: add error helpers and fix package name
  pkg/quota/quotautil/error.go
  pkg/quota/quotautil/helpers.go
Labels: approved, lgtm, size/M

#457 split valid and enabled TLS versions
  pkg/config/validation/serving_info.go
  pkg/crypto/crypto.go
  pkg/crypto/crypto_test.go
Labels: approved, lgtm, size/S

#458 change intent of ValidTLSVersions()
  pkg/config/validation/serving_info.go
  pkg/crypto/crypto.go
Labels: approved, lgtm, size/S

#462 add apiserver helpers to library-go
  pkg/apiserver/admission/admissionregistrationtesting/admissiontesting.go
  pkg/apiserver/admission/admissionrestconfig/intiializers.go
  pkg/apiserver/admission/admissiontimeout/decorator.go
  pkg/apiserver/admission/admissiontimeout/timeoutadmission.go
  pkg/apiserver/admission/admissiontimeout/timeoutadmission_test.go
  pkg/apiserver/apiserverconfig/cachecontrol.go
  pkg/apiserver/apiserverconfig/longrunning.go
  pkg/apiserver/apiserverconfig/personal_subjectaccessreview.go
  pkg/apiserver/apiserverconfig/project_request_info_resolver.go
  pkg/apiserver/apiserverconfig/requestinforesolver.go
Labels: approved, lgtm, size/L

#463 allow more interia for degraded because installer pods take a long time for AWS
  pkg/operator/status/condition.go
  pkg/operator/status/status_controller_test.go
Labels: approved, lgtm, size/S

#464 build-machinery: Add version support
  alpha-build-machinery/Makefile
  alpha-build-machinery/make/examples/multiple-binaries/.gitignore
  alpha-build-machinery/make/examples/multiple-binaries/Makefile.test
  alpha-build-machinery/make/examples/multiple-binaries/Makefile.test.log
  alpha-build-machinery/make/examples/multiple-binaries/cmd/oc/main.go
  alpha-build-machinery/make/examples/multiple-binaries/pkg/version/version.go
  alpha-build-machinery/make/lib/golang.mk
  alpha-build-machinery/make/targets/golang/build.mk
Labels: approved, lgtm, size/M
