Repository openshift/library-go, pull requests merged in 2020-02, with the labels that each got.

#694 Add version check and wire it for `go`
  alpha-build-machinery/make/examples/version-checks/Makefile
  alpha-build-machinery/make/examples/version-checks/Makefile.test
  alpha-build-machinery/make/examples/version-checks/Makefile.test.log
  alpha-build-machinery/make/lib/golang.mk
  alpha-build-machinery/make/lib/version.mk
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#697 Bug 1793267: Add -mod=vendor fallback for `go list`
  alpha-build-machinery/make/lib/golang.mk
  alpha-build-machinery/make/targets/openshift/deps.mk
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#698 build-machinery: use -trimpath by default
  alpha-build-machinery/make/examples/multiple-binaries/Makefile.test.log
  alpha-build-machinery/make/lib/golang.mk
Labels: approved, lgtm, size/S

#700 factory: fix time based resync to use queue instead of calling sync directly
  pkg/controller/factory/base_controller.go
Labels: approved, lgtm, size/S

#704 bug 1798725: allow static pod operator to be composed
  pkg/operator/condition/condition.go
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#705 Add alpha-build-machinery warning
  alpha-build-machinery/make/golang.mk
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#706 bug 1800321: add substitution for NODE_NAME inside of static pods
  pkg/operator/staticpod/controller/installer/bindata/bindata.go
  pkg/operator/staticpod/controller/installer/manifests/installer-pod.yaml
  pkg/operator/staticpod/installerpod/cmd.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#707 bug 1800609: add cpu limits to become guaranteed
  pkg/operator/staticpod/controller/installer/bindata/bindata.go
  pkg/operator/staticpod/controller/installer/manifests/installer-pod.yaml
  pkg/operator/staticpod/controller/prune/bindata/bindata.go
  pkg/operator/staticpod/controller/prune/manifests/pruner-pod.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#708 bump openshift/api for IPv6DualStack removal
  go.mod
  go.sum
  pkg/operator/configobserver/featuregates/observe_featuregates_test.go
  vendor/github.com/gogo/protobuf/gogoproto/gogo.pb.go
  vendor/github.com/gogo/protobuf/proto/encode.go
  vendor/github.com/gogo/protobuf/proto/lib.go
  vendor/github.com/gogo/protobuf/proto/properties.go
  vendor/github.com/gogo/protobuf/proto/table_marshal.go
  vendor/github.com/gogo/protobuf/proto/table_merge.go
  vendor/github.com/gogo/protobuf/proto/table_unmarshal.go
  vendor/github.com/gogo/protobuf/proto/text.go
  vendor/github.com/gogo/protobuf/protoc-gen-gogo/descriptor/descriptor.pb.go
  vendor/github.com/google/gofuzz/README.md
  vendor/github.com/google/gofuzz/fuzz.go
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/README.md
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/0000_03_config-operator_01_proxy.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_build.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_image.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/network/v1/001-clusternetwork-crd.yaml
  vendor/github.com/openshift/api/network/v1/002-hostsubnet-crd.yaml
  vendor/github.com/openshift/api/network/v1/003-netnamespace-crd.yaml
  vendor/github.com/openshift/api/network/v1/004-egressnetworkpolicy-crd.yaml
  vendor/github.com/openshift/api/network/v1/generated.pb.go
  vendor/github.com/openshift/api/network/v1/generated.proto
  vendor/github.com/openshift/api/network/v1/types.go
  vendor/github.com/openshift/api/network/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/network/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#701 add methods to manipulation observed configuration values
  pkg/operator/resource/resourcemerge/generic_config_merger.go
  pkg/operator/resource/resourcemerge/generic_config_merger_test.go
Labels: approved, lgtm, size/L

#712 bump: openshift/build-machinery-go
  go.mod
  go.sum
  vendor/github.com/openshift/build-machinery-go/OWNERS
  vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk
  vendor/github.com/openshift/build-machinery-go/make/lib/version.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/deps-gomod.mk
  vendor/modules.txt
Labels: approved, lgtm, size/S

#684 Bug 1774156: 4.2 cherry-picks in support of automated service ca rotation
  pkg/crypto/crypto.go
  pkg/crypto/crypto_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#715 Bug 1805398: Allow disabling serving in ControllerBuilder
  pkg/controller/controllercmd/builder.go
  pkg/controller/controllercmd/cmd.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#719 DEVEXP-515: Added support for RequestModifiers.
  pkg/image/registryclient/client.go
Labels: approved, lgtm, size/S

#720 Bug 1806876: limit number of ldap entries based on its capacity
  pkg/security/ldapquery/query.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#717 bug 1806692: substitute all content for node name and revision
  pkg/operator/staticpod/installerpod/cmd.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#722 set .sh files to be executeable
  pkg/operator/staticpod/installerpod/cmd.go
Labels: approved, lgtm, size/S
