Repository openshift/library-go, pull requests merged in 2020-04, with the labels that each got.

#760 add WithCustomInstaller method to Builder interface
  pkg/operator/staticpod/controllers.go
Labels: approved, lgtm

#764 Bug 1819256: Fix SA token sync
  pkg/operator/resource/resourceapply/core.go
  pkg/operator/resource/resourceapply/core_test.go
Labels: approved, bugzilla/valid-bug, lgtm

#765 [release-4.4] Fix SA token sync
  pkg/operator/resource/resourceapply/core.go
  pkg/operator/resource/resourceapply/core_test.go
Labels: approved, cherry-pick-approved, lgtm

#709 Bug 1779438: fix race for controller commands
  pkg/controller/controllercmd/cmd.go
  pkg/controller/fileobserver/observer_polling.go
  pkg/controller/fileobserver/observer_polling_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#768 Fix ApplySecret for Type changes
  pkg/operator/certrotation/signer_test.go
  pkg/operator/certrotation/target_test.go
  pkg/operator/encryption/controllers/state_controller_test.go
  pkg/operator/encryption/encryptionconfig/secret.go
  pkg/operator/encryption/secrets/secrets.go
  pkg/operator/encryption/testing/helpers.go
  pkg/operator/resource/resourceapply/core.go
  pkg/operator/resource/resourceapply/core_test.go
  pkg/operator/resourcesynccontroller/resourcesync_controller_test.go
Labels: approved, lgtm

#771 Add WithVersion() to command builder that reports binary version to prometheus
  pkg/controller/controllercmd/builder.go
Labels: approved, lgtm

#772 cmd: add WithVersion to StartController
  pkg/controller/controllercmd/cmd.go
Labels: approved, lgtm

#775 Bug 1826259: fix ingress CA cert location
  test/library/metrics/query.go
Labels: approved, bugzilla/urgent, bugzilla/valid-bug, lgtm

#773 Update Apply{DaemonSet,Deployment} to rely on a hash of the spec
  pkg/operator/resource/resourceapply/apps.go
Labels: approved, lgtm

#779 version: make sure to always have namespace when reporting version
  pkg/controller/controllercmd/builder.go
Labels: approved, lgtm

#780 resourcesynccontroller: fix race in unit test
  pkg/operator/resourcesynccontroller/resourcesync_controller_test.go
Labels: approved, lgtm

#778 Bug 1826230: Bump to kube v1.18.2
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/apimachinery/pkg/watch/streamwatcher.go
  vendor/k8s.io/client-go/rest/request.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/client-go/tools/watch/retrywatcher.go
  vendor/modules.txt
Labels: approved, bugzilla/urgent, bugzilla/valid-bug, lgtm

#783 staticpodstate: improve condition and event messages
  pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
Labels: approved, lgtm

#776 Remove bitbucket.org/ww/goautoneg dependency
  go.mod
  go.sum
  pkg/apiserver/httprequest/httprequest.go
  vendor/bitbucket.org/ww/goautoneg/Makefile
  vendor/bitbucket.org/ww/goautoneg/README.txt
  vendor/bitbucket.org/ww/goautoneg/autoneg.go
  vendor/modules.txt
Labels: approved, lgtm

#777 events: make kube broadcaster shutdown gracefully and tune correlator so we don't loose events
  pkg/controller/controllercmd/builder.go
  pkg/controller/controllercmd/builder_test.go
  pkg/controller/controllercmd/cmd.go
  pkg/operator/events/eventstesting/recorder_testing.go
  pkg/operator/events/eventstesting/recorder_wrapper.go
  pkg/operator/events/recorder.go
  pkg/operator/events/recorder_in_memory.go
  pkg/operator/events/recorder_logging.go
  pkg/operator/events/recorder_upstream.go
  pkg/operator/events/recorder_upstream_test.go
  pkg/operator/staticpod/certsyncpod/certsync_cmd.go
Labels: approved, lgtm

#770 Fix error handling of status controller
  pkg/operator/status/status_controller.go
Labels: approved, lgtm

#787 Fix ClusterOperator event when version changes
  pkg/config/clusteroperator/v1helpers/status.go
Labels: approved, lgtm
