Repository openshift/library-go, pull requests merged in 2020-09, with the labels that each got.

#875 Fix crypto configuration for golang 1.14
  pkg/crypto/crypto.go
  pkg/crypto/crypto_test.go
Labels: approved, lgtm

#877 dockerv1client: fix conversions
  pkg/image/dockerv1client/client.go
  pkg/image/dockerv1client/client_test.go
Labels: approved, lgtm

#883 resourcesync: add provided by to sync error message
  pkg/operator/resourcesynccontroller/interfaces.go
  pkg/operator/resourcesynccontroller/resourcesync_controller.go
Labels: approved, lgtm

#885 Bug 1876913: Add global git configs
  pkg/git/repository.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#884 Bug 1876874: log request and respose bodies for identities
  pkg/operator/apiserver/audit/bindata/bindata.go
  pkg/operator/apiserver/audit/manifests/audit-policies-cm.yaml
  pkg/operator/apiserver/audit/testdata/audit-policies-cm-scenario-1.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#886 installer: do not log stacktrace when installer pod fail
  pkg/operator/staticpod/installerpod/cmd.go
Labels: approved, lgtm

#888 installer: add reason with blame
  pkg/operator/staticpod/controller/installer/blame.go
  pkg/operator/staticpod/controller/installer/installer_controller.go
Labels: approved, lgtm

#887 installer: log connection errors on retry
  pkg/operator/resource/retry/retry.go
  pkg/operator/resource/retry/retry_test.go
Labels: approved, lgtm

#864 Validate operatorSpec.logLevel
  pkg/operator/loglevel/logging_controller.go
  pkg/operator/loglevel/logging_controller_test.go
  pkg/operator/loglevel/util.go
Labels: approved, lgtm

#889 Bug 1876913: Redact proxy urls in git config
  pkg/git/repository.go
  pkg/git/repository_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#891 Fix panic in cache sync
  pkg/controller/factory/base_controller.go
  pkg/controller/factory/base_controller_test.go
Labels: approved, lgtm

#892 use upstream sigs.k8s.io/kube-storage-version-migrator
  go.mod
  go.sum
  pkg/operator/encryption/controllers/migrators/kubestorageversionmigrator.go
  vendor/modules.txt
  vendor/sigs.k8s.io/kube-storage-version-migrator/LICENSE
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/apis/migration/v1alpha1/doc.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/apis/migration/v1alpha1/register.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/apis/migration/v1alpha1/types.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/apis/migration/v1alpha1/zz_generated.deepcopy.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/clientset.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/doc.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/scheme/doc.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/scheme/register.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/typed/migration/v1alpha1/doc.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/typed/migration/v1alpha1/generated_expansion.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/typed/migration/v1alpha1/migration_client.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/typed/migration/v1alpha1/storagestate.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/typed/migration/v1alpha1/storageversionmigration.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/informer/internalinterfaces/factory_interfaces.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/informer/migration/v1alpha1/interface.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/informer/migration/v1alpha1/storagestate.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/informer/migration/v1alpha1/storageversionmigration.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/lister/migration/v1alpha1/expansion_generated.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/lister/migration/v1alpha1/storagestate.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/lister/migration/v1alpha1/storageversionmigration.go
Labels: approved, lgtm

#876 controller factory: allow conditional queue key add
  pkg/controller/factory/controller_context.go
  pkg/controller/factory/controller_context_test.go
  pkg/controller/factory/factory.go
Labels: approved, lgtm

#894 Bug 1878648: apiserver-audit: add secure-oauth-storage-* policies
  pkg/operator/apiserver/audit/bindata/bindata.go
  pkg/operator/apiserver/audit/manifests/audit-policies-cm.yaml
  pkg/operator/apiserver/audit/testdata/audit-policies-cm-scenario-1.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#882 [release-4.3] Bug 1876486: static-pod-installer: recreate installers that disappeared
  glide.lock
  glide.yaml
  pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/api/apps/v1/generated.proto
  vendor/github.com/openshift/api/apps/v1/types.go
  vendor/github.com/openshift/api/authorization/v1/generated.proto
  vendor/github.com/openshift/api/authorization/v1/types.go
  vendor/github.com/openshift/api/authorization/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/hack/verify-crds.sh
  vendor/github.com/openshift/api/image/v1/generated.proto
  vendor/github.com/openshift/api/image/v1/types.go
  vendor/github.com/openshift/api/image/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_kubeapiserver.go
  vendor/github.com/openshift/api/operator/v1/types_kubecontrollermanager.go
  vendor/github.com/openshift/api/operator/v1/types_scheduler.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/project/v1/generated.proto
  vendor/github.com/openshift/api/project/v1/types.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/template/v1/generated.proto
  vendor/github.com/openshift/api/template/v1/types.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#881 [release-4.4] Bug 1876484: static-pod-installer: recreate installers that disappeared
  pkg/operator/staticpod/controller/installer/installer_controller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#893 apps: add human readable deployment pod containers status helper
  pkg/apps/deployment/status.go
  pkg/apps/deployment/status_test.go
  pkg/operator/apiserver/controller/workload/workload.go
  pkg/operator/apiserver/controller/workload/workload_test.go
  pkg/operator/apiserver/controllerset/apiservercontrollerset.go
Labels: approved, lgtm

#896 Fix reading of CRD v1
  pkg/operator/resource/resourceread/apiextensions.go
Labels: approved, lgtm

#899 v1helpers: add namespaced informer for pods
  pkg/operator/v1helpers/informers.go
Labels: approved, lgtm

#900 workload: switch to use pod lister instead of passing full informer factory
  pkg/operator/apiserver/controller/workload/workload.go
  pkg/operator/apiserver/controllerset/apiservercontrollerset.go
Labels: approved, lgtm

#898 Replace bitbucket.org/ww/goautoneg with its mirror
  go.mod
  go.sum
  pkg/apiserver/httprequest/httprequest.go
  vendor/bitbucket.org/ww/goautoneg/Makefile
  vendor/bitbucket.org/ww/goautoneg/README.txt
  vendor/bitbucket.org/ww/goautoneg/autoneg.go
  vendor/modules.txt
Labels: approved, lgtm

#890 Bug 1878007: Validate operatorSpec.logLevel
  pkg/operator/loglevel/logging_controller.go
  pkg/operator/loglevel/logging_controller_test.go
  pkg/operator/loglevel/util.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#905 staticpodstate: report if container is running when not ready
  pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
Labels: approved, lgtm

#901 Bug 1879475: Update status reasons to be more explicit
  pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller.go
  pkg/operator/csi/csidrivernodeservicecontroller/csi_driver_node_service_controller.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#880 connectivitycheckcontroller: add unsupported options to enable/disable
  Makefile
  pkg/operator/connectivitycheckcontroller/bindata/bindata.go
  pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
  pkg/operator/connectivitycheckcontroller/manifests/controlplane.operator.openshift.io_podnetworkconnectivitychecks.yaml
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1beta1/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/factory.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/generic.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1/expansion_generated.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1beta1/expansion_generated.go
  vendor/modules.txt
Labels: approved, lgtm

#908 connectivitycheckcontroller: configurable enabled by default flag
  pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
Labels: approved, lgtm

#902 Apply webhookconfiguration
  pkg/operator/resource/resourceapply/admissions.go
  pkg/operator/resource/resourceapply/admissions_test.go
  pkg/operator/resource/resourceapply/generic.go
Labels: approved, lgtm
