Repository openshift/library-go, pull requests merged in 2020-10, with the labels that each got.

#909 csi: add ${CLUSTER_ID} to placeholders
  pkg/operator/csi/csicontrollerset/csi_controller_set.go
  pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller.go
  pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller_test.go
Labels: approved, lgtm

#910 verifier: expose Interface and hide implementation details
  pkg/verify/configmap.go
  pkg/verify/verify.go
  pkg/verify/verify_test.go
Labels: approved, lgtm

#911 pkg/route: Add a package with route helpers
  pkg/route/OWNERS
  pkg/route/routeapihelpers/routeapihelpers.go
  pkg/route/routeapihelpers/routeapihelpers_test.go
Labels: approved, lgtm

#914 image/reference: support parsing partial repo names
  pkg/image/reference/reference.go
  pkg/image/reference/reference_test.go
Labels: approved, lgtm

#917 Check errors if we can't annotate a secret
  pkg/operator/encryption/controllers/migration_controller.go
Labels: approved, lgtm

#916 Bug 1886627: operator/installer: don't mark a successful installer with pending revision as failed
  pkg/operator/staticpod/controller/installer/installer_controller.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#918 connectivitycheckcontroller: do not remove crd if checks exist
  pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
Labels: approved, lgtm

#710 pkg/operator/status/condition: Say "All is well" with no interesting conditions
  pkg/operator/status/condition.go
Labels: approved, lgtm, size/XS

#922 don't wait on kube-apiserver available
  pkg/operator/apiserver/controller/workload/workload.go
Labels: approved, lgtm

#920 add UID to all static pods to trick kubelet into honoring grace period
  pkg/operator/resource/resourceread/core.go
  pkg/operator/staticpod/installerpod/cmd.go
Labels: approved, lgtm

#925 Change GetServiceCIDR() to GetServiceCIDRs() for dual-stack support
  pkg/operator/configobserver/network/observe_network.go
  pkg/operator/configobserver/network/observe_networking_test.go
Labels: approved, lgtm

#915 Add support for kubevirt platform
  go.mod
  go.sum
  pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
  pkg/operator/connectivitycheckcontroller/bindata/bindata.go
  pkg/operator/connectivitycheckcontroller/manifests/controlplane.operator.openshift.io_podnetworkconnectivitychecks.yaml
  pkg/operator/genericoperatorclient/dynamic_operator_client_test.go
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/01-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/types_imagepruner.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_10_config-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_12_etcd-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_30_openshift-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_40_kube-storage-version-migrator-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-openshift-controller-manager-operator_02_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_service-ca-operator_02_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_80_csi_snapshot_controller_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/0000_10-pod-network-connectivity-check.crd.yaml
  vendor/modules.txt
Labels: approved, lgtm

#921 Update to kubernetes v1.19.2
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/go.sum
  vendor/github.com/openshift/api/network/v1/001-clusternetwork-crd.yaml
  vendor/github.com/openshift/api/network/v1/002-hostsubnet-crd.yaml
  vendor/github.com/openshift/api/network/v1/003-netnamespace-crd.yaml
  vendor/github.com/openshift/api/network/v1/004-egressnetworkpolicy-crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/crd-schema-gen.mk
  vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/component-base/logs/registry.go
  vendor/modules.txt
Labels: approved, lgtm

#928 fix image reference parsing when tag includes a `.`
  pkg/image/reference/reference.go
  pkg/image/reference/reference_test.go
Labels: approved, lgtm

#904 Fixing function name case
  pkg/operator/loglevel/logging_controller.go
  pkg/operator/loglevel/util.go
Labels: approved, lgtm

#929 controller/staticpodstate: don't use relative times in conditions
  pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
Labels: approved, lgtm

#930 Bug 1890724: controller/staticpod: reduce noise of not-ready containers
  pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#933 collapse static pod bytes
  pkg/operator/staticpod/installerpod/cmd.go
Labels: approved, lgtm
