Repository openshift/library-go, pull requests merged in 2020-05, with the labels that each got.

#790 Bug 1832143: Prevent noisy events for ovirt cloud provider
  pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#792 Bug 1813894: Fix staticpod controller to use service ca from prometheus
  pkg/operator/staticpod/controller/monitoring/bindata/bindata.go
  pkg/operator/staticpod/controller/monitoring/manifests/service-monitor.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#782 [release-4.4] Update Apply{DaemonSet,Deployment} to rely on a hash of the spec
  pkg/operator/resource/resourceapply/apps.go
Labels: approved, lgtm

#793 factory: add bare informer registration
  pkg/controller/factory/factory.go
Labels: approved, lgtm

#789 Fix missing event in node controller
  pkg/operator/staticpod/controller/node/node_controller.go
  pkg/operator/staticpod/controller/node/node_controller_test.go
Labels: approved, lgtm

#800 Bug 1837675: Create reusable manifests package
  go.mod
  pkg/manifest/manifest.go
  pkg/manifest/manifest_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#804 Bug 1826230: Bump to kube 1.18.3
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/go.sum
  vendor/github.com/openshift/api/security/v1/0000_03_security-openshift_01_scc.crd.yaml
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/k8s.io/apimachinery/pkg/util/json/json.go
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/client-go/tools/clientcmd/client_config.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#805 Bug 1812126: double memory resource request and limits values
  pkg/operator/staticpod/controller/installer/bindata/bindata.go
  pkg/operator/staticpod/controller/installer/manifests/installer-pod.yaml
  pkg/operator/staticpod/controller/prune/bindata/bindata.go
  pkg/operator/staticpod/controller/prune/manifests/pruner-pod.yaml
Labels: approved, bugzilla/valid-bug, lgtm

#806 Update interrupted InProgress revisions to Abandoned
  pkg/operator/revisioncontroller/revision_controller.go
  pkg/operator/revisioncontroller/revision_controller_test.go
  pkg/operator/staticpod/controller/prune/prune_controller.go
  pkg/operator/staticpod/controller/prune/prune_controller_test.go
Labels: approved, lgtm
