Repository openshift/library-go, pull requests merged in 2020-01, with the labels that each got.

#653 build-machinery: respect -mod=vendor for go list
  alpha-build-machinery/make/lib/golang.mk
Labels: approved, lgtm, size/XS

#654 fileobserver: prometheus counter for observed actions
  pkg/controller/fileobserver/observer.go
  pkg/controller/fileobserver/observer_polling.go
Labels: approved, lgtm, size/M

#656 leaderelection: set release on cancel to true
  pkg/config/leaderelection/leaderelection.go
Labels: approved, lgtm, size/XS

#655 leaderelection: use proto client
  pkg/controller/controllercmd/builder.go
Labels: approved, lgtm, size/XS

#657 config: default bind network to tcp instead of tcp4
  pkg/config/configdefaults/config_default.go
Labels: approved, lgtm, size/XS

#659 build-machinery: Add human readable messages to go mod verify-deps
  alpha-build-machinery/make/targets/openshift/deps-gomod.mk
Labels: approved, lgtm, size/XS

#660 staticpod: improve node not ready degraded message to include reason and message
  pkg/operator/staticpod/controller/node/node_controller.go
  pkg/operator/staticpod/controller/node/node_controller_test.go
Labels: approved, lgtm, size/S

#176 helper for logging resource names
  pkg/operator/resource/resourceapply/event_helpers.go
  pkg/operator/resource/resourceapply/event_helpers_test.go
  pkg/operator/resource/resourcehelper/resource_helpers.go
Labels: approved, lgtm, size/L

#663 allow injection of ca bundles
  pkg/operator/resource/resourceapply/core.go
  pkg/operator/resource/resourceapply/core_test.go
Labels: approved, lgtm, size/L

#602 add helper functions for running prometheus query
  test/library/metrics/query.go
  vendor/github.com/prometheus/client_golang/api/client.go
  vendor/github.com/prometheus/client_golang/api/prometheus/v1/api.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#664 changes the next empty encryption key's name for encryption e2e test
  test/library/encryption/helpers.go
Labels: approved, lgtm, size/XS

#590 cert-syncer: Fix events for not-found resources
  pkg/operator/staticpod/certsyncpod/certsync_controller.go
Labels: approved, lgtm, size/S

#668 Add observer for APIServer.Spec.AdditionalCORSAllowedOrigins
  pkg/operator/configobserver/apiserver/observe_cors.go
  pkg/operator/configobserver/apiserver/observe_cors_test.go
Labels: approved, lgtm, size/L

#667 Add controllerset for controlling an apiserver deployment
  pkg/operator/apiserver/controller/apiservice/apigroup.go
  pkg/operator/apiserver/controller/apiservice/apiservice_controller.go
  pkg/operator/apiserver/controller/apiservice/apiservice_controller_test.go
  pkg/operator/apiserver/controller/nsfinalizer/finalizer_controller.go
  pkg/operator/apiserver/controllerset/apiservercontrollerset.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/authentication.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/console.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/csisnapshotcontroller.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/dns.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/etcd.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/ingresscontroller.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/kubeapiserver.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/kubecontrollermanager.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/kubescheduler.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/kubestorageversionmigrator.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/network.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/openshiftapiserver.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/openshiftcontrollermanager.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/serviceca.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/servicecatalogapiserver.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/servicecatalogcontrollermanager.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/clientset.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/doc.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/fake/clientset_generated.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/fake/doc.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/fake/register.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1/fake/doc.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1/fake/fake_apiregistration_client.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1/fake/fake_apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/apiregistration_client.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/doc.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/fake/doc.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/fake/fake_apiregistration_client.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/fake/fake_apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/generated_expansion.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/apiregistration/interface.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/apiregistration/v1/apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/apiregistration/v1/interface.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/apiregistration/v1beta1/apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/apiregistration/v1beta1/interface.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/factory.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/generic.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/k8s.io/kube-aggregator/pkg/client/listers/apiregistration/v1/apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/listers/apiregistration/v1/expansion_generated.go
  vendor/k8s.io/kube-aggregator/pkg/client/listers/apiregistration/v1beta1/apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/listers/apiregistration/v1beta1/expansion_generated.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#677 make it possible to nerf feature gates if they are broken
  pkg/operator/configobserver/featuregates/observe_featuregates.go
  pkg/operator/configobserver/featuregates/observe_featuregates_test.go
Labels: approved, lgtm, size/M

#672 Static resource controller
  pkg/operator/resource/resourceapply/generic.go
  pkg/operator/resource/resourceapply/generic_test.go
  pkg/operator/staleconditions/remove_stale_conditions.go
  pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
  pkg/operator/staticpod/controller/backingresource/backing_resource_controller_test.go
  pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
  pkg/operator/staticpod/controllers.go
  pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/clientset.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/generated_expansion.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#678 Add namespace flag
  pkg/controller/controllercmd/cmd.go
  pkg/controller/controllercmd/flags.go
  pkg/operator/events/recorder.go
Labels: approved, lgtm, size/M

#673 let the static pod resource controller auto-find the required informers
  pkg/operator/resource/resourceapply/generic.go
  pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
  pkg/operator/staticpod/controllers.go
  pkg/operator/staticresourcecontroller/static_resource_controller.go
Labels: approved, lgtm, size/L

#675 add cached client capabilities to stay out of qps jail
  pkg/operator/resource/resourceapply/generic.go
  pkg/operator/staticpod/controller/backingresource/backing_resource_controller_test.go
  pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
  pkg/operator/staticpod/controllers.go
  pkg/operator/staticresourcecontroller/static_resource_controller.go
  pkg/operator/v1helpers/core_getters.go
Labels: approved, lgtm, size/M

#681 Remove unused post-bootstrap config override from rendering
  pkg/operator/render/options/config.go
  pkg/operator/render/options/generic.go
Labels: approved, lgtm, size/S

#682 Allow adjusting serving info to avoid port collisions
  pkg/controller/controllercmd/cmd.go
  pkg/controller/controllercmd/flags.go
Labels: approved, lgtm, size/XS

#683 Bug 1792501: Add memory request and limit to revision pruner pod
  pkg/operator/staticpod/controller/prune/bindata/bindata.go
  pkg/operator/staticpod/controller/prune/manifests/pruner-pod.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#666 Controller factory
  pkg/controller/factory/base_controller.go
  pkg/controller/factory/controller_context.go
  pkg/controller/factory/controller_test.go
  pkg/controller/factory/factory.go
  pkg/controller/factory/interfaces.go
  pkg/controller/manager/controller_manager.go
  pkg/operator/loglevel/logging_controller.go
  pkg/operator/loglevel/logging_controller_test.go
  pkg/operator/revisioncontroller/revision_controller.go
  pkg/operator/revisioncontroller/revision_controller_test.go
  pkg/operator/staticpod/certsyncpod/certsync_cmd.go
  pkg/operator/staticpod/certsyncpod/certsync_controller.go
  pkg/operator/staticpod/controller/backingresource/backing_resource_controller_test.go
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
  pkg/operator/staticpod/controller/installerstate/installer_state_controller.go
  pkg/operator/staticpod/controller/installerstate/installer_state_controller_test.go
  pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
  pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller_test.go
  pkg/operator/staticpod/controller/node/node_controller.go
  pkg/operator/staticpod/controller/node/node_controller_test.go
  pkg/operator/staticpod/controller/prune/prune_controller.go
  pkg/operator/staticpod/controller/prune/prune_controller_test.go
  pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  pkg/operator/staticpod/controllers.go
  pkg/operator/staticresourcecontroller/static_resource_controller.go
  pkg/operator/unsupportedconfigoverridescontroller/unsupportedconfigoverrides_controller.go
Labels: approved, lgtm, size/XXL

#686 adds static-resources-controller to apiserver-controller-set
  pkg/operator/apiserver/controllerset/apiservercontrollerset.go
Labels: approved, lgtm, size/S

#688 fix informer typo in static resource controller
  pkg/operator/staticresourcecontroller/static_resource_controller.go
Labels: approved, lgtm, size/XS

#685 controller: deflake controller factory test
  pkg/controller/factory/controller_test.go
Labels: approved, lgtm, size/M

#692 Make sure there are some packages to be build
  alpha-build-machinery/make/targets/golang/build.mk
  alpha-build-machinery/make/targets/openshift/crd-schema-gen.mk
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#693 fix detection of namespace
  pkg/operator/staticresourcecontroller/static_resource_controller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS
