Repository openshift/library-go, pull requests merged in 2020-03, with the labels that each got.

#680 Create reusable package to manage manifests for use by CVO and oc
  go.mod
  pkg/manifest/manifest.go
  pkg/manifest/manifest_test.go
Labels: approved, lgtm, size/L

#726 Bug 1810036: Set a random serial number for signing certificate templates
  pkg/crypto/crypto.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#699 Properly terminate controllers on leader election lost/shutdown
  pkg/controller/controllercmd/builder.go
  pkg/controller/controllercmd/builder_test.go
  pkg/controller/factory/base_controller.go
  pkg/controller/factory/factory.go
  pkg/controller/factory/interfaces.go
  pkg/controller/manager/controller_manager.go
  pkg/operator/resourcesynccontroller/resourcesync_controller.go
  pkg/operator/resourcesynccontroller/resourcesync_controller_test.go
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controllers.go
  pkg/operator/staticresourcecontroller/static_resource_controller.go
Labels: approved, lgtm, size/XL

#727 resourceapply: Allow removing run-level labels from namespaces
  pkg/operator/resource/resourceapply/core.go
  pkg/operator/resource/resourceapply/core_test.go
  pkg/operator/resource/resourcemerge/object_merger.go
Labels: approved, lgtm, size/L

#732 implements a generic workload controller
  go.mod
  pkg/operator/apiserver/controller/workload/workload.go
  pkg/operator/apiserver/controller/workload/workload_test.go
  pkg/operator/apiserver/controllerset/apiservercontrollerset.go
Labels: approved, lgtm, size/XL

#731 Migrate controllers to factory
  pkg/config/leaderelection/leaderelection.go
  pkg/controller/factory/base_controller.go
  pkg/controller/factory/controller_context.go
  pkg/controller/factory/controller_test.go
  pkg/controller/factory/factory.go
  pkg/controller/factory/interfaces.go
  pkg/operator/apiserver/controller/apiservice/apiservice_controller.go
  pkg/operator/apiserver/controller/apiservice/apiservice_controller_test.go
  pkg/operator/apiserver/controller/nsfinalizer/finalizer_controller.go
  pkg/operator/certrotation/client_cert_rotation_controller.go
  pkg/operator/configobserver/config_observer_controller.go
  pkg/operator/configobserver/config_observer_controller_test.go
  pkg/operator/management/management_state_controller.go
  pkg/operator/management/management_state_controller_test.go
  pkg/operator/resourcesynccontroller/resourcesync_controller.go
  pkg/operator/staleconditions/remove_stale_conditions.go
  pkg/operator/status/status_controller.go
  pkg/operator/status/status_controller_test.go
Labels: approved, lgtm, size/XXL

#734 allows for setting an optional prefix for condition's type field for the generic workload ctrl
  pkg/operator/apiserver/controller/workload/workload.go
  pkg/operator/apiserver/controller/workload/workload_test.go
  pkg/operator/apiserver/controllerset/apiservercontrollerset.go
Labels: approved, lgtm, size/M

#738 delegates creation of common informers down to workload controller
  pkg/operator/apiserver/controllerset/apiservercontrollerset.go
Labels: approved, lgtm, size/S

#737 logging: properly set log level
  pkg/operator/loglevel/logging_controller.go
  pkg/operator/loglevel/logging_controller_test.go
  pkg/operator/loglevel/util.go
  pkg/operator/staticpod/controller/installer/installer_controller.go
Labels: approved, lgtm, size/L

#743 configobserver: pass informers in controller constructor
  pkg/operator/configobserver/config_observer_controller.go
Labels: approved, lgtm, size/XS

#742 Fix oauthServiceAccount client interface to include contexts
  pkg/oauth/oauthserviceaccountclient/oauthclientregistry.go
  pkg/oauth/oauthserviceaccountclient/oauthclientregistry_test.go
Labels: approved, lgtm, size/M

#746 certrotation: check the context value for nil
  pkg/operator/certrotation/client_cert_rotation_controller.go
Labels: approved, lgtm

#748 Update prebase branch to fix metric query helpers
  test/library/metrics/query.go
Labels: approved, lgtm

#747 removes APIServicesToManage as it's specific to OAS
  pkg/operator/apiserver/controller/apiservice/apiservice_controller.go
  pkg/operator/apiserver/controller/apiservice/apiservice_controller_test.go
  pkg/operator/apiserver/controllerset/apiservercontrollerset.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/authentication.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/console.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/csisnapshotcontroller.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/dns.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/etcd.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/ingresscontroller.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/kubeapiserver.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/kubecontrollermanager.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/kubescheduler.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/kubestorageversionmigrator.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/network.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/openshiftapiserver.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/openshiftcontrollermanager.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/serviceca.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/servicecatalogapiserver.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/servicecatalogcontrollermanager.go
  vendor/modules.txt
Labels: approved, lgtm

#749 factory: fix appending to caches
  pkg/controller/factory/factory.go
  pkg/operator/resourcesynccontroller/resourcesync_controller_test.go
  pkg/operator/v1helpers/test_helpers.go
Labels: approved, lgtm

#744 config-observers: prune returned config
  pkg/operator/configobserver/apiserver/observe_cors.go
  pkg/operator/configobserver/apiserver/observe_tlssecurityprofile.go
  pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
  pkg/operator/configobserver/featuregates/observe_featuregates.go
  pkg/operator/configobserver/proxy/observe_proxy.go
  pkg/operator/configobserver/unstructured.go
Labels: approved, lgtm, size/L

#751 factory: improve unit test coverage
  pkg/controller/factory/base_controller.go
  pkg/controller/factory/base_controller_test.go
  pkg/controller/factory/controller_context_test.go
  pkg/controller/factory/factory.go
  pkg/controller/factory/factory_test.go
Labels: approved, lgtm

#733 apiserver observers: add switch to observe to apiServerArguments
  pkg/operator/configobserver/apiserver/observe_cors.go
  pkg/operator/configobserver/apiserver/observe_cors_test.go
  pkg/operator/configobserver/apiserver/observe_tlssecurityprofile.go
  pkg/operator/configobserver/apiserver/observe_tlssecurityprofile_test.go
Labels: approved, lgtm, size/L

#754 adds revision controller to APIServerControllerSet
  pkg/operator/apiserver/controllerset/apiservercontrollerset.go
Labels: approved, lgtm

#753 UnionRevisionLabelPodDeployer
  pkg/operator/encryption/deployer/unionrevisionedpod.go
  pkg/operator/encryption/deployer/unionrevisionedpod_test.go
Labels: approved, lgtm

#687 Migrate encryption controllers to factory
  pkg/operator/encryption/controllers.go
  pkg/operator/encryption/controllers/condition_controller.go
  pkg/operator/encryption/controllers/controller.go
  pkg/operator/encryption/controllers/key_controller.go
  pkg/operator/encryption/controllers/key_controller_test.go
  pkg/operator/encryption/controllers/migration_controller.go
  pkg/operator/encryption/controllers/migration_controller_test.go
  pkg/operator/encryption/controllers/migrators/inprocess.go
  pkg/operator/encryption/controllers/migrators/kubestorageversionmigrator.go
  pkg/operator/encryption/controllers/migrators/types.go
  pkg/operator/encryption/controllers/prune_controller.go
  pkg/operator/encryption/controllers/prune_controller_test.go
  pkg/operator/encryption/controllers/state_controller.go
  pkg/operator/encryption/controllers/state_controller_test.go
  pkg/operator/encryption/deployer/revisionedpod.go
  pkg/operator/encryption/deployer/unionrevisionedpod.go
  pkg/operator/encryption/deployer/unionrevisionedpod_test.go
  pkg/operator/encryption/statemachine/transition.go
  test/e2e-encryption/encryption_test.go
Labels: approved, lgtm, size/XL

#757 factory: add WithSyncDegradedOnError that allows handling degraded for simple sync()
  pkg/controller/factory/base_controller.go
  pkg/controller/factory/base_controller_test.go
  pkg/controller/factory/factory.go
Labels: approved, lgtm

#750 Add CSIDriver to resourceread and resourceapply
  pkg/operator/resource/resourceapply/storage.go
  pkg/operator/resource/resourceapply/storage_test.go
  pkg/operator/resource/resourceread/storage.go
Labels: approved, lgtm

#758 Update to k8s v0.18.0 tag
  go.mod
  go.sum
  vendor/github.com/openshift/api/Dockerfile.build
  vendor/github.com/openshift/api/config/v1/types_operatorhub.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/go.sum
  vendor/github.com/openshift/api/operator/v1/0000_10_config-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-svcat-apiserver-operator_02_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_authentication.go
  vendor/github.com/openshift/api/operator/v1/types_config.go
  vendor/github.com/openshift/api/operator/v1/types_servicecatalogapiserver.go
  vendor/github.com/openshift/api/operator/v1/types_servicecatalogcontrollermanager.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_operatorhub.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/operatorhub.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/interface.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/operatorhub.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/operatorhub.go
  vendor/k8s.io/api/networking/v1beta1/generated.proto
  vendor/k8s.io/api/networking/v1beta1/types.go
  vendor/k8s.io/api/networking/v1beta1/types_swagger_doc_generated.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/helpers.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/store.go
  vendor/k8s.io/utils/net/net.go
  vendor/k8s.io/utils/net/port.go
  vendor/modules.txt
Labels: approved, lgtm

#756 moves encryption controllers to apiservercontrollerset
  pkg/operator/apiserver/controllerset/apiservercontrollerset.go
  pkg/operator/encryption/controllers.go
Labels: approved, lgtm

#762 moves DeploymentNodeProvider
  pkg/operator/encryption/deployer/deploynodeprovider.go
Labels: approved, lgtm

#761 adds encryption.Provider
  pkg/operator/apiserver/controller/workload/workload.go
  pkg/operator/apiserver/controllerset/apiservercontrollerset.go
  pkg/operator/encryption/controllers.go
  pkg/operator/encryption/controllers/condition_controller.go
  pkg/operator/encryption/controllers/controller.go
  pkg/operator/encryption/controllers/helpers_test.go
  pkg/operator/encryption/controllers/key_controller.go
  pkg/operator/encryption/controllers/key_controller_test.go
  pkg/operator/encryption/controllers/migration_controller.go
  pkg/operator/encryption/controllers/migration_controller_test.go
  pkg/operator/encryption/controllers/prune_controller.go
  pkg/operator/encryption/controllers/prune_controller_test.go
  pkg/operator/encryption/controllers/state_controller.go
  pkg/operator/encryption/controllers/state_controller_test.go
  test/e2e-encryption/encryption_test.go
Labels: approved, lgtm

#755 apiserver: add prefix to tls and cors observers
  pkg/operator/configobserver/apiserver/observe_cors_test.go
  pkg/operator/configobserver/config_observer_controller.go
  pkg/operator/configobserver/config_observer_controller_test.go
Labels: approved, lgtm

#759 Fix StorageClasses comparison
  pkg/operator/resource/resourceapply/storage.go
  pkg/operator/resource/resourceapply/storage_test.go
Labels: approved, lgtm
