Repository openshift/library-go, pull requests merged in 2020-07, with the labels that each got.

#822 [release-4.2] Bug 1799079: Add resource requests to pruner and installer pod
  pkg/operator/staticpod/controller/installer/bindata/bindata.go
  pkg/operator/staticpod/controller/installer/manifests/installer-pod.yaml
  pkg/operator/staticpod/controller/prune/bindata/bindata.go
  pkg/operator/staticpod/controller/prune/manifests/pruner-pod.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#830 use a hostname in leader election id so we can the leaseholder
  pkg/config/leaderelection/leaderelection.go
Labels: approved, lgtm

#832 factory: handle panic in sync
  pkg/controller/controllercmd/builder.go
  pkg/controller/factory/base_controller.go
Labels: approved, lgtm

#816 Add Config Observers for OAuth Token Config
  go.mod
  go.sum
  pkg/operator/configobserver/oauth/observe_tokenconfig.go
  pkg/operator/configobserver/oauth/observe_tokenconfig_test.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_build.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/types_imagepruner.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/register.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/types_storage.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/osin/v1/types.go
  vendor/github.com/openshift/api/osin/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm

#834 loglevel: allow to override the default log level
  pkg/operator/loglevel/logging_controller.go
  pkg/operator/loglevel/logging_controller_test.go
Labels: approved, lgtm

#835 eventwatch: allow to match reason substring
  pkg/operator/eventwatch/controller.go
  pkg/operator/eventwatch/controller_test.go
  pkg/operator/eventwatch/glob.go
Labels: approved, lgtm

#829 CSI: add controllers for CSI operators
  pkg/operator/csi/credentialsrequestcontroller/credentials_request_controller.go
  pkg/operator/csi/credentialsrequestcontroller/credentials_request_controller_test.go
  pkg/operator/csi/csicontrollerset/csi_controller_set.go
  pkg/operator/csi/csidrivercontroller/csi_driver_controller.go
  pkg/operator/csi/csidrivercontroller/csi_driver_controller_test.go
  pkg/operator/csi/csidrivercontroller/sync.go
  pkg/operator/resource/resourceapply/credentialsrequest.go
  pkg/operator/resource/resourceread/credentialsrequest.go
  pkg/operator/resource/resourceread/credentialsrequest_test.go
Labels: approved, lgtm

#838 csi: fix startup of controllers in controllerset
  pkg/operator/csi/csicontrollerset/csi_controller_set.go
Labels: approved, lgtm

#833 configobserver/cloudprovider: support cluster-config-operator
  pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
  pkg/operator/configobserver/cloudprovider/observe_cloudprovider_test.go
Labels: approved, lgtm

#797 update ApplySecret to handle StringData
  pkg/operator/resource/resourceapply/core.go
Labels: approved, lgtm

#840 Fix ApplySecret with stringData
  pkg/operator/resource/resourceapply/core.go
Labels: approved, lgtm

#839 move the etcd config observer to library-go
  pkg/operator/configobserver/apiserver/listers.go
  pkg/operator/configobserver/apiserver/listers_test.go
  pkg/operator/configobserver/apiserver/observe_cors_test.go
  pkg/operator/configobserver/apiserver/observe_tlssecurityprofile.go
  pkg/operator/configobserver/apiserver/observe_tlssecurityprofile_test.go
  pkg/operator/configobserver/etcd/OWNERS
  pkg/operator/configobserver/etcd/listers.go
  pkg/operator/configobserver/etcd/listers_test.go
  pkg/operator/configobserver/etcd/observe_etcd_endpoints.go
  pkg/operator/configobserver/etcd/observe_etcd_endpoints_test.go
Labels: approved, lgtm

#841 NewNestedConfigObserver controller
  pkg/operator/configobserver/config_observer_controller.go
  pkg/operator/configobserver/config_observer_controller_test.go
Labels: approved, lgtm

#846 Add prune controller to the APIServerControllerSet
  pkg/operator/apiserver/controllerset/apiservercontrollerset.go
  pkg/operator/secretspruner/prune_controller.go
  pkg/operator/secretspruner/prune_controller_test.go
Labels: approved, lgtm

#847 CSI: Accept custom instance name
  pkg/operator/csi/csicontrollerset/csi_controller_set.go
  pkg/operator/csi/csidrivercontroller/csi_driver_controller.go
  pkg/operator/csi/csidrivercontroller/csi_driver_controller_test.go
  pkg/operator/genericoperatorclient/dynamic_operator_client.go
Labels: approved, lgtm

#850 Fixed PostStartHook execution
  pkg/controller/factory/factory.go
Labels: approved, lgtm

#842 Make unionCondition public
  pkg/operator/status/condition.go
  pkg/operator/status/status_controller.go
Labels: approved, lgtm

#853 dockerv1client: fix conversions
  pkg/image/dockerv1client/client.go
  pkg/image/dockerv1client/client_test.go
Labels: approved, lgtm

#845 Audit policy config observer
  go.mod
  go.sum
  pkg/operator/configobserver/apiserver/observe_audit.go
  pkg/operator/configobserver/apiserver/observe_audit_test.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-merge-patch
  vendor/github.com/openshift/api/operator/v1/register.go
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm

#851 add configobserver for the master url arg for kcm and ks
  pkg/operator/configobserver/masterurl/observe_masterurl.go
  pkg/operator/configobserver/masterurl/observe_masterurl_test.go
Labels: approved, lgtm

#849 adds missing tests for ApplyDeployment and ApplyDeploymentWithForce
  pkg/operator/resource/resourceapply/apps_test.go
Labels: approved, lgtm

#856 tweak EnsureAtMostOnePodPerNode method
  go.mod
  pkg/operator/apiserver/controller/workload/workload.go
Labels: approved, lgtm

#857 fix the static pod operator client
  pkg/operator/genericoperatorclient/dynamic_staticpod_operator_client.go
Labels: approved, lgtm

#623 encryption-e2e: retry on golang net errors
  test/library/encryption/errors.go
Labels: approved, lgtm, size/S

#859 Add audit policy path getter
  pkg/operator/apiserver/audit/audit_policies.go
  pkg/operator/apiserver/audit/audit_policies_test.go
Labels: approved, lgtm

#860 tweaks audit policies
  pkg/operator/apiserver/audit/audit_policies.go
  pkg/operator/apiserver/audit/audit_policies_test.go
  pkg/operator/apiserver/audit/bindata/bindata.go
  pkg/operator/apiserver/audit/manifests/audit-policies-cm.yaml
Labels: approved, lgtm
