Repository openshift/library-go, pull requests merged in 2020-06, with the labels that each got.

#808 factory: add mechanism to allow synthetic requeue without error
  pkg/controller/factory/base_controller.go
  pkg/operator/revisioncontroller/revision_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
Labels: approved, lgtm

#809 pkg/operator/render: grammar fixes
  pkg/operator/render/options/generic.go
Labels: approved, lgtm

#810 Add simple cron based scheduler to controller factory
  go.mod
  go.sum
  pkg/controller/factory/base_controller.go
  pkg/controller/factory/factory.go
  pkg/controller/factory/factory_test.go
  vendor/github.com/robfig/cron/v3/.gitignore
  vendor/github.com/robfig/cron/v3/.travis.yml
  vendor/github.com/robfig/cron/v3/LICENSE
  vendor/github.com/robfig/cron/v3/README.md
  vendor/github.com/robfig/cron/v3/chain.go
  vendor/github.com/robfig/cron/v3/constantdelay.go
  vendor/github.com/robfig/cron/v3/cron.go
  vendor/github.com/robfig/cron/v3/doc.go
  vendor/github.com/robfig/cron/v3/go.mod
  vendor/github.com/robfig/cron/v3/logger.go
  vendor/github.com/robfig/cron/v3/option.go
  vendor/github.com/robfig/cron/v3/parser.go
  vendor/github.com/robfig/cron/v3/spec.go
  vendor/modules.txt
Labels: approved, lgtm

#811 allow disabling leader election in ControllerCommandConfig
  pkg/controller/controllercmd/cmd.go
Labels: approved, lgtm

#767 reaper: Add a periodic reaper funcion
  pkg/proc/proc.go
  pkg/proc/proc_linux.go
  pkg/proc/reaper.go
Labels: approved, lgtm

#813 encryption-tests: log an error while waiting for the migration controller
  test/library/encryption/e_log.go
  test/library/encryption/perf_helpers.go
Labels: approved, lgtm

#814 factory: allow multiple scheduled times for sync
  pkg/controller/factory/base_controller.go
  pkg/controller/factory/factory.go
Labels: approved, lgtm

#815 Handle storage types in staticresourcecontroller
  pkg/operator/resource/resourceapply/generic.go
  pkg/operator/resource/resourceapply/storage.go
  pkg/operator/staticresourcecontroller/static_resource_controller.go
Labels: approved, lgtm

#818 eventwatch: add controller
  pkg/operator/eventwatch/controller.go
  pkg/operator/eventwatch/controller_test.go
Labels: approved, lgtm

#817 operatorclient: add metadata methods to interface
  pkg/operator/configobserver/config_observer_controller_test.go
  pkg/operator/genericoperatorclient/dynamic_operator_client.go
  pkg/operator/management/management_state_controller_test.go
  pkg/operator/status/status_controller_test.go
  pkg/operator/v1helpers/interfaces.go
  pkg/operator/v1helpers/test_helpers.go
Labels: approved, lgtm

#821 [release-4.3] Bug 1848583: Add resource requests to pruner pod
  pkg/operator/staticpod/controller/installer/bindata/bindata.go
  pkg/operator/staticpod/controller/installer/manifests/installer-pod.yaml
  pkg/operator/staticpod/controller/prune/bindata/bindata.go
  pkg/operator/staticpod/controller/prune/manifests/pruner-pod.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#823 eventwatch: process events with increasing counter
  pkg/operator/eventwatch/controller.go
  pkg/operator/eventwatch/controller_test.go
Labels: approved, lgtm

#824 proc: fix build error on non-linux platforms
  pkg/proc/proc.go
Labels: approved, lgtm

#825 Bug 1845766: Add status code to ErrNotV2Registry
  pkg/image/registryclient/client.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#826 Add helpers for service node port range configuration
  go.mod
  go.sum
  pkg/operator/configobserver/network/observe_network.go
  pkg/operator/configobserver/network/observe_networking_test.go
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/OWNERS
  vendor/github.com/openshift/api/build/v1/generated.pb.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_network.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_scheduler.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/01-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/types_imagepruner.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/install.go
  vendor/github.com/openshift/api/operator/v1/0000_20_etcd-operator_01.crd.yaml
  vendor/github.com/openshift/api/operatorcontrolplane/install.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/0000_10-pod-network-connectivity-check.crd.yaml
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/doc.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/register.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/types_conditioncheck.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm
