Repository openshift/library-go, pull requests merged in 2021-06, with the labels that each got.

#1083 Bug 1965929: add a CSR approving controller
  pkg/operator/csr/csr_approver.go
  pkg/operator/csr/csr_approver_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1093 csr: fix package name
  pkg/operator/csr/csr_approver.go
  pkg/operator/csr/csr_approver_test.go
Labels: approved, lgtm

#1082 add a simple client-cert controller for the single-cluster common case
  pkg/operator/csr/README.md
  pkg/operator/csr/cert_controller.go
  pkg/operator/csr/certificate.go
  pkg/operator/csr/certificate_test.go
  pkg/operator/csr/controller_test.go
  pkg/operator/csr/csrtestinghelpers/assertion.go
  pkg/operator/csr/csrtestinghelpers/testinghelpers.go
  pkg/operator/csr/simple_clientcert_controller.go
Labels: approved, lgtm

#1094 csr approver: filter incoming CSRs before entering sync()
  pkg/controller/factory/eventfilters.go
  pkg/operator/csr/csr_approver.go
  pkg/operator/csr/csr_approver_test.go
Labels: approved, lgtm

#1091 Bug 1907309: Add new StorageVersionMigration resourceapply
  go.mod
  go.sum
  pkg/operator/resource/resourceapply/generic.go
  pkg/operator/resource/resourceapply/migration.go
  pkg/operator/resource/resourceapply/migration_test.go
  pkg/operator/resource/resourceread/migration.go
  pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/modules.txt
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/fake/clientset_generated.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/fake/doc.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/fake/register.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/typed/migration/v1alpha1/fake/doc.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/typed/migration/v1alpha1/fake/fake_migration_client.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/typed/migration/v1alpha1/fake/fake_storagestate.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/typed/migration/v1alpha1/fake/fake_storageversionmigration.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1098 Bug 1963730: moves the cert directory under the target directory
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/installerpod/cmd.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1100 Bug 1946479: pkg/operator/staticpod/controller/installer,pruner: use manual SA mounts
  pkg/operator/staticpod/controller/installer/bindata/bindata.go
  pkg/operator/staticpod/controller/installer/manifests/installer-pod.yaml
  pkg/operator/staticpod/controller/prune/bindata/bindata.go
  pkg/operator/staticpod/controller/prune/manifests/pruner-pod.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1101 Bug 1963730: revert https://github.com/openshift/library-go/pull/1098
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/installerpod/cmd.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1097 Bug 1879182: make secure- and normal audit policies match
  pkg/operator/apiserver/audit/bindata/bindata.go
  pkg/operator/apiserver/audit/manifests/audit-policies-cm.yaml
  pkg/operator/apiserver/audit/testdata/audit-policies-cm-scenario-1.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1096 image/registryclient: set insecure and return early in blobMirroredRepository
  go.mod
  pkg/image/registryclient/client.go
  pkg/image/registryclient/client_mirrored.go
  pkg/image/registryclient/client_test.go
  pkg/operator/staticpod/installerpod/copy.go
  vendor/modules.txt
Labels: approved, lgtm

#1103 Bug 1963730: writes the dynamic certs atomically
  pkg/operator/staticpod/certsyncpod/certsync_controller.go
  pkg/operator/staticpod/controller/prune/prune_controller.go
  pkg/operator/staticpod/controller/prune/prune_controller_test.go
  pkg/operator/staticpod/controllers.go
  pkg/operator/staticpod/file_utils.go
  pkg/operator/staticpod/installerpod/cmd.go
  pkg/operator/staticpod/prune/cmd.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1108 Bug 1969631: encryption controllers wait for all informers before running the sync loops
  pkg/operator/encryption/controllers.go
  pkg/operator/encryption/controllers/condition_controller.go
  pkg/operator/encryption/controllers/migration_controller.go
  pkg/operator/encryption/controllers/migration_controller_test.go
  pkg/operator/encryption/controllers/prune_controller.go
  pkg/operator/encryption/controllers/prune_controller_test.go
  pkg/operator/encryption/controllers/state_controller.go
  pkg/operator/encryption/controllers/state_controller_test.go
  pkg/operator/encryption/preconditions.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1099 Bug 1961317: Adding static assets to related objects
  pkg/operator/staticresourcecontroller/static_resource_controller.go
  pkg/operator/staticresourcecontroller/static_resource_controller_test.go
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#1081 CSI: Unify assetFuncs for all controllers
  pkg/operator/csi/csicontrollerset/csi_controller_set.go
Labels: approved, lgtm

#1113 Migrate csi deployment to use generic deployment
  pkg/operator/csi/csicontrollerset/csi_controller_set.go
  pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller.go
  pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller_test.go
  pkg/operator/csi/csidrivercontrollerservicecontroller/helpers.go
  pkg/operator/csi/csidrivercontrollerservicecontroller/helpers_test.go
  pkg/operator/deploymentcontroller/deployment_controller.go
  pkg/operator/deploymentcontroller/deployment_controller_test.go
  pkg/operator/deploymentcontroller/helpers.go
  pkg/operator/deploymentcontroller/helpers_test.go
Labels: approved, lgtm

#1111 makes the apiservice controller more resilient to failures
  pkg/operator/apiserver/controller/apiservice/apigroup.go
Labels: approved, lgtm

#1117 DeploymentController: Do not overwrite manifest
  pkg/operator/deploymentcontroller/deployment_controller.go
Labels: approved, lgtm

#1114 apiserver/audit: split policy config map manifest into policy rule slices
  pkg/operator/apiserver/audit/audit_policies.go
  pkg/operator/apiserver/audit/audit_policies_test.go
  pkg/operator/apiserver/audit/bindata/bindata.go
  pkg/operator/apiserver/audit/legacy.go
  pkg/operator/apiserver/audit/legacy_test.go
  pkg/operator/apiserver/audit/manifests/allrequestbodies-rules.yaml
  pkg/operator/apiserver/audit/manifests/audit-policies-cm.yaml
  pkg/operator/apiserver/audit/manifests/base-policy.yaml
  pkg/operator/apiserver/audit/manifests/default-rules.yaml
  pkg/operator/apiserver/audit/manifests/writerequestbodies-rules.yaml
  pkg/operator/apiserver/audit/testdata/audit-policies-cm-scenario-1.yaml
  pkg/operator/resourcesynccontroller/resourcesync_controller_test.go
Labels: approved, lgtm

#1118 workload controller: delays reporting degraded condition when progressing > 15 minutes
  pkg/operator/apiserver/controller/workload/workload.go
  pkg/operator/apiserver/controller/workload/workload_test.go
Labels: approved, lgtm

#1121 Wire context properly to all resource apply helpers
  pkg/operator/apiserver/controller/apiservice/apiservice_controller.go
  pkg/operator/certrotation/cabundle.go
  pkg/operator/certrotation/cabundle_test.go
  pkg/operator/certrotation/client_cert_rotation_controller.go
  pkg/operator/certrotation/signer.go
  pkg/operator/certrotation/signer_test.go
  pkg/operator/certrotation/target.go
  pkg/operator/certrotation/target_test.go
  pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
  pkg/operator/csi/credentialsrequestcontroller/credentials_request_controller.go
  pkg/operator/csi/csidrivernodeservicecontroller/csi_driver_node_service_controller.go
  pkg/operator/deploymentcontroller/deployment_controller.go
  pkg/operator/encryption/controllers/migration_controller.go
  pkg/operator/encryption/controllers/state_controller.go
  pkg/operator/resource/resourceapply/admissionregistration.go
  pkg/operator/resource/resourceapply/admissionregistration_test.go
  pkg/operator/resource/resourceapply/apiextensions.go
  pkg/operator/resource/resourceapply/apiregistration.go
  pkg/operator/resource/resourceapply/apps.go
  pkg/operator/resource/resourceapply/apps_test.go
  pkg/operator/resource/resourceapply/core.go
  pkg/operator/resource/resourceapply/core_test.go
  pkg/operator/resource/resourceapply/credentialsrequest.go
  pkg/operator/resource/resourceapply/generic.go
  pkg/operator/resource/resourceapply/generic_test.go
  pkg/operator/resource/resourceapply/migration.go
  pkg/operator/resource/resourceapply/migration_test.go
  pkg/operator/resource/resourceapply/monitoring.go
  pkg/operator/resource/resourceapply/monitoring_test.go
  pkg/operator/resource/resourceapply/policy.go
  pkg/operator/resource/resourceapply/rbac.go
  pkg/operator/resource/resourceapply/storage.go
  pkg/operator/resource/resourceapply/storage_test.go
  pkg/operator/resource/resourceapply/unstructured.go
  pkg/operator/resource/resourceapply/volumesnapshotclass.go
  pkg/operator/resource/resourceapply/volumesnapshotclass_test.go
  pkg/operator/resourcesynccontroller/resourcesync_controller.go
  pkg/operator/revisioncontroller/revision_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
  pkg/operator/staticpod/controller/prune/prune_controller.go
  pkg/operator/staticpod/controller/prune/prune_controller_test.go
  pkg/operator/staticresourcecontroller/static_resource_controller.go
Labels: approved, lgtm

#1105 csr approver: choose between logging and status updates on errors
  pkg/operator/csr/csr_approver.go
Labels: approved, lgtm

#1115 apiserver: add audit policy controller
  pkg/operator/apiserver/controller/auditpolicy/auditpolicy_controller.go
  pkg/operator/apiserver/controllerset/apiservercontrollerset.go
Labels: approved, lgtm
