Repository openshift/library-go, pull requests merged in 2021-11, with the labels that each got.

#1224 fix registryclient Context.Copy
  pkg/image/registryclient/client.go
Labels: approved, lgtm

#1245 installerpod: skip installer pod UID generation when running on newer kubelets
  pkg/operator/staticpod/installerpod/cmd.go
  pkg/operator/staticpod/installerpod/cmd_test.go
Labels: approved, lgtm

#1142 operators: wire context properly to operator controllers
  pkg/controller/controllercmd/builder.go
  pkg/operator/apiserver/controller/apiservice/apigroup.go
  pkg/operator/apiserver/controller/apiservice/apiservice_controller.go
  pkg/operator/certrotation/client_cert_rotation_controller.go
  pkg/operator/certrotation/config.go
  pkg/operator/configobserver/config_observer_controller_test.go
  pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
  pkg/operator/deploymentcontroller/deployment_controller.go
  pkg/operator/encryption/controllers/condition_controller.go
  pkg/operator/encryption/controllers/key_controller.go
  pkg/operator/encryption/controllers/key_controller_test.go
  pkg/operator/encryption/controllers/migration_controller.go
  pkg/operator/encryption/controllers/migrators/inprocess.go
  pkg/operator/encryption/controllers/migrators/inprocess_processor.go
  pkg/operator/encryption/controllers/migrators/inprocess_processor_test.go
  pkg/operator/encryption/controllers/prune_controller.go
  pkg/operator/encryption/controllers/state_controller.go
  pkg/operator/encryption/deployer/revisionedpod.go
  pkg/operator/encryption/deployer/unionrevisionedpod.go
  pkg/operator/encryption/deployer/unionrevisionedpod_test.go
  pkg/operator/encryption/secrets/secrets.go
  pkg/operator/encryption/statemachine/transition.go
  pkg/operator/events/eventstesting/recorder_testing.go
  pkg/operator/events/eventstesting/recorder_wrapper.go
  pkg/operator/events/recorder.go
  pkg/operator/events/recorder_in_memory.go
  pkg/operator/events/recorder_logging.go
  pkg/operator/events/recorder_test.go
  pkg/operator/events/recorder_upstream.go
  pkg/operator/resource/resourcehash/as_configmap.go
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
  pkg/operator/staticpod/controller/prune/prune_controller.go
  pkg/operator/staticpod/controller/prune/prune_controller_test.go
  pkg/operator/staticpod/installerpod/cmd.go
  pkg/operator/v1helpers/test_helpers.go
  pkg/operator/watchdog/cmd.go
  test/e2e-encryption/encryption_test.go
Labels: approved, lgtm

#1243 Add conditional resource synchronization to the resource sync controller
  pkg/operator/apiserver/controllerset/apiservercontrollerset.go
  pkg/operator/encryption/controllers.go
  pkg/operator/encryption/controllers/key_controller_test.go
  pkg/operator/encryption/controllers/migration_controller_test.go
  pkg/operator/encryption/controllers/prune_controller_test.go
  pkg/operator/encryption/controllers/state_controller_test.go
  pkg/operator/encryption/deployer/revisionedpod.go
  pkg/operator/resourcesynccontroller/interfaces.go
  pkg/operator/resourcesynccontroller/resourcesync_controller.go
  pkg/operator/resourcesynccontroller/resourcesync_controller_test.go
  test/e2e-encryption/encryption_test.go
Labels: approved, lgtm

#1246 [poc] add conditional resources to the static resource controller
  pkg/operator/staticresourcecontroller/static_resource_controller.go
Labels: approved, lgtm

#1249 pkg: fix apiservice discovery context panic
  pkg/operator/apiserver/controller/apiservice/apigroup.go
Labels: approved, lgtm

#1255 bug 2026352: staticpod pruner: check if the cert directory exists
  pkg/operator/staticpod/prune/cmd.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1226 Bug 2008539: Try another registry if blob is not found
  pkg/image/registryclient/client_mirrored.go
  pkg/image/registryclient/client_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high
