Repository openshift/library-go, pull requests merged in 2021-05, with the labels that each got.

#1069 extends the maximum time the tests will wait for KAS to reach the same revision
  test/library/apiserver/apiserver.go
Labels: approved, lgtm

#1072 changes mustSucceedMultipleTimes to sleep before each invocation the given timeout
  test/library/pod_same_revision.go
Labels: approved, lgtm

#1075 staticpod: recreate existing pod manifests instead of updating
  pkg/operator/staticpod/installerpod/cmd.go
Labels: approved, lgtm

#1076 Bug 1943804: increases the maximum time for migration for the encryption tests on AWS
  test/library/encryption/e_log.go
  test/library/encryption/helpers.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1067 Add resourceApply for VolumeSnapshotClass
  pkg/operator/resource/resourceapply/unstructured.go
  pkg/operator/resource/resourceapply/volumesnapshotclass.go
  pkg/operator/resource/resourceapply/volumesnapshotclass_test.go
Labels: approved, lgtm

#1074 CSI: allow to set dynamic client to static resource controller
  pkg/operator/csi/csicontrollerset/csi_controller_set.go
Labels: approved, lgtm

#1078 Bug 1960758: New helper for oc adm must-gather / oc debug
  pkg/image/imageutil/helpers.go
  pkg/image/imageutil/helpers_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1089 staticpod: remove misuse of RevisionResource type
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
  pkg/operator/staticpod/controllers.go
Labels: approved, lgtm

#1056 Bug 1947402: csi: add hook to set Deployment replicas according to numbe of master nodes
  pkg/operator/csi/csicontrollerset/csi_controller_set.go
  pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller.go
  pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller_test.go
  pkg/operator/csi/csidrivercontrollerservicecontroller/helpers.go
  pkg/operator/csi/csidrivercontrollerservicecontroller/helpers_test.go
  pkg/operator/csi/csidrivernodeservicecontroller/csi_driver_node_service_controller.go
  pkg/operator/csi/csidrivernodeservicecontroller/csi_driver_node_service_controller_test.go
  pkg/operator/resource/resourceapply/generic.go
  pkg/operator/resource/resourceapply/policy.go
  pkg/operator/resource/resourceread/policy.go
  pkg/operator/staticresourcecontroller/static_resource_controller.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1090 staticpod: fix cert sync controller types to be unrevisioned
  pkg/operator/staticpod/certsyncpod/certsync_cmd.go
  pkg/operator/staticpod/certsyncpod/certsync_controller.go
Labels: approved, lgtm
