Repository openshift/library-go, pull requests merged in 2021-08, with the labels that each got.

#1169 Bug 1984942: ApplyClusterRoleBinding triggers boundsError when adding new subject
  pkg/operator/resource/resourceapply/rbac.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1174 staticpod/startup-monitor: return readiness correctly on last iteration
  pkg/operator/staticpod/startupmonitor/cmd.go
  pkg/operator/staticpod/startupmonitor/monitor.go
Labels: approved, lgtm

#1172 staticpod/installer: skip backoff if lastAvailableRevision > targetRevision
  pkg/operator/staticpod/controller/installer/installer_controller.go
Labels: approved, lgtm

#1175 staticPodFallbackConditionController handles multiple pods returned from the API server
  pkg/operator/staticpod/controller/staticpodfallback/static_pod_fallback_condition.go
  pkg/operator/staticpod/controller/staticpodfallback/static_pod_fallback_condition_test.go
Labels: approved, lgtm

#1176 startupMonitorPodConditionController: gets the progressing node name to find a potential startup monitor pod
  pkg/operator/staticpod/controller/startupmonitorcondition/startup_monitor_condition.go
  pkg/operator/staticpod/controller/startupmonitorcondition/startup_monitor_condition_test.go
Labels: approved, lgtm

#1179 Bug 1991357: installer_controller: only degraded if lastFailedRevision > currentRe…
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#1182 deflake TestStaticPodFallbackConditionController
  pkg/operator/staticpod/controller/staticpodfallback/static_pod_fallback_condition_test.go
Labels: approved, lgtm

#1140 Bug 1987025: CSI driver controller: modify nodeselector based on control plane topology
  pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller.go
  pkg/operator/csi/csidrivercontrollerservicecontroller/helpers.go
  pkg/operator/csi/csidrivercontrollerservicecontroller/helpers_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1180 Bug 1993800: staticpod/installer: fix backoff of installers
  pkg/operator/revisioncontroller/revision_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#1192 csi: Replace leader-election parameters
  pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller.go
  pkg/operator/csi/csidrivercontrollerservicecontroller/helpers.go
  pkg/operator/csi/csidrivercontrollerservicecontroller/helpers_test.go
Labels: approved, lgtm

#1194 Bug 1986003: bump(k8s.io/*): v0.22.1
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/go.sum
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/images.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/kustomize.mk
  vendor/github.com/sirupsen/logrus/.travis.yml
  vendor/github.com/sirupsen/logrus/CHANGELOG.md
  vendor/github.com/sirupsen/logrus/README.md
  vendor/github.com/sirupsen/logrus/entry.go
  vendor/github.com/sirupsen/logrus/go.sum
  vendor/github.com/sirupsen/logrus/json_formatter.go
  vendor/github.com/sirupsen/logrus/logger.go
  vendor/github.com/sirupsen/logrus/terminal_check_unix.go
  vendor/github.com/sirupsen/logrus/text_formatter.go
  vendor/golang.org/x/time/rate/rate.go
  vendor/k8s.io/apiserver/pkg/admission/metrics/metrics.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/mutating/dispatcher.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/validating/dispatcher.go
  vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
  vendor/k8s.io/apiserver/pkg/server/deprecated_insecure_serving.go
  vendor/k8s.io/apiserver/pkg/server/options/audit.go
  vendor/k8s.io/apiserver/pkg/server/secure_serving.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/store.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high
