Repository openshift/library-go, pull requests merged in 2021-02, with the labels that each got.

#981 csi: add some unit tests to code added recently
  pkg/operator/csi/csiconfigobservercontroller/csi_config_observer_controller_test.go
  pkg/operator/csi/csidrivercontrollerservicecontroller/helpers_test.go
  pkg/operator/csi/csidrivernodeservicecontroller/helpers_test.go
  pkg/operator/v1helpers/test_helpers.go
Labels: approved, lgtm

#986 Bug 1915467: cherry-pick hooks helpers and config observer
  pkg/operator/csi/csiconfigobservercontroller/csi_config_observer_controller.go
  pkg/operator/csi/csicontrollerset/csi_controller_set.go
  pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller.go
  pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller_test.go
  pkg/operator/csi/csidrivercontrollerservicecontroller/helpers.go
  pkg/operator/csi/csidrivernodeservicecontroller/csi_driver_node_service_controller.go
  pkg/operator/csi/csidrivernodeservicecontroller/csi_driver_node_service_controller_test.go
  pkg/operator/csi/csidrivernodeservicecontroller/helpers.go
  pkg/operator/v1helpers/helpers.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#987 Bug 1912820: competing connectivitycheckcontrollers cause pod restarts during upgrades
  pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
  pkg/operator/resource/resourceapply/admissionregistration_test.go
  pkg/operator/resource/resourceapply/generic.go
  pkg/operator/resource/resourceread/admission.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#992 provides a static encryption provider
  pkg/operator/encryption/static_provider.go
Labels: approved, lgtm

#993 Add IsCloudProviderExternal helper for operators
  pkg/cloudprovider/external.go
  pkg/cloudprovider/external_test.go
Labels: approved, lgtm

#996 Allow SCC to be created during bootstrapping
  pkg/assets/create/creater.go
  pkg/client/openshiftrestmapper/hardcoded_restmapper.go
Labels: approved, lgtm

#989 serviceability: Remove Sentry
  go.mod
  go.sum
  pkg/serviceability/panic.go
  pkg/serviceability/sentry.go
  vendor/github.com/certifi/gocertifi/LICENSE
  vendor/github.com/certifi/gocertifi/README.md
  vendor/github.com/certifi/gocertifi/certifi.go
  vendor/github.com/getsentry/raven-go/.dockerignore
  vendor/github.com/getsentry/raven-go/.gitignore
  vendor/github.com/getsentry/raven-go/.gitmodules
  vendor/github.com/getsentry/raven-go/.travis.yml
  vendor/github.com/getsentry/raven-go/Dockerfile.test
  vendor/github.com/getsentry/raven-go/LICENSE
  vendor/github.com/getsentry/raven-go/README.md
  vendor/github.com/getsentry/raven-go/client.go
  vendor/github.com/getsentry/raven-go/errors.go
  vendor/github.com/getsentry/raven-go/exception.go
  vendor/github.com/getsentry/raven-go/http.go
  vendor/github.com/getsentry/raven-go/interfaces.go
  vendor/github.com/getsentry/raven-go/runtests.sh
  vendor/github.com/getsentry/raven-go/stacktrace.go
  vendor/github.com/getsentry/raven-go/writer.go
  vendor/modules.txt
Labels: approved, lgtm

#998 add hardcoded authorizers for metrics and token reviews
  pkg/authorization/hardcodedauthorizer/metrics.go
  pkg/authorization/hardcodedauthorizer/metrics_test.go
  pkg/controller/controllercmd/builder.go
Labels: approved, lgtm

#997 use the controllerfactory in the workloadcontroller
  pkg/operator/apiserver/controller/workload/workload.go
  pkg/operator/apiserver/controller/workload/workload_test.go
  pkg/operator/apiserver/controllerset/apiservercontrollerset.go
Labels: approved, lgtm
