Repository openshift/library-go, pull requests merged in 2021-04, with the labels that each got.

#1025 add Default Audit Policy getter function
  pkg/operator/apiserver/audit/audit_policies.go
  pkg/operator/apiserver/audit/audit_policies_test.go
Labels: approved, lgtm

#1030 provides CancelRequest method for the PreferredHost RoundTripper to facilitate cancellation
  pkg/config/client/transport.go
Labels: approved, lgtm

#1042 Sync ServiceMonitors in CSI controller set
  pkg/operator/csi/csicontrollerset/csi_controller_set.go
  pkg/operator/resource/resourceapply/generic.go
  pkg/operator/resource/resourceapply/monitoring.go
  pkg/operator/resource/resourceapply/monitoring_test.go
  pkg/operator/resource/resourceapply/unstructured.go
  pkg/operator/resource/resourceread/unstructured.go
  pkg/operator/resource/resourceread/unstructured_test.go
  pkg/operator/staticresourcecontroller/static_resource_controller.go
Labels: approved, lgtm

#1020 shell args
  pkg/operator/v1helpers/args.go
  pkg/operator/v1helpers/args_test.go
Labels: approved, lgtm

#1048 static-pods: always set installer reason string
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
Labels: approved, lgtm

#1045 static-pods: allow fast-forward to next revision with pending installer
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
Labels: approved, lgtm

#1049 Bug 1917129: static-pods: no MissingVersion event as long as there are no known nodes yet
  pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1050 Add ${KUBE_RBAC_PROXY_IMAGE} replacer to CSI driver controller
  pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller.go
  pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller_test.go
  pkg/operator/csi/csidrivernodeservicecontroller/csi_driver_node_service_controller.go
Labels: approved, lgtm

#1051 allow static resource controller to set degraded on panic
  pkg/controller/factory/base_controller.go
Labels: approved, lgtm

#1052 add revision reason to status configmaps
  pkg/operator/revisioncontroller/revision_controller.go
Labels: approved, lgtm

#1053 add resourceApply for prometheus rule
  pkg/operator/resource/resourceapply/monitoring.go
  pkg/operator/resource/resourceapply/unstructured.go
Labels: approved, lgtm

#1064 bug 1953798: stop doing live gets for optional cert syncer files that don't exist on disk yet
  pkg/operator/staticpod/certsyncpod/certsync_controller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1065 bug 1955226: update CRD apply to understand some fields are defaulted
  pkg/operator/resource/resourcemerge/apiextensions.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
