Repository openshift/library-go, pull requests merged in 2022-10, with the labels that each got.

#1403 Add milestone logging to investigate PodNotReady failures
  pkg/operator/staticpod/installerpod/cmd.go
Labels: approved, lgtm

#1406 OCPBUGS-2125: pkg/manifest/manifest.go: add option to allow unknown capabilities
  pkg/manifest/manifest.go
  pkg/manifest/manifest_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-important, jira/valid-bug

#1402 Make request using correct namespace
  pkg/template/templateprocessingclient/dynamic_process.go
Labels: approved, lgtm

#1404 OCPBUGS-1904: add new ConditionalStaticResourcesController
  pkg/operator/csi/csicontrollerset/csi_controller_set.go
  pkg/operator/staticresourcecontroller/static_resource_controller.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-critical, jira/valid-bug

#1408 update to release.openshift.io/feature-set to match OCP 4.12
  pkg/manifest/manifest.go
  pkg/manifest/manifest_test.go
Labels: approved, lgtm

#1409 OCPBUGS-2293: pkg/manifest/manifest.go: add option to allow unknown capabilities
  pkg/manifest/manifest.go
  pkg/manifest/manifest_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-important, jira/valid-bug

#1405 lower timeout to increase retries
  pkg/operator/staticpod/installerpod/cmd.go
Labels: approved, lgtm

#1412 Check for nil pointer before checking connectivity
  pkg/config/serving/server.go
Labels: approved, lgtm
