Repository openshift/library-go, pull requests merged in 2022-01, with the labels that each got.

#1275 Bug 2037274: [crypto,transport]/missing_san: verify invalid certificates
  pkg/crypto/missing_san.go
  pkg/crypto/missing_san_test.go
  pkg/transport/missing_san_roundtripper.go
  pkg/transport/missing_san_roundtripper_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#1278 Bug 2037274: pkg/security/ldapclient: add configuration for connection verification
  pkg/security/OWNERS
  pkg/security/ldapclient/client.go
Labels: approved, lgtm

#1280 pkg/security/OWNERS: add auth team
  pkg/security/OWNERS
Labels: approved, lgtm

#1281 bug 2005901: staticpod builder: initialize operand label selector separately
  pkg/operator/staticpod/controller/guard/guard_controller.go
  pkg/operator/staticpod/controller/guard/guard_controller_test.go
  pkg/operator/staticpod/controllers.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#1283 Bug 2037274: metrics controller
  go.mod
  pkg/operator/metricscontroller/legacy_cn_certs_sync.go
  pkg/operator/metricscontroller/legacy_cn_certs_sync_test.go
  pkg/operator/metricscontroller/metrics_controller.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#1279 [release-4.9] Bug 2029571: csi: add hook to inject custom CA bundle
  pkg/operator/csi/csidrivercontrollerservicecontroller/helpers.go
  pkg/operator/csi/csidrivernodeservicecontroller/helpers.go
  pkg/operator/v1helpers/helpers.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1285 rely on client interfaces for prometheus client
  test/library/metrics/query.go
Labels: approved, lgtm

#1284 Bug 2031839: metricscontroller: handle empty vector query result
  pkg/operator/metricscontroller/legacy_cn_certs_sync.go
  pkg/operator/metricscontroller/legacy_cn_certs_sync_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#1282 Bug 2037856: use 'configmapsleases' based leader election
  pkg/config/leaderelection/leaderelection.go
  pkg/controller/controllercmd/builder.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#1274 Add precondition to the StaticResourceController
  pkg/operator/staticresourcecontroller/static_resource_controller.go
Labels: approved, lgtm

#1288 audit: use API to drop managed fields
  pkg/operator/apiserver/audit/bindata/bindata.go
  pkg/operator/apiserver/audit/manifests/base-policy.yaml
  pkg/operator/apiserver/audit/testdata/allrequestbodies.yaml
  pkg/operator/apiserver/audit/testdata/audit-policies-cm-scenario-1.yaml
  pkg/operator/apiserver/audit/testdata/default.yaml
  pkg/operator/apiserver/audit/testdata/multipleCr.yaml
  pkg/operator/apiserver/audit/testdata/none.yaml
  pkg/operator/apiserver/audit/testdata/oauth.yaml
  pkg/operator/apiserver/audit/testdata/writerequestbodies.yaml
Labels: approved, lgtm

#1287 bug 2005901: guard controller: create the pdb if it does not exist
  pkg/operator/staticpod/controller/guard/guard_controller.go
  pkg/operator/staticpod/controller/guard/guard_controller_test.go
  pkg/operator/staticpod/controllers.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#1289 Bug 2037274: pkg/operator/metricscontroller: add prefix, support vector results
  pkg/operator/metricscontroller/legacy_cn_certs_sync.go
  pkg/operator/metricscontroller/legacy_cn_certs_sync_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#1290 Bug 2031839: pkg/operator/metricscontroller: remove legacy CN sync function
  go.mod
  pkg/operator/metricscontroller/legacy_cn_certs_sync.go
  pkg/operator/metricscontroller/legacy_cn_certs_sync_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#1294 need to store the passed value to the apply cache for later compariso…
  pkg/operator/resource/resourceapply/admissionregistration.go
  pkg/operator/resource/resourceapply/admissionregistration_test.go
Labels: approved, lgtm

#1292 Fix typo in StaticResourceController
  pkg/operator/staticresourcecontroller/static_resource_controller.go
Labels: approved, lgtm

#1297 Add dmage and myself for pkg/image approvers, and myself to pkg/operator
  pkg/image/OWNERS
  pkg/operator/OWNERS
Labels: approved, lgtm

#1299 staticpodcontroller: refactor ToControllers() method to be less error prone
  pkg/operator/staticpod/controller/guard/guard_controller.go
  pkg/operator/staticpod/controller/staticpodfallback/static_pod_fallback_condition.go
  pkg/operator/staticpod/controllers.go
Labels: approved, lgtm

#1300 wait for other installers to finish
  pkg/operator/staticpod/installerpod/cmd.go
Labels: approved, lgtm

#1301 add a check for the installer container status to be posted
  pkg/operator/staticpod/installerpod/cmd.go
Labels: approved, lgtm
