Repository openshift/library-go, pull requests merged in 2022-08, with the labels that each got.

#1384 Bug 2108054: Add ReadGenericWithUnstructured
  pkg/operator/resource/resourceapply/generic.go
  pkg/operator/resource/resourceapply/generic_test.go
  pkg/operator/resource/resourceread/generic.go
  pkg/operator/resource/resourceread/generic_test.go
  pkg/operator/staticresourcecontroller/static_resource_controller.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#1385 Add soltysh as approver
  OWNERS
Labels: approved, lgtm

#1381 Switch from k8s.io/apimachinery/pkg/util/clock to k8s.io/utils/clock
  pkg/operator/onepodpernodeccontroller/onepodpernode_controller.go
  pkg/operator/onepodpernodeccontroller/onepodpernode_controller_test.go
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
  vendor/k8s.io/apimachinery/pkg/util/clock/clock.go
  vendor/modules.txt
Labels: approved, lgtm

#1387 update manifest selection to allow Default and TechPreview for releas…
  pkg/manifest/manifest.go
  pkg/manifest/manifest_test.go
Labels: approved, lgtm

#1276 Bug 2000276: EncryptionStateControllerDegraded: failed to get converged static pod revision
  pkg/operator/encryption/deployer/revisionedpod.go
  pkg/operator/encryption/deployer/revisionedpod_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1392 Fix Services informer in StaticResourceController
  pkg/operator/staticresourcecontroller/static_resource_controller.go
Labels: approved, lgtm

#1388 Ldap: Respect ALL_PROXY when dialing
  go.mod
  pkg/security/ldapclient/client.go
  pkg/security/ldapclient/client_test.go
  vendor/golang.org/x/net/internal/socks/client.go
  vendor/golang.org/x/net/internal/socks/socks.go
  vendor/golang.org/x/net/proxy/dial.go
  vendor/golang.org/x/net/proxy/direct.go
  vendor/golang.org/x/net/proxy/per_host.go
  vendor/golang.org/x/net/proxy/proxy.go
  vendor/golang.org/x/net/proxy/socks5.go
  vendor/modules.txt
Labels: approved, lgtm
