Repository openshift/library-go, pull requests merged in 2022-11, with the labels that each got.

#1407 Copy route validation and defaulting bits from openshift-apiserver.
  pkg/route/hostassignment/assignment.go
  pkg/route/hostassignment/assignment_test.go
  pkg/route/hostassignment/plugin.go
  pkg/route/hostassignment/plugin_test.go
  pkg/route/validation/validation.go
  pkg/route/validation/validation_test.go
Labels: approved, lgtm

#1413 OCPBUGS-2083: set default list of TLS ciphers for Kube RBAC sidecars
  pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller.go
  pkg/operator/csi/csidrivercontrollerservicecontroller/helpers.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug

#1419 Add additional approvers to the staticpod library
  pkg/operator/staticpod/OWNERS
Labels: approved, lgtm

#1395 Installer static controller: be more forgiving and consider only recent installer pods
  pkg/operator/staticpod/controller/installerstate/installer_state_controller.go
  pkg/operator/staticpod/controller/installerstate/installer_state_controller_test.go
Labels: approved, lgtm

#1423 pkg/crypto: add stlaz as approver/reviewer
  pkg/crypto/OWNERS
Labels: approved, lgtm

#1421 OCPBUGS-3123: add --feature-set option to render options
  pkg/assets/assets.go
  pkg/assets/assets_test.go
  pkg/assets/create/create_test.go
  pkg/operator/render/options/generic.go
  pkg/operator/render/render.go
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, jira/severity-important, jira/valid-bug

#1428 move the featureset detection for rendering after substitution so the…
  pkg/assets/assets.go
  pkg/assets/assets_test.go
  pkg/operator/render/render.go
Labels: approved, lgtm

#1429 Revert "Make request using correct namespace"
  pkg/template/templateprocessingclient/dynamic_process.go
Labels: approved, lgtm

#1431 Revert "Merge pull request #1429 from vrutkovs/revert-1402-master"
  pkg/template/templateprocessingclient/dynamic_process.go
Labels: approved, lgtm

#1422 USHIFT-573 Regenerate client certificate on subject change
  pkg/crypto/crypto.go
  pkg/crypto/crypto_test.go
Labels: approved, lgtm

#1427 OCPBUGS-3041: guard controller: set an explicit hostname to avoid name collisions
  pkg/operator/staticpod/controller/guard/guard_controller.go
  pkg/operator/staticpod/controller/guard/guard_controller_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-important, jira/valid-bug

#1391 Add Nutanix as an external cloud provider platform
  pkg/cloudprovider/external.go
  pkg/cloudprovider/external_test.go
  pkg/operator/configobserver/cloudprovider/observe_cloudprovider_test.go
Labels: approved, lgtm

#1410 STOR-1055: Add CSIDriver verification check in library-go
  pkg/operator/resource/resourceapply/storage.go
  pkg/operator/resource/resourceapply/storage_test.go
Labels: approved, lgtm, px-approved, qe-approved, docs-approved

#1434 assign template namespace to default if not set
  pkg/template/templateprocessingclient/dynamic_process.go
Labels: approved, lgtm
