Repository openshift/library-go, pull requests merged in 2022-03, with the labels that each got.

#1325 Add support for batch/v1 CronJob
  pkg/image/referencemutator/pods.go
Labels: approved, lgtm

#1324 Recreate CSIDriver on change
  pkg/operator/resource/resourceapply/storage.go
  pkg/operator/resource/resourceapply/storage_test.go
Labels: approved, lgtm

#1305 migrate bindata to go embed
  Makefile
  pkg/operator/apiserver/audit/audit_policies.go
  pkg/operator/apiserver/audit/audit_policies_test.go
  pkg/operator/apiserver/audit/bindata/bindata.go
  pkg/operator/connectivitycheckcontroller/Makefile
  pkg/operator/connectivitycheckcontroller/bindata/bindata.go
  pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
  pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
  pkg/operator/staticpod/controller/backingresource/bindata/bindata.go
  pkg/operator/staticpod/controller/guard/bindata/bindata.go
  pkg/operator/staticpod/controller/guard/guard_controller.go
  pkg/operator/staticpod/controller/installer/bindata/bindata.go
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/prune/bindata/bindata.go
  pkg/operator/staticpod/controller/prune/prune_controller.go
Labels: approved, lgtm

#1327 Bugzilla 2063342: audit/manifests: exclude tokenreviews and tokenrequests from audit logs
  pkg/operator/apiserver/audit/manifests/allrequestbodies-rules.yaml
  pkg/operator/apiserver/audit/manifests/writerequestbodies-rules.yaml
  pkg/operator/apiserver/audit/testdata/allrequestbodies.yaml
  pkg/operator/apiserver/audit/testdata/multipleCr.yaml
  pkg/operator/apiserver/audit/testdata/oauth.yaml
  pkg/operator/apiserver/audit/testdata/writerequestbodies.yaml
Labels: approved, lgtm

#1329 Extend rest mappings with job definition
  pkg/client/openshiftrestmapper/hardcoded_restmapper.go
Labels: approved, lgtm, ok-to-test

#1328 Bug 2049671: resourcesynccontroller: avoid requests to non-existent target
  pkg/operator/resource/resourceapply/core.go
  pkg/operator/resourcesynccontroller/resourcesync_controller.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1330 add operator controller that can eliminate co-scheduled pods that should be separate
  pkg/operator/onepodpernodeccontroller/onepodpernode_controller.go
  pkg/operator/onepodpernodeccontroller/onepodpernode_controller_test.go
Labels: approved, lgtm

#1333 Adding method from cvo for capabilities
  pkg/manifest/manifest.go
  pkg/manifest/manifest_test.go
Labels: approved, lgtm
