Repository openshift/library-go, pull requests merged in 2022-05, with the labels that each got.

#1355 4.10: Re-create StorageClass to change immutable parameters
  pkg/operator/resource/resourceapply/storage.go
  pkg/operator/resource/resourceapply/storage_test.go
Labels: approved, lgtm

#1362 updates signature of WaitForAPIServerToStabilizeOnTheSameRevision function
  test/library/apiserver/apiserver.go
  test/library/library.go
  test/library/pod_same_revision.go
  test/library/pod_same_revision_test.go
Labels: approved, lgtm

#1365 moves `IsSNOCheckFnc` to a common place
  pkg/operator/staticpod/controller/common/helpers.go
  pkg/operator/staticpod/controller/guard/guard_controller.go
  pkg/operator/staticpod/controller/guard/guard_controller_test.go
Labels: approved, lgtm

#1347 Bug 2064024: Increase timeout for missing static pods
  pkg/operator/staticpod/controller/missingstaticpod/missing_static_pod_controller.go
  pkg/operator/staticpod/controller/missingstaticpod/missing_static_pod_controller_test.go
  pkg/operator/staticpod/controllers.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#1367 Fix ApplyService to detect new Service spec
  pkg/operator/resource/resourceapply/core.go
  pkg/operator/resource/resourceapply/core_test.go
Labels: approved, lgtm

#1368 Bug 2084331: pkg/manifest/manifest.go: Fix checkResourceEnablement
  pkg/manifest/manifest.go
  pkg/manifest/manifest_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1371 Bug 2071998: pkg/verify: Expose store error details, especially slow access
  pkg/verify/configmap_test.go
  pkg/verify/store/configmap/configmap.go
  pkg/verify/store/memory/memory.go
  pkg/verify/store/parallel/parallel.go
  pkg/verify/store/parallel/parallel_test.go
  pkg/verify/store/serial/serial.go
  pkg/verify/store/serial/serial_test.go
  pkg/verify/store/sigstore/sigstore.go
  pkg/verify/store/sigstore/sigstore_test.go
  pkg/verify/store/store.go
  pkg/verify/verify.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high
