Repository openshift/library-go, pull requests merged in 2022-09, with the labels that each got.

#1394 Bug 2073220: routes/status resources can leak sensitive data
  pkg/operator/apiserver/audit/manifests/allrequestbodies-rules.yaml
  pkg/operator/apiserver/audit/manifests/writerequestbodies-rules.yaml
  pkg/operator/apiserver/audit/testdata/allrequestbodies.yaml
  pkg/operator/apiserver/audit/testdata/audit-policies-cm-scenario-1.yaml
  pkg/operator/apiserver/audit/testdata/multipleCr.yaml
  pkg/operator/apiserver/audit/testdata/oauth.yaml
  pkg/operator/apiserver/audit/testdata/writerequestbodies.yaml
  pkg/verify/configmap_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#1396 Add KubevirtPlatformType to external platforms
  pkg/cloudprovider/external.go
  pkg/cloudprovider/external_test.go
  pkg/operator/configobserver/cloudprovider/observe_cloudprovider_test.go
Labels: approved, lgtm

#1397 AUTH-296: crypto: add a CA{} method for creating subCAs, too
  pkg/crypto/crypto.go
Labels: approved, lgtm

#1398 crypto: fix the EnsureSubCA function failing to read the serial.txt file
  pkg/crypto/crypto.go
  pkg/crypto/crypto_test.go
Labels: approved, lgtm

#1400 Bug 2101520: Log right error when initializing delegating authentication
  pkg/config/serving/server.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low
