Repository openshift/library-go, pull requests merged in 2022-04, with the labels that each got.

#1344 assign recorder for one pod per node controller
  pkg/operator/onepodpernodeccontroller/onepodpernode_controller.go
Labels: approved, lgtm

#1343 Adding unit tests to cover nil pointer cases of Include()
  pkg/manifest/manifest_test.go
Labels: approved, lgtm

#1346 pkg/manifest: Add methods to support capability implicit enablement
  pkg/manifest/manifest.go
  pkg/manifest/manifest_test.go
Labels: approved, lgtm

#1349 Bug 2067775: Update prometheus client_golang from 1.11.0 => 1.11.1
  go.mod
  go.sum
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1351 controller factory: allow enqueuing multiple objects in eventHandler
  pkg/controller/factory/controller_context.go
  pkg/controller/factory/controller_context_test.go
  pkg/controller/factory/factory.go
Labels: approved, lgtm

#1345 add storage class controller
  pkg/operator/csi/csicontrollerset/csi_controller_set.go
  pkg/operator/csi/csistorageclasscontroller/csi_storageclass_controller.go
  pkg/operator/csi/csistorageclasscontroller/csi_storageclass_controller_test.go
Labels: approved, lgtm

#1340 Bug 2063953: extend rest mapping with job definition
  pkg/client/openshiftrestmapper/hardcoded_restmapper.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#1354 [4.10] add storage class controller
  pkg/operator/csi/csicontrollerset/csi_controller_set.go
  pkg/operator/csi/csistorageclasscontroller/csi_storageclass_controller.go
  pkg/operator/csi/csistorageclasscontroller/csi_storageclass_controller_test.go
Labels: approved, lgtm

#1358 Bug 2071998: pkg/verify: Expose underlying signature errors
  pkg/verify/verify.go
  pkg/verify/verify_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#1357 Bug 1958198: Avoid zero resync interval
  pkg/operator/csr/csr_approver.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#1361 Suppress 'No Recognised Cloud Provider' warning for Nutanix
  pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
Labels: approved, lgtm
