Repository openshift/library-go, pull requests merged in 2023-12, with the labels that each got.

#1642 OCPBUGS-21846: Revert "OCPBUGS-21846: revision_controller: be more verbose about LatestAvailableRevision and resourceVersion"
  pkg/operator/revisioncontroller/revision_controller.go
  pkg/operator/v1helpers/helpers.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1641 OCPBUGS-21846: revision_controller: update last revision only when a revision is completely rendered
  pkg/operator/revisioncontroller/revision_controller.go
  pkg/operator/revisioncontroller/revision_controller_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1640 Add option to skip setting cloud-provider=external
  pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
  pkg/operator/configobserver/cloudprovider/observe_cloudprovider_test.go
Labels: approved, lgtm

#1644 AUTH-471: pkg/operator/status - add EvaluationConditionDetected
  pkg/operator/status/condition.go
  pkg/operator/status/status_controller.go
  pkg/operator/status/status_controller_test.go
Labels: approved, lgtm, jira/valid-reference

#1638 skip change event on challenge response
  pkg/operator/status/status_controller.go
  pkg/operator/status/status_controller_test.go
Labels: approved, lgtm

#1636 OCPBUGS-24226: setting TLSSecurityProfile with no minTLSVersion crashes controller
  pkg/operator/csi/csidrivercontrollerservicecontroller/helpers.go
  pkg/operator/csi/csidrivercontrollerservicecontroller/helpers_test.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#1645 OCPBUGS-25345: sort errs to void flapping messages
  pkg/operator/staticpod/controller/guard/guard_controller.go
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference

#1639 HOSTEDCP-1344: pkg/crypto: expose an unsafe self-signed cert generator
  pkg/crypto/crypto.go
  pkg/crypto/crypto_test.go
Labels: approved, lgtm, jira/valid-reference

#1648 Bump golang 1.21
  .ci-operator.yaml
  go.mod
  go.sum
  pkg/crypto/cert_accept_reject_test.go
Labels: approved, lgtm

#1649 TRT-1420: Revert "revision_controller: update last revision only when a revisio…
  pkg/operator/revisioncontroller/revision_controller.go
  pkg/operator/revisioncontroller/revision_controller_test.go
Labels: approved, lgtm, jira/valid-reference

#1650 Bump rhel to 9 to match other repositories
  .ci-operator.yaml
Labels: approved, lgtm
