Repository openshift/library-go, pull requests merged in 2023-10, with the labels that each got.

#1578 [release-4.12] OCPBUGS-19837: Update staticpod file permissions to conform with CIS benchmarks
  pkg/operator/staticpod/installerpod/cmd.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1568 move code from cluster-debug-tools for reuse in origin
  pkg/certs/cert-inspection/certgraphanalysis/analyzer.go
  pkg/certs/cert-inspection/certgraphanalysis/ca_bundle.go
  pkg/certs/cert-inspection/certgraphanalysis/certkeypair.go
  pkg/certs/cert-inspection/certgraphanalysis/collector.go
  pkg/certs/cert-inspection/certgraphanalysis/deduplication.go
  pkg/certs/cert-inspection/certgraphanalysis/nameguessing.go
  pkg/certs/cert-inspection/certgraphapi/types.go
  vendor/k8s.io/apimachinery/pkg/util/duration/duration.go
  vendor/modules.txt
Labels: approved, lgtm

#1580 cert-inspection: update MCO cert name
  pkg/certs/cert-inspection/certgraphanalysis/nameguessing.go
Labels: approved, lgtm

#1581 certgraphanalysis: add funcs to inspect CSRs
  pkg/certs/cert-inspection/certgraphanalysis/analyzer.go
Labels: approved, lgtm

#1582 cert-inspection: add GatherCertsFromPlatformNamespaces, PKIRegistryInfo
  pkg/certs/cert-inspection/certgraphanalysis/collector.go
  pkg/certs/cert-inspection/certgraphanalysis/nameguessing.go
  pkg/certs/cert-inspection/certgraphapi/type_registry.go
  pkg/certs/cert-inspection/certgraphutils/util.go
Labels: approved, lgtm

#1583 cert-inspection: remove InspectCSRv1beta1
  pkg/certs/cert-inspection/certgraphanalysis/analyzer.go
Labels: approved, lgtm

#1584 track metadata from incluster secrets and configmaps
  go.mod
  go.sum
  pkg/certs/cert-inspection/certgraphanalysis/collector.go
  pkg/certs/cert-inspection/certgraphapi/types.go
  vendor/github.com/openshift/api/.gitignore
  vendor/github.com/openshift/api/Dockerfile.rhel8
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/annotations/annotations.go
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_image.crd.yaml
  vendor/github.com/openshift/api/config/v1/feature_gates.go
  vendor/github.com/openshift/api/config/v1/stable.clusterversion.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/helm/v1beta1/00_helm-chart-repository.crd.yaml
  vendor/github.com/openshift/api/helm/v1beta1/00_project-helm-chart-repository.crd.yaml
  vendor/github.com/openshift/api/helm/v1beta1/stable.helmchartrepository.testsuite.yaml
  vendor/github.com/openshift/api/helm/v1beta1/stable.projecthelmchartrepository.testsuite.yaml
  vendor/github.com/openshift/api/kubecontrolplane/v1/types.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/legacyconfig/v1/types.go
  vendor/github.com/openshift/api/legacyconfig/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_80_machine-config-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/register.go
  vendor/github.com/openshift/api/operator/v1/stable.ingresscontroller.testsuite.yaml
  vendor/github.com/openshift/api/operator/v1/stable.machineconfiguration.testsuite.yaml
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_machineconfiguration.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm

#1587 Allow enabling HTTP, the default is off
  pkg/config/serving/server.go
  pkg/controller/controllercmd/builder.go
  pkg/controller/controllercmd/cmd.go
Labels: approved, lgtm

#1588 Allow enabling HTTP, the default is off [4.14]
  pkg/config/serving/server.go
  pkg/controller/controllercmd/builder.go
  pkg/controller/controllercmd/cmd.go
Labels: approved, lgtm, backport-risk-assessed

#1589 Allow enabling HTTP, the default is off [4.13]
  pkg/config/serving/server.go
  pkg/controller/controllercmd/builder.go
  pkg/controller/controllercmd/cmd.go
Labels: approved, lgtm, backport-risk-assessed

#1590 Allow enabling HTTP, the default is off [4.12]
  pkg/config/serving/server.go
  pkg/controller/controllercmd/builder.go
  pkg/controller/controllercmd/cmd.go
Labels: approved, lgtm, backport-risk-assessed

#1595 pkg/operator/certrotation: add stlaz for review/approve
  pkg/operator/certrotation/OWNERS
Labels: approved, lgtm

#1593 certrotation: add more options for consumers
  pkg/operator/certrotation/cabundle.go
  pkg/operator/certrotation/client_cert_rotation_controller.go
  pkg/operator/certrotation/signer.go
  pkg/operator/certrotation/target.go
Labels: approved, lgtm

#1599 allow skipping revisioned secrets and configmaps
  pkg/certs/cert-inspection/certgraphanalysis/collector.go
  pkg/certs/cert-inspection/certgraphanalysis/options.go
Labels: approved, lgtm

#1600 skip revisioned
  pkg/certs/cert-inspection/certgraphanalysis/options.go
Labels: approved, lgtm
