Repository openshift/library-go, pull requests merged in 2023-06, with the labels that each got.

#1543 Add OWNERS file for cloudprovider package
  pkg/cloudprovider/OWNERS
Labels: approved, lgtm

#1535 OCPBUGS-13946: report fast resync interval only when > 0 and < 60
  pkg/controller/factory/base_controller.go
  pkg/controller/factory/factory.go
Labels: approved, lgtm, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1537 factory/base_controller: properly synchronize runPeriodicalResync function
  pkg/controller/factory/base_controller.go
Labels: approved, lgtm

#1534 WRKLDS-728: controller/apiservice: allow to disable/delete an API service resources
  pkg/operator/apiserver/controller/apiservice/apiservice_controller.go
  pkg/operator/apiserver/controller/apiservice/apiservice_controller_test.go
Labels: approved, lgtm, ¯\_(ツ)_/¯

#1547 pkg/manifest: Add Manifest.String() method
  pkg/manifest/manifest.go
  pkg/manifest/manifest_test.go
Labels: approved, lgtm

#1541 OCPBUGS-14824: library-go: `ApplyStorageClass()` must not ignore `Res…
  pkg/operator/csi/csistorageclasscontroller/csi_storageclass_controller.go
  pkg/operator/resource/resourceapply/storage.go
  pkg/operator/resource/resourceapply/storage_test.go
Labels: approved, lgtm, px-approved, docs-approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#1546 OCPBUGS-15256: installerpod: change config map based files mode to 0600
  pkg/operator/staticpod/installerpod/cmd.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
