Repository openshift/library-go, pull requests merged in 2023-03, with the labels that each got.

#1463 [4.12] OCPBUGS-6789: expose method for finding featuregates
  pkg/operator/configobserver/featuregates/observe_featuregates.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1476 Add encryption tests OWNERS
  test/e2e-encryption/OWNERS
  test/library/encryption/OWNERS
Labels: approved, lgtm

#1480 Revert "Merge pull request #1477 from dgrisonnet/fix-encryption-test"
  test/library/encryption/helpers.go
Labels: approved, lgtm

#1481 Use leases for leader election
  pkg/config/leaderelection/leaderelection.go
  pkg/controller/controllercmd/builder.go
Labels: approved, lgtm

#1479 [release-4.10] OCPBUGS-8235: Guard controller: set the readiness probe endpoint explicitly
  pkg/operator/staticpod/controller/guard/bindata/bindata.go
  pkg/operator/staticpod/controller/guard/guard_controller.go
  pkg/operator/staticpod/controller/guard/guard_controller_test.go
  pkg/operator/staticpod/controller/guard/manifests/guard-pod.yaml
  pkg/operator/staticpod/controllers.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1483 revision: add more context to reason messages
  pkg/operator/revisioncontroller/revision_controller.go
Labels: approved, lgtm

#1475 Add AES-GCM to the encryption test library
  go.mod
  go.sum
  pkg/operator/configobserver/featuregates/observe_featuregates_test.go
  test/library/encryption/assertion.go
  test/library/encryption/perf_scenarios.go
  test/library/encryption/scenarios.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml-patch
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/stable.apiserver.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/stable.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.apiserver.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1/types_nutanixprovider.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1beta1/types_gcpprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm

#1487 make leader election option "LeaseDuration/RenewDeadline/RetryPeriod" configurable
  pkg/config/leaderelection/leaderelection.go
  pkg/controller/controllercmd/cmd.go
Labels: approved, lgtm

#1491 OCPBUGS-10887: usercache: fix race when groups are removed from user informer
  pkg/oauth/usercache/groups.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1489 OCPBUGS-8691: Allow CSI driver operators to override nodeSelector on HyperShift
  pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-important, jira/valid-bug, jira/valid-reference
