Repository openshift/library-go, pull requests merged in 2023-11, with the labels that each got.

#1592 cert-inspection: remove hardcoded cert description and name guessing
  pkg/certs/cert-inspection/certgraphanalysis/collector.go
  pkg/certs/cert-inspection/certgraphanalysis/nameguessing.go
  pkg/certs/cert-inspection/certgraphapi/types.go
  pkg/certs/cert-inspection/certgraphutils/util.go
Labels: approved, lgtm

#1602 guard: add workload partitioning annotation
  pkg/operator/staticpod/controller/guard/guard_controller_test.go
  pkg/operator/staticpod/controller/guard/manifests/guard-pod.yaml
Labels: approved, lgtm

#1615 Fix klog invocations
  pkg/operator/csi/csistorageclasscontroller/csi_storageclass_controller.go
  pkg/operator/staticpod/installerpod/cmd.go
  pkg/operator/staticpod/startupmonitor/cmd.go
Labels: approved, lgtm

#1617 add option to rewrite the proxy-ca for reduced size and understanding
  pkg/certs/cert-inspection/certgraphanalysis/collection_options.go
  pkg/certs/cert-inspection/certgraphanalysis/collector.go
  pkg/certs/cert-inspection/certgraphanalysis/metadata_options.go
  pkg/certs/cert-inspection/certgraphanalysis/options.go
Labels: approved, lgtm

#1618 certgraphanalysis: add SkipHashed option
  pkg/certs/cert-inspection/certgraphanalysis/collection_options.go
  pkg/certs/cert-inspection/certgraphanalysis/collector.go
Labels: approved, lgtm

#1616 [release-4.13] AUTH-443: add support for oauth authorization code flow
  pkg/oauth/tokenrequest/callback_server.go
  pkg/oauth/tokenrequest/request_token.go
  pkg/oauth/tokenrequest/request_token_test.go
Labels: approved, lgtm, cherry-pick-approved, jira/valid-reference

#1619 catch all proxy-cas
  pkg/certs/cert-inspection/certgraphanalysis/collector.go
  pkg/certs/cert-inspection/certgraphanalysis/filtering_options.go
  pkg/certs/cert-inspection/certgraphanalysis/metadata_options.go
Labels: approved, lgtm

#1620 OCPBUGS-18697: guard controller: re-create pods with phase nor pending neither running
  pkg/operator/staticpod/controller/guard/guard_controller.go
  pkg/operator/staticpod/controller/guard/guard_controller_test.go
Labels: approved, lgtm, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1611 STOR-1453: CSI: Set TLS ciphers based on observed configuration
  pkg/operator/configobserver/apiserver/observe_tlssecurityprofile.go
  pkg/operator/csi/csiconfigobservercontroller/csi_config_observer_controller.go
  pkg/operator/csi/csiconfigobservercontroller/csi_config_observer_controller_test.go
  pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller.go
  pkg/operator/csi/csidrivercontrollerservicecontroller/helpers.go
  pkg/operator/csi/csidrivercontrollerservicecontroller/helpers_test.go
Labels: approved, lgtm, jira/valid-reference

#1623 OCPCLOUD-2256: resourceapply: ApplyClusterRole, add support for aggregation rules
  pkg/operator/resource/resourceapply/rbac.go
Labels: approved, lgtm, jira/valid-reference

#1614 OCPBUGS-23796: add pdbUnhealthyPodEvictionPolicy option to a GuardController
  pkg/operator/staticpod/controller/guard/guard_controller.go
  pkg/operator/staticpod/controllers.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1631 OCPBUGS-21846: revision_controller: be more verbose about LatestAvailableRevision and resourceVersion
  pkg/operator/revisioncontroller/revision_controller.go
  pkg/operator/v1helpers/helpers.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1630 make status reporting reuse name of CertRotationController
  pkg/operator/certrotation/client_cert_rotation_controller.go
Labels: approved, lgtm

#1594 cert rotation: add optional jira component and description annotations to TLS artifacts
  pkg/operator/certrotation/annotations.go
  pkg/operator/certrotation/cabundle.go
  pkg/operator/certrotation/signer.go
  pkg/operator/certrotation/target.go
  pkg/operator/csr/cert_controller.go
  pkg/operator/resourcesynccontroller/core.go
Labels: approved, lgtm

#1632 controllercmd: allow configuring topology detection
  pkg/controller/controllercmd/builder.go
  pkg/controller/controllercmd/builder_test.go
Labels: approved, lgtm

#1633 controllercmd: bubble up topology detection to the top
  pkg/controller/controllercmd/cmd.go
Labels: approved, lgtm

#1635 Add ability to collect whitelisted annotations specified by the caller
  pkg/certs/cert-inspection/certgraphanalysis/collection_options.go
  pkg/certs/cert-inspection/certgraphanalysis/collector.go
  pkg/certs/cert-inspection/certgraphanalysis/filtering_options.go
  pkg/certs/cert-inspection/certgraphanalysis/metadata_options.go
  pkg/certs/cert-inspection/certgraphapi/type_registry.go
Labels: approved, lgtm

#1637 fix accidental recursion
  pkg/certs/cert-inspection/certgraphanalysis/collection_options.go
Labels: approved, lgtm
