Repository openshift/library-go, pull requests merged in 2023-09, with the labels that each got.

#1569 USHIFT-1593: Regenerate certs on hostname changes
  pkg/crypto/crypto.go
  pkg/crypto/crypto_test.go
Labels: approved, lgtm, jira/valid-reference

#1573 Bump openshift/*
  go.mod
  go.sum
  vendor/k8s.io/kube-openapi/pkg/cached/cache.go
  vendor/k8s.io/kube-openapi/pkg/handler/handler.go
  vendor/k8s.io/kube-openapi/pkg/handler3/handler.go
  vendor/modules.txt
Labels: approved, lgtm, acknowledge-critical-fixes-only

#1570 OCPBUGS-16796: pkg/operator: update static pod manifests perms
  pkg/operator/staticpod/installerpod/cmd.go
Labels: approved, lgtm, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1577 [release-4.13] OCPBUGS-19825: Update staticpod file permissions to conform with CIS benchmarks
  pkg/operator/staticpod/installerpod/cmd.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
