Repository openshift/library-go, pull requests merged in 2023-01, with the labels that each got.

#1430 OCPBUGS-1341: Remove stale pod network connectivity checks
  pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/informers/externalversions/factory.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/informers/externalversions/operatorcontrolplane/interface.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/informers/externalversions/operatorcontrolplane/v1alpha1/interface.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/informers/externalversions/operatorcontrolplane/v1alpha1/podnetworkconnectivitycheck.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/listers/operatorcontrolplane/v1alpha1/expansion_generated.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/listers/operatorcontrolplane/v1alpha1/podnetworkconnectivitycheck.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug

#1418 [release-4.10] OCPBUGS-5345: routes/status resources can leak sensitive data
  pkg/operator/apiserver/audit/bindata/bindata.go
  pkg/operator/apiserver/audit/manifests/allrequestbodies-rules.yaml
  pkg/operator/apiserver/audit/manifests/writerequestbodies-rules.yaml
  pkg/operator/apiserver/audit/testdata/allrequestbodies.yaml
  pkg/operator/apiserver/audit/testdata/audit-policies-cm-scenario-1.yaml
  pkg/operator/apiserver/audit/testdata/multipleCr.yaml
  pkg/operator/apiserver/audit/testdata/oauth.yaml
  pkg/operator/apiserver/audit/testdata/writerequestbodies.yaml
Labels: approved, lgtm

#1453 expose method for finding featuregates
  pkg/operator/configobserver/featuregates/observe_featuregates.go
Labels: approved, lgtm

#1451 [OCPCLOUD-1818] Migrate vSphere to out of tree cloudprovider
  pkg/cloudprovider/external.go
  pkg/cloudprovider/external_test.go
Labels: lgtm, do-not-merge/hold

#1455 OCPBUGS-4551: [release-4.11] guard controller: set an explicit hostname to avoid name collisions
  pkg/operator/staticpod/controller/guard/guard_controller.go
  pkg/operator/staticpod/controller/guard/guard_controller_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-important, jira/valid-bug

#1456 STOR-947: allow separate evaluation of storage class state
  pkg/operator/csi/csistorageclasscontroller/csi_storageclass_controller.go
Labels: approved, lgtm

#1450 Extend check controller with server side apply
  pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
Labels: approved, lgtm

#1457 WRKLDS-649: Guard controller: set the readiness probe endpoint explicitly
  pkg/operator/staticpod/controller/guard/guard_controller.go
  pkg/operator/staticpod/controller/guard/guard_controller_test.go
  pkg/operator/staticpod/controller/guard/manifests/guard-pod.yaml
  pkg/operator/staticpod/controllers.go
Labels: approved, lgtm, jira/valid-reference

#1459 STOR-1128: Export code that sets CSI StorageClass as the default one
  pkg/operator/csi/csistorageclasscontroller/csi_storageclass_controller.go
Labels: approved, lgtm, jira/valid-reference
