Repository openshift/library-go, pull requests merged in 2024-01, with the labels that each got.

#1572 OCPBUGS-19056: apiserver: optimize IsLongRunningRequest
  pkg/apiserver/apiserverconfig/longrunning.go
  pkg/apiserver/apiserverconfig/longrunning_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1651 Fix ordering bug
  pkg/operator/revisioncontroller/revision_controller.go
  pkg/operator/revisioncontroller/revision_controller_test.go
Labels: approved, lgtm

#1657 move diff before update to klog v2
  pkg/operator/resource/resourceapply/admissionregistration.go
  pkg/operator/resource/resourceapply/apiextensions.go
  pkg/operator/resource/resourceapply/apiregistration.go
  pkg/operator/resource/resourceapply/apps.go
  pkg/operator/resource/resourceapply/core.go
  pkg/operator/resource/resourceapply/migration.go
  pkg/operator/resource/resourceapply/monitoring.go
  pkg/operator/resource/resourceapply/policy.go
  pkg/operator/resource/resourceapply/rbac.go
  pkg/operator/resource/resourceapply/storage.go
  pkg/operator/resource/resourceapply/volumesnapshotclass.go
Labels: approved, lgtm, jira/valid-reference

#1658 when updating status, do a live GET after conflict
  pkg/operator/configobserver/config_observer_controller_test.go
  pkg/operator/genericoperatorclient/dynamic_operator_client.go
  pkg/operator/genericoperatorclient/dynamic_staticpod_operator_client.go
  pkg/operator/managementstatecontroller/management_state_controller_test.go
  pkg/operator/status/status_controller_test.go
  pkg/operator/v1helpers/helpers.go
  pkg/operator/v1helpers/interfaces.go
  pkg/operator/v1helpers/test_helpers.go
Labels: approved, lgtm

#1659 add featuregate reading and writing
  pkg/operator/resource/resourceread/config.go
Labels: approved, lgtm

#1613 cert-inspect: collect certificates from disk
  pkg/certs/cert-inspection/certgraphanalysis/certkeypair.go
  pkg/certs/cert-inspection/certgraphanalysis/collector.go
  pkg/certs/cert-inspection/certgraphanalysis/deduplication.go
  pkg/certs/cert-inspection/certgraphanalysis/disk_certs.go
  pkg/certs/cert-inspection/certgraphanalysis/metadata_options.go
  pkg/certs/cert-inspection/certgraphapi/types.go
Labels: approved, lgtm

#1653 expose more funcs for etcd cert_rotation
  pkg/operator/certrotation/cabundle.go
  pkg/operator/certrotation/cabundle_test.go
  pkg/operator/certrotation/client_cert_rotation_controller.go
  pkg/operator/certrotation/signer.go
  pkg/operator/certrotation/signer_test.go
  pkg/operator/certrotation/target.go
  pkg/operator/certrotation/target_test.go
Labels: approved, lgtm

#1663 expose combine location cert metadata functions
  pkg/certs/cert-inspection/certgraphanalysis/deduplication.go
Labels: approved, lgtm

#1664 [release-4.15] When updating status, do a live GET after conflict & Move diff before update to klog v2
  pkg/operator/configobserver/config_observer_controller_test.go
  pkg/operator/genericoperatorclient/dynamic_operator_client.go
  pkg/operator/genericoperatorclient/dynamic_staticpod_operator_client.go
  pkg/operator/managementstatecontroller/management_state_controller_test.go
  pkg/operator/resource/resourceapply/admissionregistration.go
  pkg/operator/resource/resourceapply/apiextensions.go
  pkg/operator/resource/resourceapply/apiregistration.go
  pkg/operator/resource/resourceapply/apps.go
  pkg/operator/resource/resourceapply/core.go
  pkg/operator/resource/resourceapply/migration.go
  pkg/operator/resource/resourceapply/monitoring.go
  pkg/operator/resource/resourceapply/policy.go
  pkg/operator/resource/resourceapply/rbac.go
  pkg/operator/resource/resourceapply/storage.go
  pkg/operator/resource/resourceapply/volumesnapshotclass.go
  pkg/operator/status/status_controller_test.go
  pkg/operator/v1helpers/helpers.go
  pkg/operator/v1helpers/interfaces.go
  pkg/operator/v1helpers/test_helpers.go
Labels: approved, lgtm

#1668 prefer lister when its resourceVersion is different than the last try
  pkg/operator/v1helpers/helpers.go
Labels: approved, lgtm

#1672 reduce the noise on diffs to on request
  pkg/operator/v1helpers/helpers.go
Labels: approved, lgtm

#1671 [4.15] pick for lister reuse
  pkg/operator/v1helpers/helpers.go
Labels: approved, lgtm

#1501 chore: replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`
  go.mod
  go.sum
  pkg/assets/create/creater.go
  pkg/operator/configobserver/config_observer_controller_test.go
  pkg/operator/configobserver/masterurl/observe_masterurl_test.go
  pkg/operator/configobserver/network/observe_networking_test.go
  pkg/operator/csi/csidrivercontrollerservicecontroller/helpers_test.go
  pkg/operator/csi/csidrivernodeservicecontroller/helpers_test.go
  pkg/operator/render/options/generic.go
  pkg/operator/resource/resourceapply/monitoring_test.go
  pkg/operator/resource/resourceapply/volumesnapshotclass_test.go
  pkg/operator/v1helpers/helpers.go
  vendor/github.com/ghodss/yaml/.gitignore
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test
