Repository openshift/library-go, pull requests merged in 2024-03, with the labels that each got.

#1681 OCPBUGS-30119: certrotation: update all secret types to `kubernetes.io/tls` preserving existing content
  pkg/operator/certrotation/metadata.go
  pkg/operator/certrotation/signer.go
  pkg/operator/certrotation/signer_test.go
  pkg/operator/certrotation/target.go
  pkg/operator/certrotation/target_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1688 OCPBUGS-30304: [release-4.15] certrotation: update all secret types to kubernetes.io/tls preserving existing content
  pkg/operator/certrotation/annotations.go
  pkg/operator/certrotation/cabundle.go
  pkg/operator/certrotation/metadata.go
  pkg/operator/certrotation/signer.go
  pkg/operator/certrotation/signer_test.go
  pkg/operator/certrotation/target.go
  pkg/operator/certrotation/target_test.go
  pkg/operator/csr/cert_controller.go
  pkg/operator/resourcesynccontroller/core.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1689 NO-JIRA: certoration: fix a typo when setting AutoRegenerateAfterOfflineExpiry
  pkg/operator/certrotation/annotations.go
Labels: approved, lgtm, jira/valid-reference

#1690 NO-JIRA: cert-inspection: replace node name from annotation value
  pkg/certs/cert-inspection/certgraphanalysis/metadata_options.go
Labels: approved, lgtm, jira/valid-reference

#1686 OCPBUGS-30319: oauthserviceaccountclient: expect that there might be no tokens associated with SA
  pkg/oauth/oauthserviceaccountclient/oauthclientregistry.go
  pkg/oauth/oauthserviceaccountclient/oauthclientregistry_test.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#1555 Switch to blang/semver/v4
  go.mod
  go.sum
  pkg/image/imageutil/helpers.go
  pkg/operator/staticpod/installerpod/cmd.go
  pkg/operator/versioning/compare.go
  pkg/operator/versioning/compare_test.go
  vendor/github.com/blang/semver/.travis.yml
  vendor/github.com/blang/semver/LICENSE
  vendor/github.com/blang/semver/README.md
  vendor/github.com/blang/semver/json.go
  vendor/github.com/blang/semver/package.json
  vendor/github.com/blang/semver/range.go
  vendor/github.com/blang/semver/semver.go
  vendor/github.com/blang/semver/sort.go
  vendor/github.com/blang/semver/sql.go
  vendor/modules.txt
Labels: approved, lgtm

#1698 add featuregate summarization for oc and api
  pkg/features/feature_diff_summary.go
  pkg/features/summarizer.go
  pkg/markdown/markdown.go
Labels: approved, lgtm

#1701 Use syscalls conditionally only for linux
  pkg/certs/cert-inspection/certgraphanalysis/disk_certs.go
  pkg/certs/cert-inspection/certgraphanalysis/locationmetadata.go
  pkg/certs/cert-inspection/certgraphanalysis/locationmetadata_unsupported.go
Labels: approved, lgtm

#1700 add validatingadmissionpolicy reading
  pkg/operator/resource/resourceread/admission.go
Labels: approved, lgtm
