Repository openshift/library-go, pull requests merged in 2024-08, with the labels that each got.

#1773 OCPBUGS-38335: Revert "use update only secret-apply for cert rotation logic"
  pkg/operator/certrotation/signer.go
  pkg/operator/certrotation/signer_test.go
  pkg/operator/certrotation/target.go
  pkg/operator/certrotation/target_test.go
  pkg/operator/resource/resourceapply/core.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1772 OCPBUGS-38335: certrotation: avoid using applySecret to catch racy cert updates
  pkg/operator/certrotation/cabundle.go
  pkg/operator/certrotation/cabundle_test.go
  pkg/operator/certrotation/signer.go
  pkg/operator/certrotation/signer_test.go
  pkg/operator/certrotation/target.go
  pkg/operator/certrotation/target_test.go
  pkg/operator/resource/resourceapply/admissionregistration.go
  pkg/operator/resource/resourceapply/apiextensions.go
  pkg/operator/resource/resourceapply/apiregistration.go
  pkg/operator/resource/resourceapply/apps.go
  pkg/operator/resource/resourceapply/core.go
  pkg/operator/resource/resourceapply/event_helpers.go
  pkg/operator/resource/resourceapply/migration.go
  pkg/operator/resource/resourceapply/monitoring.go
  pkg/operator/resource/resourceapply/policy.go
  pkg/operator/resource/resourceapply/rbac.go
  pkg/operator/resource/resourceapply/storage.go
  pkg/operator/resource/resourceapply/volumesnapshotclass.go
  pkg/operator/resource/resourcehelper/event_helpers.go
  pkg/operator/resource/resourcehelper/event_helpers_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1776 certgraphanalysis: update bootstrap name lookup
  pkg/certs/cert-inspection/certgraphanalysis/collector.go
Labels: approved, lgtm

#1778 SPLAT-1772: drop vars removed in api#1780
  pkg/cloudprovider/external.go
Labels: approved, lgtm, jira/valid-reference

#1779 NO-JIRA: Expand approvers for library-go
  OWNERS
Labels: approved, lgtm, jira/valid-reference

#1775 OCPCLOUD-2565: Updates features to support adding to FlagSet
  pkg/features/features.go
Labels: approved, lgtm, jira/valid-reference

#1784 OCPBUGS-39255: resourcehelper: handle nil object when guessing GVK
  pkg/operator/resource/resourcehelper/resource_helpers.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
