Repository openshift/library-go, pull requests merged in 2024-10, with the labels that each got.

#1796 OCPBUGS-36233: Replicas hook consider Control plane topology
  pkg/operator/csi/csidrivercontrollerservicecontroller/helpers.go
  pkg/operator/csi/csidrivercontrollerservicecontroller/helpers_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1819 audit: do not log requests to /livez
  pkg/operator/apiserver/audit/manifests/base-policy.yaml
  pkg/operator/apiserver/audit/testdata/allrequestbodies.yaml
  pkg/operator/apiserver/audit/testdata/default.yaml
  pkg/operator/apiserver/audit/testdata/multipleCr.yaml
  pkg/operator/apiserver/audit/testdata/none.yaml
  pkg/operator/apiserver/audit/testdata/oauth.yaml
  pkg/operator/apiserver/audit/testdata/writerequestbodies.yaml
Labels: approved, lgtm

#1811 API-1835: add mutation tracking to the fake client
  pkg/manifestclient/mutation_tracker.go
  pkg/manifestclient/read_roundtripper.go
  pkg/manifestclient/readwrite_roundtripper.go
  pkg/manifestclient/write_roundtripper.go
  pkg/manifestclienttest/client_test.go
  pkg/manifestclienttest/client_write_test.go
  pkg/manifestclienttest/informer_test.go
  pkg/operator/genericoperatorclient/dynamic_operator_client.go
  pkg/operator/genericoperatorclient/dynamic_staticpod_operator_client.go
  pkg/operator/genericoperatorclient/test_operator_client.go
Labels: approved, lgtm, jira/valid-reference

#1818 refactor dynamic client creation and add testing ones
  pkg/operator/genericoperatorclient/dynamic_operator_client.go
  pkg/operator/genericoperatorclient/dynamic_staticpod_operator_client.go
  pkg/operator/genericoperatorclient/test_operator_client.go
Labels: approved

#1805 STOR-1988: support GCP WIF in credentials request controller
  pkg/operator/csi/credentialsrequestcontroller/credentials_request_controller.go
  pkg/operator/csi/credentialsrequestcontroller/credentials_request_controller_test.go
Labels: approved, lgtm, jira/valid-reference

#1824 API-1835: demonstrate how we will store desired mutations
  pkg/manifestclient/mutation_directory_reader.go
  pkg/manifestclient/mutation_directory_writer.go
  pkg/manifestclient/mutation_tracker.go
  pkg/manifestclient/readwrite_roundtripper.go
  pkg/manifestclient/serialized_request.go
  pkg/manifestclient/serialized_request_test.go
  pkg/manifestclient/write_roundtripper.go
  pkg/manifestclienttest/client_test.go
  pkg/manifestclienttest/client_write_test.go
  pkg/manifestclienttest/testdata/mutation-tests/APPLY-STATUS-crd-in-dataset-with-options/ApplyStatus/cluster-scoped/config.openshift.io/featuregates/001-body-new-item.yaml
  pkg/manifestclienttest/testdata/mutation-tests/APPLY-STATUS-crd-in-dataset-with-options/ApplyStatus/cluster-scoped/config.openshift.io/featuregates/001-options-new-item.yaml
  pkg/manifestclienttest/testdata/mutation-tests/APPLY-crd-in-dataset/Apply/cluster-scoped/config.openshift.io/featuregates/001-body-new-item.yaml
  pkg/manifestclienttest/testdata/mutation-tests/APPLY-crd-in-dataset/Apply/cluster-scoped/config.openshift.io/featuregates/001-options-new-item.yaml
  pkg/manifestclienttest/testdata/mutation-tests/CREATE-crd-in-dataset/Create/cluster-scoped/config.openshift.io/featuregates/001-body-new-item.yaml
  pkg/manifestclienttest/testdata/mutation-tests/CREATE-crd-not-in-dataset/Create/cluster-scoped/config.openshift.io/apiservers/001-body-new-item.yaml
  pkg/manifestclienttest/testdata/mutation-tests/DELETE-crd-in-dataset/Delete/cluster-scoped/config.openshift.io/featuregates/001-body-cluster.yaml
  pkg/manifestclienttest/testdata/mutation-tests/UPDATE-STATUS-crd-in-dataset-with-options/UpdateStatus/cluster-scoped/config.openshift.io/featuregates/001-body-new-item.yaml
  pkg/manifestclienttest/testdata/mutation-tests/UPDATE-STATUS-crd-in-dataset-with-options/UpdateStatus/cluster-scoped/config.openshift.io/featuregates/001-options-new-item.yaml
  pkg/manifestclienttest/testdata/mutation-tests/UPDATE-crd-in-dataset/Update/cluster-scoped/config.openshift.io/featuregates/001-body-new-item.yaml
  pkg/operator/genericoperatorclient/dynamic_operator_client.go
  pkg/operator/genericoperatorclient/dynamic_staticpod_operator_client.go
  pkg/operator/genericoperatorclient/test_operator_client.go
  pkg/operator/v1helpers/canonicalize.go
Labels: approved, lgtm, jira/valid-reference

#1827 API-1835: add clock to client for injection
  pkg/operator/genericoperatorclient/dynamic_operator_client.go
  pkg/operator/genericoperatorclient/dynamic_staticpod_operator_client.go
  pkg/operator/genericoperatorclient/test_operator_client.go
  pkg/operator/v1helpers/canonicalize.go
Labels: approved, jira/valid-reference

#1826 intro json patch library
  pkg/apiserver/jsonpatch/jsonpatch.go
  pkg/apiserver/jsonpatch/jsonpatch_test.go
Labels: approved, lgtm

#1828 NO-JIRA: don't use unnecessary generics
  pkg/manifestclient/mutation_tracker.go
Labels: approved, lgtm, jira/valid-reference

#1829 Add test-e2e-monitoring placeholder rule
  Makefile
Labels: approved, lgtm

#1832 add waitforcachesync
  pkg/operator/v1helpers/informers.go
Labels: approved, lgtm

#1835 NO-JIRA: jsonpatch: don't put test operations at the beginning
  pkg/apiserver/jsonpatch/jsonpatch.go
  pkg/apiserver/jsonpatch/jsonpatch_test.go
Labels: approved, lgtm, jira/valid-reference

#1834 add ability to read kinds from other namespaces for list
  pkg/manifestclient/list.go
  pkg/manifestclient/serialized_request.go
  pkg/manifestclienttest/client_test.go
  pkg/manifestclienttest/testdata/must-gather-01/namespaces/openshift-authentication-operator/core/configmaps/foo.yaml
  pkg/manifestclienttest/testdata/mutation-tests/APPLY-STATUS-crd-in-dataset-with-options/ApplyStatus/cluster-scoped-resources/config.openshift.io/featuregates/001-body-new-item.yaml
  pkg/manifestclienttest/testdata/mutation-tests/APPLY-STATUS-crd-in-dataset-with-options/ApplyStatus/cluster-scoped-resources/config.openshift.io/featuregates/001-options-new-item.yaml
  pkg/manifestclienttest/testdata/mutation-tests/APPLY-crd-in-dataset/Apply/cluster-scoped-resources/config.openshift.io/featuregates/001-body-new-item.yaml
  pkg/manifestclienttest/testdata/mutation-tests/APPLY-crd-in-dataset/Apply/cluster-scoped-resources/config.openshift.io/featuregates/001-options-new-item.yaml
  pkg/manifestclienttest/testdata/mutation-tests/CREATE-crd-in-dataset/Create/cluster-scoped-resources/config.openshift.io/featuregates/001-body-new-item.yaml
  pkg/manifestclienttest/testdata/mutation-tests/CREATE-crd-not-in-dataset/Create/cluster-scoped-resources/config.openshift.io/apiservers/001-body-new-item.yaml
  pkg/manifestclienttest/testdata/mutation-tests/DELETE-crd-in-dataset/Delete/cluster-scoped-resources/config.openshift.io/featuregates/001-body-cluster.yaml
  pkg/manifestclienttest/testdata/mutation-tests/UPDATE-STATUS-crd-in-dataset-with-options/UpdateStatus/cluster-scoped-resources/config.openshift.io/featuregates/001-body-new-item.yaml
  pkg/manifestclienttest/testdata/mutation-tests/UPDATE-STATUS-crd-in-dataset-with-options/UpdateStatus/cluster-scoped-resources/config.openshift.io/featuregates/001-options-new-item.yaml
  pkg/manifestclienttest/testdata/mutation-tests/UPDATE-crd-in-dataset/Update/cluster-scoped-resources/config.openshift.io/featuregates/001-body-new-item.yaml
Labels: approved, lgtm

#1837 add p0lyn0mial to OWNERS
  OWNERS
Labels: approved, lgtm

#1838 API-1835: realign manifestclient on fs.FS
  pkg/manifestclient/encoding.go
  pkg/manifestclient/get.go
  pkg/manifestclient/group_resource_discovery.go
  pkg/manifestclient/list.go
  pkg/manifestclient/mutation_directory_reader.go
  pkg/manifestclient/read_roundtripper.go
  pkg/manifestclient/readwrite_roundtripper.go
  pkg/manifestclienttest/client_test.go
  pkg/manifestclienttest/client_write_test.go
Labels: approved, lgtm, jira/valid-reference

#1839 NO-JIRA: make it easier to locate diffs in serialized requests
  pkg/manifestclient/mutation_tracker.go
  pkg/manifestclient/serialized_request.go
Labels: approved, lgtm, jira/valid-reference

#1840 API-1835: add ability to get and list namespaces from must-gather
  pkg/manifestclient/get.go
  pkg/manifestclient/list.go
  pkg/manifestclienttest/client_test.go
Labels: approved, lgtm, jira/valid-reference

#1842 NO-JIRA: jsonpatch: forbid testing resourceVersion
  pkg/apiserver/jsonpatch/jsonpatch.go
  pkg/apiserver/jsonpatch/jsonpatch_test.go
Labels: approved, lgtm, jira/valid-reference

#1844 NO-JIRA: node_controller: change newTargetNodeState assignment and rename to triggerStatusApplyError
  pkg/operator/staticpod/controller/node/node_controller.go
  pkg/operator/staticpod/controller/node/node_controller_test.go
Labels: approved, lgtm, jira/valid-reference

#1841 API-1835: use discovery for the discovery endpoint
  pkg/manifestclient/default-discovery/README.md
  pkg/manifestclient/default-discovery/aggregated-discovery-api.yaml
  pkg/manifestclient/default-discovery/aggregated-discovery-apis.yaml
  pkg/manifestclient/group_resource_discovery.go
  pkg/manifestclient/list.go
  pkg/manifestclient/read_roundtripper.go
  pkg/manifestclienttest/client_test.go
  pkg/manifestclienttest/informer_test.go
  pkg/manifestclienttest/testdata/must-gather-02/aggregated-discovery-api.yaml
  pkg/manifestclienttest/testdata/must-gather-02/aggregated-discovery-apis.yaml
  pkg/manifestclienttest/testdata/must-gather-02/namespaces/present/apps/daemonsets.yaml
Labels: approved, lgtm, jira/valid-reference

#1830 API-1835: Migrate WorkloadController to SSA
  pkg/operator/apiserver/controller/workload/workload.go
  pkg/operator/apiserver/controller/workload/workload_test.go
Labels: approved, lgtm, jira/valid-reference

#1843 OCPBUGS-43509: add resourceread functions for ValidatingAdmissionPolicyV1
  pkg/operator/resource/resourceread/admission.go
  pkg/operator/resource/resourceread/admission_test.go
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference

#1848 NO-JIRA: ability to trigger an err on status apply
  pkg/operator/staticpod/controller/node/node_controller_test.go
  pkg/operator/v1helpers/test_helpers.go
Labels: approved, lgtm, jira/valid-reference

#1854 NO-JIRA: test_helpers: take into account existin operatorstatus when applying …
  pkg/operator/v1helpers/test_helpers.go
Labels: approved, lgtm, jira/valid-reference

#1850 NO-JIRA: enable TLS 1.3 ciphers
  pkg/crypto/crypto.go
  pkg/operator/configobserver/apiserver/observe_tlssecurityprofile_test.go
  pkg/operator/csi/csiconfigobservercontroller/csi_config_observer_controller_test.go
Labels: approved, lgtm, jira/valid-reference

#1851 API-1835: add generateName for mutation: came up on CSRs
  pkg/manifestclient/mutation_directory_reader.go
  pkg/manifestclient/mutation_tracker.go
  pkg/manifestclient/serialized_request.go
  pkg/manifestclient/serialized_request_test.go
  pkg/manifestclient/write_roundtripper.go
Labels: approved, lgtm, jira/valid-reference

#1845 API-1835: migrate the installer controller to SSA
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
  pkg/operator/staticpod/controllers.go
Labels: approved, lgtm, jira/valid-reference

#1859 OCPBUGS-42932: ensure annotations map exists before mutating it
  pkg/operator/revisioncontroller/revision_controller.go
Labels: approved, lgtm, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1860 API-1835: manifestclient: set/get a controller name in the ctx
  pkg/manifestclient/context.go
  pkg/manifestclient/context_test.go
Labels: approved, lgtm, jira/valid-reference

#1853 API-1835: Migrate multiple controllers to SSA
  pkg/operator/apiserver/controllerset/apiservercontrollerset.go
  pkg/operator/encryption/controllers.go
  pkg/operator/encryption/controllers/condition_controller.go
  pkg/operator/encryption/controllers/key_controller.go
  pkg/operator/encryption/controllers/migration_controller.go
  pkg/operator/encryption/controllers/prune_controller.go
  pkg/operator/encryption/controllers/prune_controller_test.go
  pkg/operator/encryption/controllers/state_controller.go
  pkg/operator/managementstatecontroller/management_state_controller.go
  pkg/operator/managementstatecontroller/management_state_controller_test.go
  pkg/operator/staticpod/controllers.go
  pkg/operator/unsupportedconfigoverridescontroller/unsupportedconfigoverrides_controller.go
Labels: approved, lgtm, jira/valid-reference

#1857 API-1835: tremendously increase QPS for manifest client to avoid delay
  pkg/manifestclient/readwrite_roundtripper.go
Labels: approved, lgtm, jira/valid-reference

#1863 API-1835: make manifestclient list work when no namespaces are present
  pkg/manifestclient/list.go
  pkg/manifestclienttest/client_test.go
  pkg/manifestclienttest/testdata/no-namespaces/cluster-scoped-resources/config.openshift.io/featuregates/cluster.yaml
Labels: approved, lgtm, jira/valid-reference

#1866 API-1825: revisioncontroller: add controller-instance-name label to secrets and configMaps
  pkg/operator/resource/resourceapply/core.go
  pkg/operator/resource/resourceapply/core_test.go
  pkg/operator/revisioncontroller/revision_controller.go
Labels: approved, lgtm, jira/valid-reference

#1867 API-1835: manifestclient/write_roundtripper: refine the the controller name annotation key
  pkg/manifestclient/context.go
  pkg/manifestclient/context_test.go
  pkg/manifestclient/mutation_tracker.go
  pkg/manifestclient/write_roundtripper.go
  pkg/manifestclienttest/client_write_test.go
  pkg/manifestclienttest/testdata/mutation-tests/UPDATE-crd-in-dataset-with-controller-name/Update/cluster-scoped-resources/config.openshift.io/featuregates/001-body-new-item.yaml
Labels: approved, lgtm, jira/valid-reference
