Repository openshift/library-go, pull requests merged in 2024-05, with the labels that each got.

#1730 [release-4.15] OCPBUGS-33210: oauthserviceaccountclient: expect that there might be no tokens associated with SA
  pkg/oauth/oauthserviceaccountclient/oauthclientregistry.go
  pkg/oauth/oauthserviceaccountclient/oauthclientregistry_test.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#1679 OCPBUGS-29126: deploymentcontroller: use builder pattern
  pkg/operator/deploymentcontroller/deployment_controller.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1692 OCPCLOUD-2513: Remove cloud-provider and cloud-config flags
  pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
  pkg/operator/configobserver/cloudprovider/observe_cloudprovider_test.go
Labels: approved, lgtm, jira/valid-reference

#1734 OCPBUGS-24061: Keep CSI operators progressing=true during DaemonSet rollout
  pkg/operator/csi/csidrivernodeservicecontroller/csi_driver_node_service_controller.go
Labels: approved, lgtm, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1735 OCPBUGS-33574: reduce error message details for Not Found secret
  pkg/route/validation/validation.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference

#1728 OCPBUGS-32370: Add TLS config to CSI driver daemonset
  pkg/operator/csi/csidrivernodeservicecontroller/csi_driver_node_service_controller.go
  pkg/operator/csi/csidrivernodeservicecontroller/csi_driver_node_service_controller_test.go
Labels: approved, lgtm, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1736 Return empty configuration from cloud observer
  pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
  pkg/operator/configobserver/cloudprovider/observe_cloudprovider_test.go
Labels: approved, lgtm

#1738 API-1783: Bump 1.30.1
  go.mod
  go.sum
  vendor/github.com/openshift/api/authorization/v1/generated.proto
  vendor/github.com/openshift/api/authorization/v1/types.go
  vendor/github.com/openshift/api/authorization/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_console.go
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_image_content_policy.go
  vendor/github.com/openshift/api/config/v1/types_image_digest_mirror_set.go
  vendor/github.com/openshift/api/config/v1/types_image_tag_mirror_set.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_node.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/types_project.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/features.md
  vendor/github.com/openshift/api/features/features.go
  vendor/github.com/openshift/api/machine/v1/types_aws.go
  vendor/github.com/openshift/api/machine/v1/types_controlplanemachineset.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/machine/v1beta1/types_machine.go
  vendor/github.com/openshift/api/machine/v1beta1/types_machinehealthcheck.go
  vendor/github.com/openshift/api/machine/v1beta1/types_machineset.go
  vendor/github.com/openshift/api/machine/v1beta1/types_provider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1alpha1/types_image_content_source_policy.go
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/quota/v1/generated.proto
  vendor/github.com/openshift/api/quota/v1/types.go
  vendor/github.com/openshift/api/quota/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/api/security/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/client-go/apps/applyconfigurations/internal/internal.go
  vendor/github.com/openshift/client-go/config/applyconfigurations/internal/internal.go
  vendor/github.com/openshift/client-go/operator/applyconfigurations/internal/internal.go
  vendor/github.com/openshift/client-go/operator/applyconfigurations/operator/v1/consolespec.go
  vendor/github.com/openshift/client-go/operator/applyconfigurations/operator/v1/ingress.go
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/client-go/applyconfigurations/internal/internal.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#1677 OCPBUGS-22332: route: Improve errors for missing custom-host permissions
  pkg/route/hostassignment/assignment.go
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference
