Repository openshift/library-go, pull requests merged in 2024-07, with the labels that each got.

#1748 Add support for ValidatingAdmissionPolicy v1
  pkg/operator/resource/resourceapply/admissionregistration.go
Labels: approved, lgtm

#1719 Avoid using sets when existing slices suffice
  pkg/config/validation/general.go
  pkg/controller/factory/controller_context.go
  pkg/oauth/tokenrequest/request_token.go
  pkg/operator/configobserver/featuregates/featuregate.go
  pkg/operator/configobserver/featuregates/observe_featuregates_test.go
  pkg/operator/encryption/controllers/prune_controller.go
  pkg/operator/staticpod/prune/cmd.go
  pkg/route/validation/validation.go
Labels: approved, lgtm

#1757 add junit types for serializing junit directly
  test/library/junitapi/types.go
Labels: approved, lgtm

#1758 remove unnecessary comment
  test/library/junitapi/types.go
Labels: approved, lgtm

#1759 NO-ISSUE: pkg/manifest: Restore CustomNoUpgrade handling
  pkg/manifest/manifest.go
  pkg/manifest/manifest_test.go
Labels: approved, lgtm, jira/valid-reference

#1720 NO-JIRA: certrotation: improve error messages
  pkg/operator/certrotation/cabundle.go
  pkg/operator/certrotation/cabundle_test.go
  pkg/operator/certrotation/client_cert_rotation_controller.go
  pkg/operator/certrotation/signer.go
  pkg/operator/certrotation/target.go
Labels: approved, lgtm, jira/valid-reference

#1729 On disk fake client
  pkg/manifestclient/encoding.go
  pkg/manifestclient/get.go
  pkg/manifestclient/group_resource_discovery.go
  pkg/manifestclient/io.go
  pkg/manifestclient/list.go
  pkg/manifestclient/roundtripper.go
  pkg/manifestclienttest/client_test.go
  pkg/manifestclienttest/informer_test.go
  pkg/manifestclienttest/testdata/must-gather-01/cluster-scoped-resources/apiextensions.k8s.io/customresourcedefinitions/adminpolicybasedexternalroutes.k8s.ovn.org.yaml
  pkg/manifestclienttest/testdata/must-gather-01/cluster-scoped-resources/apiextensions.k8s.io/customresourcedefinitions/alertingrules.monitoring.openshift.io.yaml
  pkg/manifestclienttest/testdata/must-gather-01/cluster-scoped-resources/config.openshift.io/featuregates.yaml
  pkg/manifestclienttest/testdata/must-gather-01/cluster-scoped-resources/config.openshift.io/featuregates/cluster.yaml
  pkg/manifestclienttest/testdata/must-gather-01/namespaces/openshift-apiserver/apps/daemonsets.yaml
  pkg/manifestclienttest/testdata/must-gather-01/namespaces/openshift-apiserver/apps/deployments.yaml
  pkg/manifestclienttest/testdata/must-gather-01/namespaces/openshift-apiserver/apps/replicasets.yaml
  pkg/manifestclienttest/testdata/must-gather-01/namespaces/openshift-apiserver/apps/statefulsets.yaml
  pkg/manifestclienttest/testdata/must-gather-01/namespaces/openshift-apiserver/core/secrets.yaml
  pkg/manifestclienttest/testdata/must-gather-01/namespaces/openshift-apiserver/core/secrets/pull-secret.yaml
  pkg/manifestclienttest/testdata/must-gather-01/namespaces/openshift-apiserver/openshift-apiserver.yaml
  pkg/manifestclienttest/testdata/must-gather-01/namespaces/openshift-authentication-operator/apps/daemonsets.yaml
  pkg/manifestclienttest/testdata/must-gather-01/namespaces/openshift-authentication-operator/apps/deployments.yaml
  pkg/manifestclienttest/testdata/must-gather-01/namespaces/openshift-authentication-operator/apps/replicasets.yaml
  pkg/manifestclienttest/testdata/must-gather-01/namespaces/openshift-authentication-operator/apps/statefulsets.yaml
  pkg/manifestclienttest/testdata/must-gather-01/namespaces/openshift-authentication-operator/openshift-authentication-operator.yaml
  pkg/manifestclienttest/testdata/must-gather-01/namespaces/openshift-authentication/apps/daemonsets.yaml
  pkg/manifestclienttest/testdata/must-gather-01/namespaces/openshift-authentication/apps/deployments.yaml
  pkg/manifestclienttest/testdata/must-gather-01/namespaces/openshift-authentication/apps/replicasets.yaml
  pkg/manifestclienttest/testdata/must-gather-01/namespaces/openshift-authentication/apps/statefulsets.yaml
  pkg/manifestclienttest/testdata/must-gather-01/namespaces/openshift-authentication/openshift-authentication.yaml
Labels: approved, lgtm

#1769 OCPBUGS-37488: csi: add tools image to csi controller
  pkg/operator/csi/csidrivercontrollerservicecontroller/helpers.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference
