Repository openshift/library-go, pull requests merged in 2024-12, with the labels that each got.

#1813 NO-JIRA: OWNERS_ALIASES: Update the username of David Hurta
  OWNERS_ALIASES
Labels: approved, lgtm, jira/valid-reference

#1898 configobserver: drop observer for minimum kubelet version
  pkg/operator/configobserver/node/observe_minimum_kubelet_version.go
  pkg/operator/configobserver/node/observe_minimum_kubelet_version_test.go
Labels: approved, lgtm

#1900 OCPBUGS-44374: CSI controller conditions should provide reason and message
  pkg/operator/csi/csidrivernodeservicecontroller/csi_driver_node_service_controller.go
  pkg/operator/deploymentcontroller/deployment_controller.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1906 API-1835: manifestclient: format jsonpatch payloads
  pkg/manifestclient/write_roundtripper.go
  pkg/manifestclienttest/client_write_test.go
  pkg/manifestclienttest/testdata/mutation-tests/PATCH-crd-in-dataset/Patch/cluster-scoped-resources/config.openshift.io/featuregates/943a-body-instance-name.yaml
  pkg/manifestclienttest/testdata/mutation-tests/PATCH-crd-in-dataset/Patch/cluster-scoped-resources/config.openshift.io/featuregates/943a-metadata-instance-name.yaml
  pkg/manifestclienttest/testdata/mutation-tests/PATCH-crd-in-dataset/Patch/cluster-scoped-resources/config.openshift.io/featuregates/bd0d-body-instance-name.yaml
  pkg/manifestclienttest/testdata/mutation-tests/PATCH-crd-in-dataset/PatchStatus/cluster-scoped-resources/config.openshift.io/featuregates/943a-body-instance-name.yaml
  pkg/manifestclienttest/testdata/mutation-tests/PATCH-crd-in-dataset/PatchStatus/cluster-scoped-resources/config.openshift.io/featuregates/943a-metadata-instance-name.yaml
  pkg/manifestclienttest/testdata/mutation-tests/PATCH-crd-in-dataset/PatchStatus/cluster-scoped-resources/config.openshift.io/featuregates/bd0d-body-instance-name.yaml
Labels: approved, lgtm, jira/valid-reference

#1882 OCPEDGE-1309: feat: add arbiter node check
  pkg/operator/staticpod/controller/guard/guard_controller.go
  pkg/operator/staticpod/controller/guard/guard_controller_test.go
  pkg/operator/staticpod/controller/node/node_controller.go
  pkg/operator/staticpod/controller/node/node_controller_test.go
  pkg/operator/staticpod/controllers.go
Labels: approved, lgtm, jira/valid-reference

#1910 NO-JIRA: operator/node-controller, guard-controller: parse the master node selector during construction
  pkg/operator/staticpod/controller/guard/guard_controller.go
  pkg/operator/staticpod/controller/guard/guard_controller_test.go
  pkg/operator/staticpod/controller/node/node_controller.go
  pkg/operator/staticpod/controller/node/node_controller_test.go
Labels: approved, lgtm, jira/valid-reference

#1905 feat(pkg/operator/csr): add NewServiceAccountMultiSubjectsApprover approver
  pkg/operator/csr/csr_approver.go
  pkg/operator/csr/csr_approver_test.go
Labels: approved, lgtm
