Repository openshift/library-go, pull requests merged in 2024-09, with the labels that each got.

#1780 audit/manifests: log requests to Events
  pkg/operator/apiserver/audit/manifests/base-policy.yaml
  pkg/operator/apiserver/audit/testdata/allrequestbodies.yaml
  pkg/operator/apiserver/audit/testdata/audit-policies-cm-scenario-1.yaml
  pkg/operator/apiserver/audit/testdata/default.yaml
  pkg/operator/apiserver/audit/testdata/multipleCr.yaml
  pkg/operator/apiserver/audit/testdata/none.yaml
  pkg/operator/apiserver/audit/testdata/oauth.yaml
  pkg/operator/apiserver/audit/testdata/writerequestbodies.yaml
Labels: approved, lgtm

#1786 Add support for deletion of deployment and daemonset via DeleteAll fu…
  pkg/operator/resource/resourceapply/apps.go
  pkg/operator/resource/resourceapply/apps_test.go
  pkg/operator/resource/resourceapply/generic.go
Labels: approved, lgtm

#1746 OCPBUGS-35231: cert-inspection: parse secret/configmap/files as kubeconfigs
  pkg/certs/cert-inspection/certgraphanalysis/analyzer.go
  pkg/certs/cert-inspection/certgraphanalysis/collector.go
  pkg/certs/cert-inspection/certgraphanalysis/disk_certs.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1740 OCPBUGS-33958: retrieve registered secret name from secretManager
  pkg/route/secretmanager/fake/fake_manager.go
  pkg/route/secretmanager/manager.go
  pkg/route/secretmanager/manager_test.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#1781 ETCD-612 Added callback to provide preconditions for revision controller
  pkg/operator/apiserver/controllerset/apiservercontrollerset.go
  pkg/operator/revisioncontroller/revision_controller.go
  pkg/operator/revisioncontroller/revision_controller_test.go
  pkg/operator/staticpod/controllers.go
Labels: approved, lgtm

#1787 API-1835: Apply operator status
  pkg/controller/factory/base_controller.go
  pkg/controller/factory/interfaces.go
  pkg/operator/README.md
  pkg/operator/apiserver/controller/apiservice/apiservice_controller.go
  pkg/operator/configobserver/config_observer_controller_test.go
  pkg/operator/genericoperatorclient/dynamic_operator_client.go
  pkg/operator/genericoperatorclient/dynamic_staticpod_operator_client.go
  pkg/operator/managementstatecontroller/management_state_controller_test.go
  pkg/operator/resourcesynccontroller/resourcesync_controller.go
  pkg/operator/staticresourcecontroller/static_resource_controller.go
  pkg/operator/status/status_controller_test.go
  pkg/operator/v1helpers/canonicalize.go
  pkg/operator/v1helpers/interfaces.go
  pkg/operator/v1helpers/test_helpers.go
Labels: approved, lgtm, jira/valid-reference

#1795 API-1835: use SSA in CSI controllers
  go.mod
  go.sum
  pkg/operator/csi/csidrivernodeservicecontroller/csi_driver_node_service_controller.go
  pkg/operator/csi/csidrivernodeservicecontroller/csi_driver_node_service_controller_test.go
  pkg/operator/deploymentcontroller/deployment_controller.go
  pkg/operator/deploymentcontroller/deployment_controller_test.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/client-go/operator/applyconfigurations/internal/internal.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#1800 API-1835: add Kind to static pod operator client creation
  pkg/operator/genericoperatorclient/dynamic_staticpod_operator_client.go
Labels: approved, lgtm, jira/valid-reference

#1798 API-1835: set the last transition time for conditions
  pkg/operator/genericoperatorclient/dynamic_operator_client.go
  pkg/operator/v1helpers/canonicalize.go
Labels: approved, lgtm, jira/valid-reference

#1790 Add jan as approver
  OWNERS
  pkg/operator/OWNERS
  pkg/operator/csi/OWNERS
Labels: approved, lgtm

#1794 API-1835: Apply 02 more loops
  pkg/controller/factory/interfaces.go
  pkg/operator/README.md
  pkg/operator/apiserver/controller/apiservice/apiservice_controller.go
  pkg/operator/apiserver/controller/auditpolicy/auditpolicy_controller.go
  pkg/operator/apiserver/controller/nsfinalizer/finalizer_controller.go
  pkg/operator/apiserver/controller/workload/workload.go
  pkg/operator/apiserver/controllerset/apiservercontrollerset.go
  pkg/operator/certrotation/client_cert_rotation_controller.go
  pkg/operator/configobserver/config_observer_controller.go
  pkg/operator/configobserver/config_observer_controller_test.go
  pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
  pkg/operator/csi/credentialsrequestcontroller/credentials_request_controller.go
  pkg/operator/csi/csiconfigobservercontroller/csi_config_observer_controller.go
  pkg/operator/csi/csidrivernodeservicecontroller/csi_driver_node_service_controller.go
  pkg/operator/csi/csistorageclasscontroller/csi_storageclass_controller.go
  pkg/operator/csr/cert_controller.go
  pkg/operator/csr/csr_approver.go
  pkg/operator/deploymentcontroller/deployment_controller.go
  pkg/operator/encryption/controllers/condition_controller.go
  pkg/operator/encryption/controllers/key_controller.go
  pkg/operator/encryption/controllers/migration_controller.go
  pkg/operator/encryption/controllers/prune_controller.go
  pkg/operator/encryption/controllers/state_controller.go
  pkg/operator/eventwatch/controller.go
  pkg/operator/latencyprofilecontroller/controller.go
  pkg/operator/loglevel/logging_controller.go
  pkg/operator/managementstatecontroller/management_state_controller.go
  pkg/operator/metricscontroller/metrics_controller.go
  pkg/operator/onepodpernodeccontroller/onepodpernode_controller.go
  pkg/operator/resourcesynccontroller/resourcesync_controller.go
  pkg/operator/resourcesynccontroller/resourcesync_controller_test.go
  pkg/operator/revisioncontroller/revision_controller.go
  pkg/operator/secretspruner/prune_controller.go
  pkg/operator/staleconditions/remove_stale_conditions.go
  pkg/operator/staticpod/certsyncpod/certsync_controller.go
  pkg/operator/staticpod/controller/guard/guard_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/installerstate/installer_state_controller.go
  pkg/operator/staticpod/controller/missingstaticpod/missing_static_pod_controller.go
  pkg/operator/staticpod/controller/node/node_controller.go
  pkg/operator/staticpod/controller/prune/prune_controller.go
  pkg/operator/staticpod/controller/startupmonitorcondition/startup_monitor_condition.go
  pkg/operator/staticpod/controller/staticpodfallback/static_pod_fallback_condition.go
  pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  pkg/operator/staticresourcecontroller/static_resource_controller.go
  pkg/operator/status/status_controller.go
  pkg/operator/unsupportedconfigoverridescontroller/unsupportedconfigoverrides_controller.go
Labels: approved, lgtm, jira/valid-reference

#1804 API-1835: prevent conditions missing information
  pkg/operator/genericoperatorclient/dynamic_operator_client.go
Labels: approved, lgtm, jira/valid-reference

#1806 API-1835: Update the installer state controller to use Apply
  pkg/operator/staticpod/controller/installerstate/installer_state_controller.go
  pkg/operator/staticpod/controller/installerstate/installer_state_controller_test.go
  pkg/operator/staticpod/controllers.go
  pkg/operator/v1helpers/test_helpers.go
Labels: approved, lgtm, jira/valid-reference

#1812 API-1835: fix initialization of variable in deployment controller
  pkg/operator/deploymentcontroller/deployment_controller.go
Labels: approved, lgtm, jira/valid-reference

#1801 API-1835: update the revision controller to use the type moved latestrevision
  go.mod
  go.sum
  pkg/operator/apiserver/controllerset/apiservercontrollerset.go
  pkg/operator/configobserver/node/suppress_config_updates_test.go
  pkg/operator/revisioncontroller/revision_controller.go
  pkg/operator/revisioncontroller/revision_controller_test.go
  pkg/operator/revisioncontroller/staticpod.go
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
  pkg/operator/staticpod/controller/node/node_controller_test.go
  pkg/operator/staticpod/controller/prune/prune_controller_test.go
  pkg/operator/staticpod/controllers.go
  pkg/operator/v1helpers/test_helpers.go
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_openshiftapiserver.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/operator/applyconfigurations/internal/internal.go
  vendor/github.com/openshift/client-go/operator/applyconfigurations/operator/v1/authenticationstatus.go
  vendor/github.com/openshift/client-go/operator/applyconfigurations/operator/v1/cloudcredentialstatus.go
  vendor/github.com/openshift/client-go/operator/applyconfigurations/operator/v1/clustercsidriverstatus.go
  vendor/github.com/openshift/client-go/operator/applyconfigurations/operator/v1/configstatus.go
  vendor/github.com/openshift/client-go/operator/applyconfigurations/operator/v1/consolestatus.go
  vendor/github.com/openshift/client-go/operator/applyconfigurations/operator/v1/csisnapshotcontrollerstatus.go
  vendor/github.com/openshift/client-go/operator/applyconfigurations/operator/v1/etcdstatus.go
  vendor/github.com/openshift/client-go/operator/applyconfigurations/operator/v1/insightsoperatorstatus.go
  vendor/github.com/openshift/client-go/operator/applyconfigurations/operator/v1/kubeapiserverstatus.go
  vendor/github.com/openshift/client-go/operator/applyconfigurations/operator/v1/kubecontrollermanagerstatus.go
  vendor/github.com/openshift/client-go/operator/applyconfigurations/operator/v1/kubeschedulerstatus.go
  vendor/github.com/openshift/client-go/operator/applyconfigurations/operator/v1/kubestorageversionmigratorstatus.go
  vendor/github.com/openshift/client-go/operator/applyconfigurations/operator/v1/networkstatus.go
  vendor/github.com/openshift/client-go/operator/applyconfigurations/operator/v1/openshiftapiserverstatus.go
  vendor/github.com/openshift/client-go/operator/applyconfigurations/operator/v1/openshiftcontrollermanagerstatus.go
  vendor/github.com/openshift/client-go/operator/applyconfigurations/operator/v1/operatorstatus.go
  vendor/github.com/openshift/client-go/operator/applyconfigurations/operator/v1/servicecastatus.go
  vendor/github.com/openshift/client-go/operator/applyconfigurations/operator/v1/servicecatalogapiserverstatus.go
  vendor/github.com/openshift/client-go/operator/applyconfigurations/operator/v1/servicecatalogcontrollermanagerstatus.go
  vendor/github.com/openshift/client-go/operator/applyconfigurations/operator/v1/staticpodoperatorstatus.go
  vendor/github.com/openshift/client-go/operator/applyconfigurations/operator/v1/storagestatus.go
  vendor/github.com/openshift/client-go/operator/applyconfigurations/operator/v1alpha1/olmstatus.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference
