Repository openshift/library-go, pull requests merged in 2024-04, with the labels that each got.

#1705 use update only secret-apply for cert rotation logic
  pkg/operator/certrotation/signer.go
  pkg/operator/certrotation/signer_test.go
  pkg/operator/certrotation/target.go
  pkg/operator/certrotation/target_test.go
  pkg/operator/resource/resourceapply/core.go
Labels: approved, lgtm

#1625 CFE-882: Route external certificate validation
  pkg/route/common.go
  pkg/route/hostassignment/assignment.go
  pkg/route/hostassignment/assignment_test.go
  pkg/route/hostassignment/externalcertificate.go
  pkg/route/hostassignment/externalcertificate_test.go
  pkg/route/validation/validation.go
  pkg/route/validation/validation_test.go
Labels: approved, lgtm, jira/valid-reference

#1706 CFE-882: add few test cases for external-certificate
  pkg/route/hostassignment/assignment.go
  pkg/route/hostassignment/assignment_test.go
Labels: approved, lgtm, jira/valid-reference

#1683 WRKLDS-1078: Revision controller not found no new revision 4.15
  pkg/operator/revisioncontroller/revision_controller.go
  pkg/operator/revisioncontroller/revision_controller_test.go
Labels: approved, lgtm, jira/valid-reference

#1707 add return flag when signer was regenerated
  pkg/operator/certrotation/client_cert_rotation_controller.go
  pkg/operator/certrotation/signer.go
  pkg/operator/certrotation/signer_test.go
Labels: approved, lgtm

#1710 OCPBUGS-31807: [release-4.15] use update only secret-apply for cert rotation logic
  pkg/operator/certrotation/signer.go
  pkg/operator/certrotation/signer_test.go
  pkg/operator/certrotation/target.go
  pkg/operator/certrotation/target_test.go
  pkg/operator/resource/resourceapply/core.go
Labels: approved, lgtm, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1714 operator/bootstrap: expose IsBootstrapComplete function
  pkg/operator/bootstrap/bootstrap.go
  pkg/operator/bootstrap/bootstrap_test.go
Labels: approved, lgtm

#1715 OCPBUGS-24195: controller/apiservice: support for defining multiple preconditions
  pkg/operator/apiserver/controller/apiservice/apigroup.go
  pkg/operator/apiserver/controller/apiservice/apiservice_controller.go
  pkg/operator/apiserver/controller/apiservice/apiservice_controller_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1694 OCPBUGS-24195: the apiservice controller waits until bootstrap complete
  pkg/operator/apiserver/controller/apiservice/apigroup.go
  pkg/operator/apiserver/controller/apiservice/apiservice_controller.go
  pkg/operator/apiserver/controller/apiservice/apiservice_controller_test.go
  pkg/operator/apiserver/controllerset/apiservercontrollerset.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1702 add validatingadmissionpolicy applying
  pkg/operator/resource/resourceapply/admissionregistration.go
  pkg/operator/resource/resourceapply/admissionregistration_test.go
  pkg/operator/resource/resourceapply/generic.go
Labels: approved, lgtm

#1673 certgraphapi: store ondisk location in PKIRegistryInfo
  pkg/certs/cert-inspection/certgraphapi/type_registry.go
  pkg/certs/cert-inspection/certgraphutils/util.go
Labels: approved, lgtm

#1697 OCPBUGS-31589: e2e: use bound API token for prometheus-k8s SA
  test/library/metrics/query.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1718 WRKLDS-1167: tolerate node-role.kubernetes.io/control-plane:NoExecute
  pkg/operator/staticpod/controller/guard/manifests/guard-pod.yaml
Labels: approved, lgtm, jira/valid-reference

#1675 CFE-866: feature: monitoring and handling "single" secret dynamically
  pkg/secret/OWNERS
  pkg/secret/fake/fake_secret_monitor.go
  pkg/secret/monitor.go
  pkg/secret/monitor_test.go
  pkg/secret/secret_monitor.go
  pkg/secret/secret_monitor_test.go
Labels: approved, lgtm, jira/valid-reference

#1626 CFE-866: Add secret manager for routes to consume secret_monitor
  pkg/route/secretmanager/fake/fake_manager.go
  pkg/route/secretmanager/manager.go
  pkg/route/secretmanager/manager_test.go
Labels: approved, lgtm, jira/valid-reference

#1725 cert collection: rewrite bootstrap IP in secret details
  pkg/certs/cert-inspection/certgraphanalysis/metadata_options.go
Labels: approved, lgtm

#1727 cert-rotation: replace RewriteBootstrapHostname with GetBootstrapHost…
  pkg/certs/cert-inspection/certgraphanalysis/collector.go
  pkg/certs/cert-inspection/certgraphanalysis/metadata_options.go
Labels: approved, lgtm
