Repository openshift/library-go, pull requests merged in 2025-01, with the labels that each got.

#1907 OCPBUGS-46372: Prevent node controller from stomping NodeStatus fields owned by installer controller
  pkg/operator/staticpod/controller/node/node_controller.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1919 wire custom clock into clusteroperator status controller
  pkg/config/clusteroperator/v1helpers/status.go
  pkg/operator/apiserver/controllerset/apiservercontrollerset.go
  pkg/operator/status/status_controller.go
  pkg/operator/status/status_controller_test.go
Labels: approved, lgtm

#1916 NO-JIRA: feat: add sort func for controller errors
  pkg/operator/v1helpers/helpers.go
Labels: approved, lgtm, jira/valid-reference

#1918 OCPBUGS-48276: Make the revision controller report degraded on error
  pkg/operator/revisioncontroller/revision_controller.go
  pkg/operator/revisioncontroller/revision_controller_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1914 OCPBUGS-24588: degrade when deployment progressing too long
  pkg/operator/apiserver/controller/workload/workload.go
  pkg/operator/deploymentcontroller/deployment_controller.go
  pkg/operator/v1helpers/helpers.go
Labels: approved, lgtm, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1913 OCPBUGS-45924: Prevent the installer controller from stomping statuses it just applied
  pkg/operator/staticpod/controller/installer/installer_controller.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1846 chore: use default timeout and proc count
  Makefile
Labels: approved, lgtm

#1929 OCPBUGS-45924: Fix "live get after write" in static pod installer controller.
  pkg/operator/staticpod/controller/installer/installer_controller.go
  pkg/operator/staticpod/controller/installer/installer_controller_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
