Repository openshift/library-go, pull requests merged in 2025-02, with the labels that each got.

#1923 Switch to canonical json-patch v4 import
  go.mod
  go.sum
  pkg/operator/resource/resourceapply/json_patch_helpers.go
  vendor/github.com/evanphx/json-patch/.gitignore
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/errors.go
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/modules.txt
Labels: approved, lgtm

#1934 NO-JIRA: certrotation: print diff when updating annotations
  pkg/operator/certrotation/annotations.go
Labels: approved, lgtm, jira/valid-reference

#1881 NO-JIRA: certgraphanalysis: save not-before and not-after, don't export to JSON
  pkg/certs/cert-inspection/certgraphanalysis/certkeypair.go
  pkg/certs/cert-inspection/certgraphapi/types.go
Labels: approved, lgtm, jira/valid-reference

#1922 [NO-JIRA]: add readApiServerOrDieV1 for kueue-operator work
  pkg/operator/resource/resourceread/apiregistration.go
Labels: approved, lgtm

#1940 OCPBUGS-51357: Only check deployment time when remaining in Progressing state
  pkg/operator/deploymentcontroller/deployment_controller.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference
