Repository openshift/library-go, pull requests merged in 2025-09, with the labels that each got.

#2006 OCPBUGS-54385: Add new helper to informers.go: NewKubeInformersForNamespacesWithResyncPeriod()
  pkg/operator/v1helpers/informers.go
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference

#2003 NO-JIRA: needNewTargetCertKeyPair: handle RefreshOnlyWhenExpired
  pkg/operator/certrotation/target.go
  pkg/operator/certrotation/target_test.go
Labels: approved, lgtm, jira/valid-reference

#2004 OCPBUGS-60045: certrotation: exit when received cabundle is empty
  pkg/operator/certrotation/client_cert_rotation_controller.go
  pkg/operator/certrotation/client_cert_rotation_controller_test.go
Labels: approved, lgtm, jira/severity-moderate, jira/valid-bug, jira/valid-reference
